### ISSUE TITLE
2018-Q2 1.1 Ship a needsdiagnosis issue dashboard

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#1]
Continuation of dashboard prototype begun in Q1.

The work is tracked here: https://github.com/webcompat/webcompat-metrics/issues/4

https://webcompat.github.io/webcompat-metrics-client/

**Comment by karlcow** [comment]
Repo has been created. Client part and server part will be separated.
I opened a couple of issues about the server.

**Comment by karlcow** [comment]
* Format discussed with @masgout https://github.com/webcompat/webcompat-metrics-server/issues/3
* Proto-coding started. Using Flask with python 3 (for now). 
* First commits should come next week.
* Gathered docs for heroku https://github.com/webcompat/webcompat-metrics-server/issues/1#issuecomment-382290693
* Data collection with a cron job https://github.com/webcompat/webcompat-metrics-server/issues/5

**Comment by karlcow** [comment]
* A first version of the data has been deployed see https://github.com/webcompat/webcompat-metrics/issues/4#issuecomment-384513114 and https://github.com/webcompat/webcompat-metrics-server/issues/7
* Discussion about domain names https://github.com/webcompat/webcompat-metrics-server/issues/6
* Current data converted to UTC and JSON

**Comment by karlcow** [comment]
* Requested a heroku account to Mozilla
* Made a temporary URL with hourly generated data accessible to @magsout

**Comment by magsout** [comment]
- refactoring some components
- added first Chart Line
- Made first draft of needsdiagnosis dashboard with a temporary URL from @karlcow

**Comment by karlcow** [comment]
Next OKR checking: May 15.

## 2018-05-03
* Heroku configured with automatic deployment 
<img width="1073" alt="capture d ecran 2018-05-03 a 10 40 58" src="https://user-images.githubusercontent.com/505230/39556894-be96ae00-4ebe-11e8-8c00-14e3d3b1dc8e.png">
* Github connected with master and staging branches for deployment on heroku.
* Reading docs… a lot of docs…

**Comment by magsout** [comment]
- reorganization of the repository, deleting of server-related files
- Travis added for automated testing
- Improved documentation

**Comment by karlcow** [comment]
* Struggling a bit last thursday/friday with the way to keep the data. Because Heroku will evaporate everything at each restart.
* Planned meeting with @magsout soon.

**Comment by magsout** [comment]
Meeting with @karlcow on this morning, we talked:
- about the granularity of the data (by day or by hour) https://github.com/webcompat/webcompat-metrics-server/issues/22
- figure out how to deploy server and client: https://github.com/webcompat/webcompat-metrics-server/issues/23
- the UI of the client: chart, form, homepage.
- a deadline for the first deployment (about 2 weeks 👍 )
- improved the delivery of the data (cached on client, gzip): https://github.com/webcompat/webcompat-metrics-server/issues/24

**Comment by magsout** [comment]
A little demo:
![screen recording 2018-05-18 at 05 33 pm](https://user-images.githubusercontent.com/1997108/40243868-a5217ed2-5ac1-11e8-9614-27cb0855cdd2.gif)

**Comment by miketaylr** [comment]
@karlcow @magsout things are looking good here, how would we rate confidence today? Still at 60%? It seems maybe higher?

**Comment by karlcow** [comment]
@miketaylr Probably after today. Yes! I'm finishing something today.

**Comment by karlcow** [comment]
* Added parameters handling https://github.com/webcompat/webcompat-metrics-server/issues/12

**Comment by miketaylr** [comment]
> @miketaylr oh, yes my PR for the code is waiting your review, after that I will push the script for deploy on GH pages, and it seems will be soon ready for the production

Awesome! Will get on that today.

**Comment by miketaylr** [comment]
status: Almost done. Need to solve one issue around CSP. The client can't fetch data from API server. Plan to do this right after work week.

**Comment by karlcow** [comment]
We have a finished working product

<img width="958" alt="capture d ecran 2018-06-20 a 05 30 37" src="https://user-images.githubusercontent.com/505230/41623206-f88d0600-744c-11e8-9a40-f0e0a7872b02.png">

That can now be improved through iterations.
https://github.com/webcompat/webcompat-metrics-server/issues/

OKR? 100%

**Comment by karlcow** [comment]
The client is visible at https://webcompat.github.io/webcompat-metrics-client/

**Comment by miketaylr** [comment]
Let's close this out, great work @karlcow and @magsout!

**Comment by miketaylr** [comment]
Score: 1.0.

Very strong collaborative work by Karl and Guillaume here.
https://webcompat.github.io/webcompat-metrics-client/?from=2018-05-19&to=2018-06-19
