### ISSUE TITLE
2019Q4 - 1.3 Manual testing on Facebook new design

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#100]

**Comment by miketaylr** [comment]
Update: Planning on getting this done next week.

**Comment by softvision-sergiulogigan** [comment]
Issues found:
#46710 www.facebook.com - “Upload” icon is blurred
#46711 www.facebook.com - Small allocated space for “Suggested” text in “Great New Group” window
#46713 www.facebook.com - “Public” button icon is displayed cropped and misaligned
