### ISSUE TITLE
2019Q4 - 2.2 TSCI - weekly confirmation

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#104]
https://wiki.mozilla.org/Compatibility/TSCI_Top_10

**Comment by softvision-oana-arbuzov** [comment]
Progress: https://docs.google.com/spreadsheets/d/1jpdTFvBF1_SMHbaCtWwuG6aAVCV35dTBS8l9rI4plQc/edit?ts=58df1d37&pli=1#gid=536230043

**Comment by miketaylr** [comment]
Update: still happening every week. 💯
