### ISSUE TITLE
2019Q4 - 3.1 Finish console.log display improvements

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#106]
On the frontend for webcompat.com.

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/issues/2659 is the relevant issue here, I think.

**Comment by miketaylr** [comment]
Update: @ksy36 working on saving the JSON file on the webcompat side. Hoping to be done in the next few weeks. Frontend prototype done.

**Comment by ksy36** [comment]
Update: Created a PR for this
