### ISSUE TITLE
2019Q4 - 3.2 Add postMessage support for report site issue data to bugform.js 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#107]
Need to file a bug, but the idea is to be able to support receiving data from postMessage (for Fenix), in addition to POST data.

**Comment by karlcow** [comment]
To remember that one of the possible solutions means that we do not have to do anything on the server side.

**Comment by karlcow** [comment]
We can potentially upload the data into an s3 instance.

**Comment by miketaylr** [comment]
Update: there is a reviewed PR waiting to land.
