### ISSUE TITLE
2018-Q2 2.4 Run a longitudinal user sentiment data prototype experiment (Blipz)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#11]
Some clarity on scoping to come, but roughly: we'll build a WebExtension and accompanying backend service, get a group of Mozillians to opt in for some testing for a few weeks, and writing up findings / define next steps.

cc @rosanardila

[Experiment Design](https://docs.google.com/document/d/15NvkpnhOddsbOwGYmR83M40pipyEKX3FfsD0e043_98/edit#heading=h.g118rl2i6btw)

**Comment by wisniewskit** [comment]
The prototype addon has been more or less implemented during the last OKR sprint, and is chiefly awaiting feedback on final UX/copy issues, as well as how to tie it into the backend. As such confidence for the actual addon portion of the project is practically 100% at this stage (assuming it doesn't change too drastically).

**Comment by wisniewskit** [comment]
At this stage the actual development seems to be essentially completed, as we're just waiting for [this Shield PR](https://github.com/mozilla/shield-studies-addon-utils/pull/180) so a final build of the addon can be made. Only minor tweaks and reviewing seems to remain.

**Comment by wisniewskit** [comment]
Just a quick update; we're still waiting on the PR I mentioned to pass review, but now we're not 100% sure how long it will take, so I'm waiting on go-ahead from the Shield on whether they're alright with us using an RC rather than a final version (if we choose to). Other progress this past week includes some bug fixes and finalizing of the testing mode code. All that seems to remain is a testing plan and exit survey code (blocked on the Shield studies API)

**Comment by miketaylr** [comment]
Update: Tom working on test plan, hoping to finish today (and some useful testing utils for the addon).

**Comment by miketaylr** [comment]
Update: Hoping to get PI request in by EOW, pending https://github.com/mozilla/shield-studies-addon-utils/pull/180 landing.

**Comment by wisniewskit** [comment]
Version 1 of the add-on is now basically done, and QA on it is imminent.

**Comment by denschub** [comment]
More or less done, waiting for release management and QA to figure out when it's going to ship. Some of the points moved to version 2.

**Comment by wisniewskit** [comment]
Aaaaand we're off! Or rather, QA is done, and we're going to start rolling out the add-on starting on the 2nd of July.

**Comment by miketaylr** [comment]
Yeah, let's mark this as DONE, since we're going live next week. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1459678

**Comment by miketaylr** [comment]
(changing from DONE to 80%, because we missed the target for "get a group of Mozillians to opt in for some testing for a few weeks, and writing up findings / define next steps." -- this will happen in Q3).

**Comment by miketaylr** [comment]
Score: 0.75

We were able to design the addon, work within the SHIELD process, and get it QA’d. A lot of the time we ended up blocked on SHIELD API updates, so we weren’t able to ship in Q2 or document findings. Go live date is July 2.

**Comment by miketaylr** [comment]
Final report: https://metrics.mozilla.com/protected/tdsmith/2018-08-blipz_v1_report.html
