### ISSUE TITLE
2019Q4 - 4.2 Investigate about:compat in Fenix

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#111]
At the very least, file the blocker bugs that we need for this to exist. Stretch goal: build it ourselves.

**Comment by miketaylr** [comment]
I wrote up a draft here: https://docs.google.com/document/d/1FMWRZUC5MHzXlNx9tBLdVPeW-pT1whexiJRtWZxmb6Q/edit#

Can you please review and comment @denschub and @wisniewskit? If you want edit access, let me know -- it's set to be public to anyone, and anyone can comment now.

**Comment by denschub** [comment]
I added some technical details to the document, but it looks fine!
