### ISSUE TITLE
2019Q4 - 4.3 Automated tracking of interventions dashboard

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#112]
Build a dashboard that shows the version number, amount of injections, and amount of user agent overrides for: mozilla-central (Firefox Nightly), mozilla-beta (Firefox Beta), mozilla-release (Desktop Release), and android-components.

**Comment by denschub** [comment]
Made some progress here. Fetching all the files works as I expected, working on parsing and storing the data reliably.

Note that we decided to store the amount of interventions indefinitely, so we can look at historical values and graphs.

**Comment by denschub** [comment]
No significant progress since last checkin.

**Comment by denschub** [comment]
Doing some fine-tuning on the cronjob and the visuals, then looking for something to deploy on. :)

**Comment by denschub** [comment]
This is done!

Deployment is available at https://arewehotfixingthewebyet.com/ (or https://arewehotfixingthewebyet.herokuapp.com/ if you prefer a longer URL), source code is available at https://github.com/webcompat/awhtwy.

In addition to showing the current data, we also keep daily counters forever, so we can use that dataset in the future to draw graphs. :)

I sent out a mail to the list to announce the dashboard and to gather feedback and ideas for future development efforts.
