### ISSUE TITLE
2019Q4 - 1.6 Revisit Needscontact Issues Once

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#113]
By the end of the quarter, we should re-triage/verify each of the issues in the needscontact milestone.

**Comment by softvision-oana-arbuzov** [comment]
Progress can be found here: https://docs.google.com/spreadsheets/d/1jpdTFvBF1_SMHbaCtWwuG6aAVCV35dTBS8l9rI4plQc/edit?ts=58df1d37&pli=1#gid=82670196

**Comment by miketaylr** [comment]
Update: finishing today or tomorrow. 🎈

**Comment by softvision-sergiulogigan** [comment]
We finished verifying all Needscontact issues:

Still reproducible: 235/363
We closed 35.3% issues as fixed or invalid.
