### ISSUE TITLE
2020Q1 0.1 - Get anonymous reporting working again

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#114]
We don't have a concrete plan right now, but we should have one soon. This KR covers the work necessary to re-enable anonymous reporting in a way that prevents GitHub from shutting us down again.

Ideas at https://github.com/webcompat/webcompat.com/issues/3124

**Comment by karlcow** [comment]
## 2020-01-21
We made good progress. Everything is tracked on https://github.com/webcompat/webcompat.com/projects/7

We will probably have something ready (be)for(e) Berlin

**Comment by karlcow** [comment]
# 2020-02-04

We are almost done. The last part is being reviewed. 
Once it is merged we can deploy on staging. 
Do thorough testing that we didn't break anything. 

and then we can deploy on production. 
And we will be able to restart anonymous reporting.

**Comment by karlcow** [comment]
# 2020-02-18

We are back in business. 
Anonymous reporting is working. we ironed the latest bugs/issues last week. There are things to improve and polished now. Things which are basically parts of the phase2.
