### ISSUE TITLE
2020Q1 0.2 - Create a plan for the future

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#115]
https://github.com/webcompat/webcompat.com/issues/3124 is short-term. We need to have a serious plan for the long-term. This KR covers creating a roadmap for the future of hosting, platforms, infrastructure of webcompat.com triage and reporting.

**Comment by miketaylr** [comment]
See also https://github.com/webcompat/webcompat.com/issues/3118

**Comment by miketaylr** [comment]
Update: we started this conversation last week.

**Comment by karlcow** [comment]
# 2020-02-18

Not real progress on that. But I guess that now we have #114 solved. we will have more spare time for working on this.
