### ISSUE TITLE
2020Q1 0.3 - Create and document policy for illegal and abusive content

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#116]
This should be linked somewhere from webcompat.com. 

Without exception, we must follow this plan to ensure no harmful or illegal content is hosted on our servers, or is associated with our organization on public GitHub issues.

**Comment by karlcow** [comment]
## 2020-01-21 
This is in progress @miketaylr started a document and reviews are going on. 
See https://github.com/webcompat/webcompat.com/issues/3138

**Comment by miketaylr** [comment]
Update: this is merged. A working version.

**Comment by miketaylr** [comment]
Let's call it done.
