### ISSUE TITLE
2020Q1 - 3.1 Drive down TSCI metric through bug investigation and prioritization

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#119]
Practically, this will look like a weekly pass of Top 10 TSCI needstriage/needsdiagnosis/outreach/sitewait work, ensuring no Top 10 site bug is neglected.

**Comment by softvision-oana-arbuzov** [comment]
Progress is visible here: https://docs.google.com/spreadsheets/d/1hJXAyFtYepzUI5fGYjlHaLUDD8V80wks44Vw28B5Y3E/edit#gid=549305135

**Comment by miketaylr** [comment]
Update: to be completed this week!
