### ISSUE TITLE
2020Q1 - 3.2 Needsdiagnosis, Sitewait and Needscontact re-verification

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#120]
Let's do another pass to see if these issues are still valid.

(With the webcompat-bot reports hidden for now, we'll need to start with non-anon reports)

**Comment by softvision-oana-arbuzov** [comment]
Progress will be visible here (non-anon reports): https://docs.google.com/spreadsheets/d/1hJXAyFtYepzUI5fGYjlHaLUDD8V80wks44Vw28B5Y3E/edit#gid=1710016320

**Comment by softvision-oana-arbuzov** [comment]
We finished re-checking the needsdiagnosis/sitewait/needscontact visible issues (non-anon reports), which is about 50% if the total issues in these milestones.
As soon as we'll have access to the anonymous reports we will continue the work on this OKR.

**Comment by softvision-oana-arbuzov** [comment]
We started checking anonymous reports.  
Done - Needsdiagnosis
In progress - Needscontact

**Comment by miketaylr** [comment]
Update: likely done by EOW. (needscontact already done)

**Comment by softvision-oana-arbuzov** [comment]
We've finished re-checking all the Needsdiagnosis, Sitewait and Needscontact issues.
A total of 593 issues out of 703 are still reproducible.
