### ISSUE TITLE
2020Q1 - 3.3 Monthly intervention verification

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#121]
We should verify that the interventions we're shipping are still needed, once a month. If not, we should file bugs to have them removed (which will be up to the current Intervention Release Owner to handle).

**Comment by softvision-oana-arbuzov** [comment]
We finished checking the UA Overrides/Interventions for January run and below is our progress:

**Desktop:**
- rolb.santanderbank.com
https://github.com/webcompat/web-bugs/issues/33462
- supportforms.embarcadero.com
https://github.com/webcompat/web-bugs/issues/34682
- att.tv
https://github.com/webcompat/web-bugs/issues/3846
- steamcommunity.com
https://github.com/webcompat/web-bugs/issues/34171
- sling.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1582582
- ib.absa.co.za
https://github.com/webcompat/web-bugs/issues/16401
- histography.io
https://github.com/webcompat/web-bugs/issues/1804
- bankofamerica.com
https://github.com/webcompat/web-bugs/issues/2787
https://github.com/webcompat/web-bugs/issues/9661
- election.gov.np
https://github.com/webcompat/web-bugs/issues/11622
- portalminasnet.com
https://github.com/webcompat/web-bugs/issues/18143
- sreedharscce.in
https://github.com/webcompat/web-bugs/issues/21505
- twitch.tv
https://bugzilla.mozilla.org/show_bug.cgi?id=1518781
- Download prompt for files with no content-type
https://bugzilla.mozilla.org/show_bug.cgi?id=1577870
- gaming.youtube.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1305028
- discordapp.com
https://github.com/webcompat/web-bugs/issues/7919
- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494
- console.cloud.google.com
https://github.com/webcompat/web-bugs/issues/33164
- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1560071
- apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969
- dunkindonuts.com
https://github.com/webcompat/web-bugs/issues/28742

**Mobile:**
- m.imgur.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1480710 
https://github.com/webcompat/web-bugs/issues/13154 
- tieda.baidu.com & baidu domains
https://bugzilla.mozilla.org/show_bug.cgi?id=945963 
https://github.com/webcompat/web-bugs/issues/18455
https://github.com/webcompat/web-bugs/issues/3149 
https://github.com/webcompat/web-bugs/issues/1372
https://github.com/webcompat/web-bugs/issues/2121
- lahaco.jp & nhk.or.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298 
- directv.com - [OK without UA Override]
https://bugzilla.mozilla.org/show_bug.cgi?id=1338260
https://bugzilla.mozilla.org/show_bug.cgi?id=1338128
https://github.com/webcompat/web-bugs/issues/3627 
- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206
https://bugzilla.mozilla.org/show_bug.cgi?id=1489914 
https://github.com/webcompat/web-bugs/issues/20344
https://github.com/webcompat/web-bugs/issues/3784
https://github.com/webcompat/web-bugs/issues/980
https://github.com/webcompat/web-bugs/issues/915
- mobile.de
https://bugzilla.mozilla.org/show_bug.cgi?id=969844 
https://github.com/webcompat/web-bugs/issues/37690 
https://github.com/webcompat/web-bugs/issues/38446
- cc.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1509831
https://github.com/webcompat/web-bugs/issues/329
- cineflix.com.br
https://bugzilla.mozilla.org/show_bug.cgi?id=1508516 
https://github.com/webcompat/web-bugs/issues/21553
https://github.com/webcompat/web-bugs/issues/21546
- redbull.com - [OK without UA Override]
https://bugzilla.mozilla.org/show_bug.cgi?id=1509852
https://github.com/webcompat/web-bugs/issues/21439 
https://github.com/webcompat/web-bugs/issues/18294
- zmags.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1509873
https://github.com/webcompat/web-bugs/issues/21576
https://github.com/webcompat/web-bugs/issues/40471
- posts.google.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1566253
https://github.com/webcompat/web-bugs/issues/17870
https://github.com/webcompat/web-bugs/issues/19609
https://github.com/webcompat/web-bugs/issues/19966
https://github.com/webcompat/web-bugs/issues/20709
- beeg.com - [OK without UA Override]
https://bugzilla.mozilla.org/show_bug.cgi?id=1567945
https://github.com/webcompat/web-bugs/issues/16648 
https://github.com/webcompat/web-bugs/issues/20575
https://github.com/webcompat/web-bugs/issues/41153
https://github.com/webcompat/web-bugs/issues/39572
- enuri.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1574522
https://github.com/webcompat/web-bugs/issues/37139
- ceskatelevize.cz
https://bugzilla.mozilla.org/show_bug.cgi?id=1574564
https://github.com/webcompat/web-bugs/issues/15467
https://github.com/webcompat/web-bugs/issues/39813
https://github.com/webcompat/web-bugs/issues/40174
https://github.com/webcompat/web-bugs/issues/41697
- heb.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1577240
https://github.com/webcompat/web-bugs/issues/33613
https://github.com/webcompat/web-bugs/issues/25403
https://github.com/webcompat/web-bugs/issues/19357
- homebook.pl
https://bugzilla.mozilla.org/show_bug.cgi?id=1577240
https://github.com/webcompat/web-bugs/issues/24044
- metfone.com.kh
https://bugzilla.mozilla.org/show_bug.cgi?id=1577267
https://github.com/webcompat/web-bugs/issues/16363
- help.pandora.com - [OK without Intervention]
https://bugzilla.mozilla.org/show_bug.cgi?id=1577245 
https://github.com/webcompat/web-bugs/issues/38433 
- Sites using PDK 5 videos
https://bugzilla.mozilla.org/show_bug.cgi?id=1551672
https://github.com/webcompat/web-bugs/issues/8410 
https://github.com/webcompat/web-bugs/issues/8570
https://github.com/webcompat/web-bugs/issues/6901
https://github.com/webcompat/web-bugs/issues/18368 
https://github.com/webcompat/web-bugs/issues/14308
https://github.com/webcompat/web-bugs/issues/24547 
https://github.com/webcompat/web-bugs/issues/25887
https://github.com/webcompat/web-bugs/issues/35061
- mail.google.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1561371
https://github.com/webcompat/web-bugs/issues/2983
- zertifikate.commerzbank.de
https://bugzilla.mozilla.org/show_bug.cgi?id=1568256
https://github.com/webcompat/web-bugs/issues/9102
- developer.apple.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1570328
https://github.com/webcompat/web-bugs/issues/4070
https://github.com/webcompat/web-bugs/issues/4302
https://github.com/webcompat/web-bugs/issues/5619
- patch.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1574973
https://github.com/webcompat/web-bugs/issues/25384
- holiday-weather.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1575011
https://github.com/webcompat/web-bugs/issues/18478
- binance.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1577270
https://github.com/webcompat/web-bugs/issues/17810
https://github.com/webcompat/web-bugs/issues/14748
https://github.com/webcompat/web-bugs/issues/14656
https://github.com/webcompat/web-bugs/issues/39287
- kitkat.com.au
https://bugzilla.mozilla.org/show_bug.cgi?id=1577297
https://github.com/webcompat/web-bugs/issues/28992

**Comment by ksy36** [comment]
m.imgur.com should be removed as well, as Oana mentioned in https://github.com/webcompat/web-bugs/issues/13154#issuecomment-577593697 since they removed an ability to log in on mobile

**Comment by miketaylr** [comment]
> m.imgur.com should be removed as well, as Oana mentioned in [webcompat/web-bugs#13154 (comment)](https://github.com/webcompat/web-bugs/issues/13154#issuecomment-577593697) since they removed an ability to log in on mobile

cc @denschub ^^

**Comment by softvision-sergiulogigan** [comment]
We finished checking the UA Overrides/Interventions for the February run and below is our progress:

**Desktop:**

- rolb.santanderbank.com
webcompat/web-bugs#33462
- supportforms.embarcadero.com
webcompat/web-bugs#34682
- att.tv
webcompat/web-bugs#3846
- steamcommunity.com
webcompat/web-bugs#34171
- sling.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1582582
- criticalcareontario.ca
webcompat/web-bugs#40267
- www.mobilesuica.com
webcompat/web-bugs#4608
- ib.absa.co.za
webcompat/web-bugs#16401
- histography.io
webcompat/web-bugs#1804
- bankofamerica.com - **[OK with UA Override on Mac]**
webcompat/web-bugs#2787
webcompat/web-bugs#9661
- sreedharscce.in
webcompat/web-bugs#21505
- twitch.tv - **[OK without UA Override, layout has changed, the More button is no longer displayed in the Chat window]**
https://bugzilla.mozilla.org/show_bug.cgi?id=1518781
- Download prompt for files with no content-type - **[No explicit STR available]**
https://bugzilla.mozilla.org/show_bug.cgi?id=1577870
- discordapp.com - **[OK without UA Override, even at 300% zoom]**
webcompat/web-bugs#7919
- dns.google.com
webcompat/web-bugs#22494
- console.cloud.google.com - **[@denschub, is this still reproducible on your side?]**
webcompat/web-bugs#33164
- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1560071
- apply.lloydsbank.co.uk
webcompat/web-bugs#34969
- dunkindonuts.com - **[OK without UA Override]**
webcompat/web-bugs#28742

**Mobile:**

- m.imgur.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1480710
webcompat/web-bugs#13154

- tieda.baidu.com & baidu domains
https://bugzilla.mozilla.org/show_bug.cgi?id=945963
webcompat/web-bugs#18455
webcompat/web-bugs#3149
webcompat/web-bugs#1372
webcompat/web-bugs#2121

- lahaco.jp & nhk.or.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298

- directv.com - **[OK without UA Override]**
https://bugzilla.mozilla.org/show_bug.cgi?id=1338260
https://bugzilla.mozilla.org/show_bug.cgi?id=1338128
webcompat/web-bugs#3627

- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206
https://bugzilla.mozilla.org/show_bug.cgi?id=1489914
webcompat/web-bugs#20344
webcompat/web-bugs#3784
webcompat/web-bugs#980
webcompat/web-bugs#915

- mobile.de
https://bugzilla.mozilla.org/show_bug.cgi?id=969844
webcompat/web-bugs#37690
webcompat/web-bugs#38446

- cc.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1509831
webcompat/web-bugs#329

- cineflix.com.br
https://bugzilla.mozilla.org/show_bug.cgi?id=1508516
webcompat/web-bugs#21553
webcompat/web-bugs#21546

- zmags.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1509873
webcompat/web-bugs#21576
webcompat/web-bugs#40471

- posts.google.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1566253
webcompat/web-bugs#17870
webcompat/web-bugs#19609
webcompat/web-bugs#19966
webcompat/web-bugs#20709

- beeg.com - **[OK without UA Override]**
https://bugzilla.mozilla.org/show_bug.cgi?id=1567945
webcompat/web-bugs#16648
webcompat/web-bugs#20575
webcompat/web-bugs#41153
webcompat/web-bugs#39572

- enuri.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1574522
webcompat/web-bugs#37139

- ceskatelevize.cz
https://bugzilla.mozilla.org/show_bug.cgi?id=1574564
webcompat/web-bugs#15467
webcompat/web-bugs#39813
webcompat/web-bugs#40174
webcompat/web-bugs#41697

- heb.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1577240
webcompat/web-bugs#33613
webcompat/web-bugs#25403
webcompat/web-bugs#19357

- homebook.pl
https://bugzilla.mozilla.org/show_bug.cgi?id=1577240
webcompat/web-bugs#24044

- metfone.com.kh
https://bugzilla.mozilla.org/show_bug.cgi?id=1577267
webcompat/web-bugs#16363

- Sites using PDK 5 videos
https://bugzilla.mozilla.org/show_bug.cgi?id=1551672
webcompat/web-bugs#8410  **[OK without Intervention]**
webcompat/web-bugs#8570 **[OK without Intervention]**
webcompat/web-bugs#6901 **[OK without Intervention ]**
webcompat/web-bugs#18368 **[OK without Intervention]**
webcompat/web-bugs#14308 **[OK without Intervention]**
webcompat/web-bugs#24547 **[OK without Intervention]**
webcompat/web-bugs#25887  
webcompat/web-bugs#35061 

- mail.google.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1561371
webcompat/web-bugs#2983

- zertifikate.commerzbank.de
https://bugzilla.mozilla.org/show_bug.cgi?id=1568256
webcompat/web-bugs#9102

- developer.apple.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1570328
webcompat/web-bugs#4070
webcompat/web-bugs#4302
webcompat/web-bugs#5619

- patch.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1574973
webcompat/web-bugs#25384

- holiday-weather.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1575011
webcompat/web-bugs#18478

- binance.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1577270
webcompat/web-bugs#17810
webcompat/web-bugs#14748
webcompat/web-bugs#14656
webcompat/web-bugs#39287

- kitkat.com.au
https://bugzilla.mozilla.org/show_bug.cgi?id=1577297
webcompat/web-bugs#28992

**Comment by denschub** [comment]
> console.cloud.google.com - [@denschub, is this still reproducible on your side?]
webcompat/web-bugs#33164

It still is reproducible with the intervention disabled, yeah. :(

**Comment by miketaylr** [comment]
Update: starting a new run tomorrow.

**Comment by miketaylr** [comment]
(file new bugs @ Web Compatibility::Interventions component)

**Comment by softvision-sergiulogigan** [comment]
**Mobile UA Overrides**

- rolb.santanderbank.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1563839
- supportforms.embarcadero.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1577179
- mobilesuica.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1610026
- tieda.baidu.com
https://bugzilla.mozilla.org/show_bug.cgi?id=945963
- lohaco.jp
https://github.com/webcompat/web-bugs/issues/938
- www.nhk.or.jp
https://github.com/webcompat/web-bugs/issues/31554
- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206
- mobile.de
https://bugzilla.mozilla.org/show_bug.cgi?id=969844
- cc.com
https://github.com/webcompat/web-bugs/issues/329
- cineflix.com.br
https://bugzilla.mozilla.org/show_bug.cgi?id=1508516
- zmags.com
https://github.com/webcompat/web-bugs/issues/40471
- posts.google.com
https://github.com/webcompat/web-bugs/issues/17870
- enuri.com
https://github.com/webcompat/web-bugs/issues/37139
- ceskatelevize.cz
https://github.com/webcompat/web-bugs/issues/15467
- heb.com **[OK without UA Override - [logged issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1623618)]**
https://github.com/webcompat/web-bugs/issues/33613
- homebook.pl
https://github.com/webcompat/web-bugs/issues/24044
- metfone.com.kh
https://github.com/webcompat/web-bugs/issues/16363
- galaxy.store
https://bugzilla.mozilla.org/show_bug.cgi?id=1598198
- answers.yahoo.com
https://github.com/webcompat/web-bugs/issues/5460
- uniqlo.com
https://github.com/webcompat/web-bugs/issues/38825
- nintendo.com **[OK without UA Override - [logged issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1623622)]**
https://github.com/webcompat/web-bugs/issues/12887

**Mobile Interventions**
-  medium.com
https://github.com/webcompat/web-bugs/issues/25844
-  m.tailieu.vn
https://github.com/webcompat/web-bugs/issues/39057
https://github.com/webcompat/web-bugs/issues/21917
-  Sites using PDK 5 video
https://github.com/webcompat/web-bugs/issues/25887
https://github.com/webcompat/web-bugs/issues/35061
-  mail.google.com
https://github.com/webcompat/web-bugs/issues/2983
-  dns.google.com
https://github.com/webcompat/web-bugs/issues/22494
-  zertifikate.commerzbank.de 
https://github.com/webcompat/web-bugs/issues/9102
-  developer.apple.com
https://github.com/webcompat/web-bugs/issues/4070
-  patch.com
https://github.com/webcompat/web-bugs/issues/25384
-  apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969
-  holiday-weather.com
https://github.com/webcompat/web-bugs/issues/18478
-  binance.com
https://github.com/webcompat/web-bugs/issues/17810
-  kitcat.com.au
https://github.com/webcompat/web-bugs/issues/28992
-  maps.google.com
https://github.com/webcompat/web-bugs/issues/39281
-  cracked.com
https://github.com/webcompat/web-bugs/issues/18218
-  gaana.com
https://github.com/webcompat/web-bugs/issues/29886
-  pcloud.com
https://github.com/webcompat/web-bugs/issues/40353
- directv.com.co
https://github.com/webcompat/web-bugs/issues/41822

**Comment by softvision-oana-arbuzov** [comment]
**Desktop User Agent Overrides:**
- rolb.santanderbank.com 
https://github.com/webcompat/web-bugs/issues/33462
https://github.com/webcompat/web-bugs/issues/32203
- supportforms.embarcadero.com
https://github.com/webcompat/web-bugs/issues/34682
- att.tv
https://github.com/webcompat/web-bugs/issues/3846
- steamcommunity.com
https://github.com/webcompat/web-bugs/issues/34171
- sling.com
https://github.com/webcompat/web-bugs/issues/17804
- criticalcareontario.ca
https://github.com/webcompat/web-bugs/issues/40267
- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608

**Desktop Interventions:**
- ib.absa.co.za
https://github.com/webcompat/web-bugs/issues/16401
- histography.io
https://github.com/webcompat/web-bugs/issues/20523
https://github.com/webcompat/web-bugs/issues/1804
- bankofamerica.com
https://github.com/webcompat/web-bugs/issues/2787
https://github.com/webcompat/web-bugs/issues/9661
https://github.com/webcompat/web-bugs/issues/15033
- sreedharscce.in
https://github.com/webcompat/web-bugs/issues/21505
- twitch.tv
https://bugzilla.mozilla.org/show_bug.cgi?id=1518781 - [OK without intervention - layout changed]
Created Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1623639 Remove Intervention for twitch.tv for comments
- Download prompt for files with no content-type
https://bugzilla.mozilla.org/show_bug.cgi?id=1577870 - [OK without intervention] https://bugzilla.mozilla.org/show_bug.cgi?id=1547905 
Created Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1623621 Remove Intervention for slideshare.net
- discordapp.com
https://github.com/webcompat/web-bugs/issues/7919 - [OK without intervention]  
https://github.com/webcompat/web-bugs/issues/8217 - [OK without intervention]  
https://github.com/webcompat/web-bugs/issues/8257 - [OK without intervention]   
Created Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1623632 Remove Intervention for discordapp.com regarding the scroll bar
- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494
- console.cloud.google.com
https://github.com/webcompat/web-bugs/issues/33164
- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1560071
- apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969
- dunkindonuts.com
https://github.com/webcompat/web-bugs/issues/28742 - [OK without intervention]   
Created Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1623639 Remove Intervention for dunkindonuts.com for "Sign in"/"Registration" forms

**Comment by softvision-oana-arbuzov** [comment]
All done - OKR completed.
