### ISSUE TITLE
2020Q1 - 3.4 Top site manual testing

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#122]
Let's look at sites 10 through 20 from the TSCI.

Note: any issue that would be classified as "severity-minor" should *not* be reported.

**Comment by softvision-oana-arbuzov** [comment]
We will start exploratory testing on the 10 to 20 sites:
- linkedin.com
- apple.com
- instagram.com
- live.com
- reddit.com
- qq.com
- nytimes.com
- adobe.com
- ebay.com
- bing.com

Progress will be visible here: https://docs.google.com/spreadsheets/d/1hJXAyFtYepzUI5fGYjlHaLUDD8V80wks44Vw28B5Y3E/edit#gid=948794909

**Comment by softvision-oana-arbuzov** [comment]
Current Progress:
Done - instagram.com
In Progress - linkedin.com and apple.com

**Comment by miketaylr** [comment]
Update: focusing on other OKRs the past few weeks. Some progress here.

**Comment by softvision-sergiulogigan** [comment]
Done - reddit.com, apple.com
In Progress - linkedin.com and live.com

**Comment by cipriansv** [comment]
Done - instagram.com, reddit.com, apple.com, LinkedIn.com, live.com

**Comment by miketaylr** [comment]
Update: challenged due to triage + verification (need ML bot to create some slack).

**Comment by softvision-sergiulogigan** [comment]
March 17 update:

linkedin.com - done
apple.com - done
instagram.com - done
live.com - done
reddit.com - done
qq.com - done
nytimes.com - done
adobe.com - done
ebay.com - done
bing.com - done

So... we're done.
