### ISSUE TITLE
2020Q1 - 3.5 Monthly intervention releases

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#123]
We want to have 3 releases this quarter, following the [Intervention Release Process](https://docs.google.com/document/d/1hyIv14aKDzGixuPz3rFHmVSXs-DlTFfJoleQxILwGws/edit#heading=h.kkurmbj28y1p).

**Comment by miketaylr** [comment]
https://wiki.mozilla.org/Compatibility/Interventions_Releases#Intervention_Release_Owner_Schedule

**Comment by miketaylr** [comment]
Update: @ksy36 has started this, and has about 10 candidate interventions for a release.

**Comment by ksy36** [comment]
Landed in Nightly, going to request an uplift for Beta and esr. Also working on a PR for Android components

**Comment by ksy36** [comment]
Landed in release and esr and was merged to AC

**Comment by miketaylr** [comment]
Dennis released v8.0.0 the past few days.

**Comment by miketaylr** [comment]
I'm going to take the 76 release, since @karlcow is busy taking care of ML bots.

**Comment by miketaylr** [comment]
v8.1.0 was released (only to Android Components) https://github.com/mozilla-mobile/android-components/pull/6230

**Comment by miketaylr** [comment]
Update: In progress.

**Comment by miketaylr** [comment]
Update; v9.0.0 has landed in Android components, and Mozilla Central -- working through uplift process for ESR and Beta now.

**Comment by miketaylr** [comment]
>  Beta

Beta uplift was approved for v9.0.0
