### ISSUE TITLE
2020Q2 - 1.3 Manual Testing of COVID19 related sites and services

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#126]
This issue tracks the work happening at https://docs.google.com/spreadsheets/d/1vwe2GxrS-mbAG4m15PJEfV80jEsml5hvb4scGD3RxQQ/edit#gid=0.

**Comment by softvision-sergiulogigan** [comment]
A good source of websites:

https://coronavirustechhandbook.com/infographics
https://coronavirustechhandbook.com/home

**Comment by miketaylr** [comment]
Update: on track, testing at least one site per day.

**Comment by softvision-oana-arbuzov** [comment]
Current progress: 59 websites tested mobile&desktop.

**Comment by cipriansv** [comment]
Current progress: 69 tested websites on mobile&desktop.

**Comment by miketaylr** [comment]
We decided to call this done at 70 sites.
