### ISSUE TITLE
2020Q2 - 1.4 Monthly Interventions Releases + Testing (Round 2)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#127]
Let's track this for one more quarter, before making it a regular part of Keep The Lights On work.

This issue covers 3 more releases (v10, v11, and v12), as well as manual verification of deployed interventions before each new release.

**Comment by miketaylr** [comment]
v10.0.0 tracking bug https://bugzilla.mozilla.org/show_bug.cgi?id=1625222 (ksenia will take over for karl)

**Comment by softvision-sergiulogigan** [comment]
We consider the following deadlines, for the manual testing of interventions:

- [ ] ~25th of April~
- [ ] ~22nd of May~
- [ ] ~23rd of June~

**Comment by miketaylr** [comment]
@softvision-sergiulogigan the idea is for us to land the code 1 week before soft freeze, which means April 23 for v10. So we need to adjust the deadlines to account for it. 

https://wiki.mozilla.org/Release_Management/Calendar

(We had also talked about doing the testing at the beginning of a release, rather than the end to allow for the most amount of time for patch writing).

**Comment by softvision-sergiulogigan** [comment]
We're gonna adjust the deadlines so we have the testing complete at least 1 week prior to the Soft Freeze, for the next iteration. After that, we'll start a new run the day after the Release Date.

This means:
- [x] 15th of April
- [x] 6th of May
- [ ] 3rd of June

**Comment by softvision-sergiulogigan** [comment]
1st pass: 

Desktop User Agent Overrides

- rolb.santanderbank.com
https://github.com/webcompat/web-bugs/issues/33462/
- supportforms.embarcadero.com - **fixed!**
https://github.com/webcompat/web-bugs/issues/34682
- att.tv
https://github.com/webcompat/web-bugs/issues/3846
- steamcommunity.com
https://github.com/webcompat/web-bugs/issues/34171
- sling.com
https://github.com/webcompat/web-bugs/issues/17804
- criticalcareontario.ca
https://github.com/webcompat/web-bugs/issues/40267
- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608

Desktop Interventions

- ib.absa.co.za
https://github.com/webcompat/web-bugs/issues/16401
- histography.io
https://github.com/webcompat/web-bugs/issues/1804
- bankofamerica.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1280834
- sreedharscce.in - **fixed! layout changed**
https://github.com/webcompat/web-bugs/issues/21505
- Download prompt for files with no content-type
https://bugzilla.mozilla.org/show_bug.cgi?id=1623621
- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494
- console.cloud.google.com
https://github.com/webcompat/web-bugs/issues/33164
- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1560071
- apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969

Mobile User Agent Overrides:

- answers.yahoo.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1610370
webcompat/web-bugs/issues/5460
- bracketchallenge.ncaa.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1621065
webcompat/web-bugs/issues/49886
- cc.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1509831
webcompat/web-bugs/issues/329
- ceskatelevize.cz
https://bugzilla.mozilla.org/show_bug.cgi?id=1574564
webcompat/web-bugs/issues/15467
- cineflix.com.br
https://bugzilla.mozilla.org/show_bug.cgi?id=1508516
webcompat/web-bugs/issues/21553
- enuri.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1574522
webcompat/web-bugs/issues/37139
- galaxy.store
https://bugzilla.mozilla.org/show_bug.cgi?id=1598198
- homebook.pl
https://bugzilla.mozilla.org/show_bug.cgi?id=1577250
webcompat/web-bugs/issues/24044
- lohaco.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298
- m2.bmo.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1622081
webcompat/web-bugs/issues/45019
- metfone.com.kh
https://bugzilla.mozilla.org/show_bug.cgi?id=1577267
webcompat/web-bugs/issues/16363
- mobile.de
https://bugzilla.mozilla.org/show_bug.cgi?id=969844
webcompat/web-bugs/issues/38446
- nhk.or.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298
- posts.google.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1566253
webcompat/web-bugs/issues/17870
- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206
- tieda.baidu.com
https://bugzilla.mozilla.org/show_bug.cgi?id=945963
webcompat.com/issues/18455
- uniqlo.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1595215
webcompat/web-bugs/issues/43334
webcompat/web-bugs/issues/38825
- wp1-ext.usps.gov
https://bugzilla.mozilla.org/show_bug.cgi?id=1622063
webcompat/web-bugs/issues/29867
- www.mobilesuica.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1610026
webcompat/web-bugs/issues/4608
- zmags.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1509873
webcompat/web-bugs/issues/21576
webcompat/web-bugs/issues/40471
- Img.weblogssl.com  - **fixed**
https://bugzilla.mozilla.org/show_bug.cgi?id=1622059
webcompat/web-bugs/issues/49166
webcompat/web-bugs/issues/48787
webcompat/web-bugs/issues/48650

Mobile Interventions:

- apply.lloydsbank.co.uk
webcompat/web-bugs/issues/34969
- binance.com
webcompat/web-bugs/issues/17810
- stemwijzer.nl
webcompat/web-bugs/issues/15955
- developer.apple.com
webcompat/web-bugs/issues/4070
- directv.com.co
webcompat/web-bugs/issues/41822
- dns.google.com
webcompat/web-bugs/issues/22494
- gaana.com
webcompat/web-bugs/issues/29886
- holiday-weather.com **fixed** (https://bugzilla.mozilla.org/show_bug.cgi?id=1630197 Remove Intervention for holiday-weather.com)
webcompat/web-bugs/issues/18478
- kitkat.com.au
webcompat/web-bugs/issues/28992
- mail.google.com
webcompat/web-bugs/issues/2983
- maps.google.com
webcompat/web-bugs/issues/39281
- medium.com
webcompat/web-bugs/issues/25844
- m.tailieu.vn
webcompat/web-bugs/issues/39057
webcompat/web-bugs/issues/21917
- patch.com - OK without intervention
webcompat/web-bugs/issues/25384 **fixed** (https://bugzilla.mozilla.org/show_bug.cgi?id=1630204 Remove Intervention for patch.com)
- pcloud.com
webcompat/web-bugs/issues/40353
- salesforce communities
webcompat/web-bugs/issues/48882
webcompat/web-bugs/issues/48754
- sites using PDK 5 video
webcompat/web-bugs/issues/25887
webcompat/web-bugs/issues/35061
- cracked.com
webcompat/web-bugs/issues/18218
- zertifikate.commerzbank.de **fixed** (https://bugzilla.mozilla.org/show_bug.cgi?id=1630259 Remove Intervention for zertifikate.commerzbank.de)
webcompat/web-bugs/issues/9102

**Comment by softvision-oana-arbuzov** [comment]
Next run scheduled for 4-6 May.

**Comment by ksy36** [comment]
On track, 10.0.0 has shipped to beta, 10.1.0 has shipped to esr and merged to ac

**Comment by cipriansv** [comment]
2nd pass:

**Desktop Interventions:**

- ib.absa.co.za 
https://github.com/webcompat/web-bugs/issues/16401

- histography.io
https://github.com/webcompat/web-bugs/issues/1804

- bankofamerica.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1280834

- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494

- console.cloud.google.com
https://github.com/webcompat/web-bugs/issues/33164

- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1560071

- apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969

- directv.com.co
https://github.com/webcompat/web-bugs/issues/41822

- sixt-neuwagen.de
https://github.com/webcompat/web-bugs/issues/50717

- websube.ckbogazici.com.tr
https://github.com/webcompat/web-bugs/issues/51714

- everyman.co
https://github.com/webcompat/web-bugs/issues/50968


**Mobile Interventions:**

- apply.lloydsbank.co.uk 
https://github.com/webcompat/web-bugs/issues/34969

- www.directv.com.co
https://github.com/webcompat/web-bugs/issues/41822

- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494

- everyman.co
https://github.com/webcompat/web-bugs/issues/50968

- www.sixt-neuwagen.de
https://github.com/webcompat/web-bugs/issues/50717

- websube.ckbogazici.com.tr 
https://github.com/webcompat/web-bugs/issues/51714

- www.binance.com 
https://github.com/webcompat/web-bugs/issues/17810

- smallingerland.stemwijzer.nl
https://github.com/webcompat/web-bugs/issues/15955

- developer.apple.com 
https://github.com/webcompat/web-bugs/issues/4070

- gaana.com 
https://github.com/webcompat/web-bugs/issues/29886

- www.kitkat.com.au 
https://github.com/webcompat/web-bugs/issues/28992

- mail.google.com
https://github.com/webcompat/web-bugs/issues/2983

- medium.com
https://github.com/webcompat/web-bugs/issues/25844

- m.tailieu.vn 
https://github.com/webcompat/web-bugs/issues/39057

- www.pcloud.com 
https://github.com/webcompat/web-bugs/issues/40353

- salesforce community
https://github.com/webcompat/web-bugs/issues/48882
https://github.com/webcompat/web-bugs/issues/48754

- sites using PDK 5 video
https://github.com/webcompat/web-bugs/issues/25887
https://github.com/webcompat/web-bugs/issues/35061

- www.cracked.com 
https://github.com/webcompat/web-bugs/issues/18218

- www.zertifikate.commerzbank.de - **fixed! layout changed**
https://github.com/webcompat/web-bugs/issues/9102


**Desktop User Agent Overrides:**

- rolb.santanderbank.com - **Fixed**
https://github.com/webcompat/web-bugs/issues/37475
https://github.com/webcompat/web-bugs/issues/33462 
Created Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1635357 Remove UA Override for rolb.santanderbank.com for all platforms

- att.tv
https://github.com/webcompat/web-bugs/issues/3846 

- steamcommunity.com
https://github.com/webcompat/web-bugs/issues/34171 

- sling.com
https://github.com/webcompat/web-bugs/issues/17804 

- criticalcareontario.ca
https://github.com/webcompat/web-bugs/issues/40267 

- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608

- app.pixton.com
https://github.com/webcompat/web-bugs/issues/43438 

**Mobile User Agent Overrides:**

- app.pixton.com
https://github.com/webcompat/web-bugs/issues/43438 

- rolb.santanderbank.com - Fixed
https://github.com/webcompat/web-bugs/issues/37475
https://github.com/webcompat/web-bugs/issues/33462 
Created Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1635357 Remove UA Override for rolb.santanderbank.com for all platforms

- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608

- answers.yahoo.com
https://github.com/webcompat/web-bugs/issues/5460 

- autotrader.ca
https://github.com/webcompat/web-bugs/issues/50961

- bracketchallenge.ncaa.com
https://github.com/webcompat/web-bugs/issues/49886 

- cc.com
https://github.com/webcompat/web-bugs/issues/329 

- ceskatelevize.cz
https://github.com/webcompat/web-bugs/issues/15467 

- cineflix.com.br
https://github.com/webcompat/web-bugs/issues/21553 

- dominos.ch
https://github.com/webcompat/web-bugs/issues/48273 

- enuri.com
https://github.com/webcompat/web-bugs/issues/37139 

- galaxy.store
https://bugzilla.mozilla.org/show_bug.cgi?id=1598198 

- homebook.pl
https://github.com/webcompat/web-bugs/issues/24044 

- lohaco.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298

- m2.bmo.com
https://github.com/webcompat/web-bugs/issues/45019 

- metfone.com.kh
https://github.com/webcompat/web-bugs/issues/16363 

- mobile.de
https://github.com/webcompat/web-bugs/issues/38446 

- nhk.or.jp (?)
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298

- posts.google.com
https://github.com/webcompat/web-bugs/issues/17870 

- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206

- tieda.baidu.com
https://github.com/webcompat/web-bugs/issues/18455 
https://github.com/webcompat/web-bugs/issues/3149 

- uniqlo.com
https://github.com/webcompat/web-bugs/issues/43334  
https://github.com/webcompat/web-bugs/issues/38825

- wp1-ext.usps.gov
https://github.com/webcompat/web-bugs/issues/29867 

- zmags.com
https://github.com/webcompat/web-bugs/issues/21576  
https://github.com/webcompat/web-bugs/issues/40471

**Comment by miketaylr** [comment]
I'll take the next rotation (v11): https://bugzilla.mozilla.org/show_bug.cgi?id=1631858

@denschub do you mind taking v12? https://bugzilla.mozilla.org/show_bug.cgi?id=1637672 (no bugs there yet!)

**Comment by cipriansv** [comment]
We scheduled the next re-check run for the 28th of May.

**Comment by miketaylr** [comment]
Update: v11 shipped.

**Comment by denschub** [comment]
> @denschub do you mind taking v12? https://bugzilla.mozilla.org/show_bug.cgi?id=1637672 (no bugs there yet!)

I don't!

**Comment by miketaylr** [comment]
v12 tracking bug https://bugzilla.mozilla.org/show_bug.cgi?id=1637672

**Comment by cipriansv** [comment]
3rd pass:

**Desktop User-Agent Overrides**:

- att.tv
webcompat/web-bugs#3846

- steamcommunity.com
webcompat/web-bugs#34171

- sling.com
webcompat/web-bugs#17804

- criticalcareontario.ca
webcompat/web-bugs#40267

- www.mobilesuica.com
webcompat/web-bugs#4608

- app.pixton.com
webcompat/web-bugs#43438

**Mobile User-Agent Overrides**:

- app.pixton.com
https://github.com/webcompat/web-bugs/issues/43438

- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608

- answers.yahoo.com
https://github.com/webcompat/web-bugs/issues/5460

- autotrader.ca
https://github.com/webcompat/web-bugs/issues/50961

- bracketchallenge.ncaa.com
https://github.com/webcompat/web-bugs/issues/49886

- cc.com
https://github.com/webcompat/web-bugs/issues/329

- ceskatelevize.cz
https://github.com/webcompat/web-bugs/issues/15467

- cineflix.com.br
https://github.com/webcompat/web-bugs/issues/21553

- dominos.ch
https://github.com/webcompat/web-bugs/issues/48273

- enuri.com
https://github.com/webcompat/web-bugs/issues/37139

- galaxy.store
https://bugzilla.mozilla.org/show_bug.cgi?id=1598198

- homebook.pl
https://github.com/webcompat/web-bugs/issues/24044

- lohaco.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298

- m2.bmo.com
https://github.com/webcompat/web-bugs/issues/45019

- metfone.com.kh
https://github.com/webcompat/web-bugs/issues/16363

- mobile.de
https://github.com/webcompat/web-bugs/issues/38446

- nhk.or.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298

- posts.google.com
https://github.com/webcompat/web-bugs/issues/17870

- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206

- tieda.baidu.com
https://github.com/webcompat/web-bugs/issues/18455
https://github.com/webcompat/web-bugs/issues/3149

- uniqlo.com
https://github.com/webcompat/web-bugs/issues/43334
https://github.com/webcompat/web-bugs/issues/38825

- wp1-ext.usps.gov
https://github.com/webcompat/web-bugs/issues/29867

- zmags.com
https://github.com/webcompat/web-bugs/issues/21576
https://github.com/webcompat/web-bugs/issues/40471

**Desktop Interventions:**

- apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969

- directv.com.co
https://github.com/webcompat/web-bugs/issues/41822

- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494

- everyman.co
https://github.com/webcompat/web-bugs/issues/50968

- sixt-neuwagen.de
https://github.com/webcompat/web-bugs/issues/50717

- websube.ckbogazici.com.tr
https://github.com/webcompat/web-bugs/issues/51714

- ib.absa.co.za
https://github.com/webcompat/web-bugs/issues/16401 

- histography.io
https://github.com/webcompat/web-bugs/issues/1804

- bankofamerica.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1280834 
https://github.com/webcompat/web-bugs/issues/2787

- Download prompt for files with no content-type - still present in `about:compat` list
https://bugzilla.mozilla.org/show_bug.cgi?id=1577870 https://bugzilla.mozilla.org/show_bug.cgi?id=1623621

- console.cloud.google.com
https://github.com/webcompat/web-bugs/issues/33164

- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1570119

**Mobile Interventions:**

- apply.lloydsbank.co.uk
https://github.com/webcompat/web-bugs/issues/34969

- directv.com.co
https://github.com/webcompat/web-bugs/issues/41822

- dns.google.com
https://github.com/webcompat/web-bugs/issues/22494

- everyman.co
https://github.com/webcompat/web-bugs/issues/50968

- sixt-neuwagen.de
https://github.com/webcompat/web-bugs/issues/50717

- websube.ckbogazici.com.tr
https://github.com/webcompat/web-bugs/issues/51714

- binance.com
https://github.com/webcompat/web-bugs/issues/17810 
Created Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1641492 Remove Intervention for binance.com

- stemwijzer.nl
https://github.com/webcompat/web-bugs/issues/15955 

- developer.apple.com
https://github.com/webcompat/web-bugs/issues/4070 

- gaana.com
https://github.com/webcompat/web-bugs/issues/29886 

- kitkat.com.au
https://github.com/webcompat/web-bugs/issues/28992 

- mail.google.com
https://github.com/webcompat/web-bugs/issues/2983 

- maps.google.com
https://github.com/webcompat/web-bugs/issues/39281 

- medium.com
https://github.com/webcompat/web-bugs/issues/25844 

- m.tailieu.vn
https://github.com/webcompat/web-bugs/issues/39057 
https://github.com/webcompat/web-bugs/issues/21917 

- pcloud.com
https://github.com/webcompat/web-bugs/issues/40353 

- salesforce communities
https://github.com/webcompat/web-bugs/issues/48882 
https://github.com/webcompat/web-bugs/issues/48754 

- sites using PDK 5 video
https://github.com/webcompat/web-bugs/issues/25887 
https://github.com/webcompat/web-bugs/issues/35061 

- cracked.com
https://github.com/webcompat/web-bugs/issues/18218

- laposte.fr
https://github.com/webcompat/web-bugs/issues/52274 
Created Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1641537 Remove Intervention for laposte.fr

**Comment by cipriansv** [comment]
4th pass:

**Desktop Interventions:**

- ib.absa.co.za
webcompat/web-bugs#16401
- histography.io
webcompat/web-bugs#1804
- bankofamerica.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1280834
webcompat/web-bugs#2787
- Download prompt for files with no content-type - FIXED, but still present in the about:compat list
https://bugzilla.mozilla.org/show_bug.cgi?id=1577870 
https://bugzilla.mozilla.org/show_bug.cgi?id=1623621
- dns.google.com
webcompat/web-bugs#22494
- console.cloud.google.com
webcompat/web-bugs#33164
- teamcoco.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1570119
- apply.lloydsbank.co.uk
webcompat/web-bugs#34969
- directv.com.co
webcompat/web-bugs#41822
- sixt-neuwagen.de
webcompat/web-bugs#50717
- websube.ckbogazici.com.tr
webcompat/web-bugs#51714
- everyman.co
webcompat/web-bugs#50968

**Mobile interventions:**

- apply.lloydsbank.co.uk
webcompat/web-bugs#34969
- directv.com.co
webcompat/web-bugs#41822
- dns.google.com
webcompat/web-bugs#22494
- everyman.co
webcompat/web-bugs#50968
- sixt-neuwagen.de
webcompat/web-bugs#50717
- websube.ckbogazici.com.tr
webcompat/web-bugs#51714
- binance.com - FIXED, but still present in the about:compat list
webcompat/web-bugs#17810
- stemwijzer.nl
webcompat/web-bugs#15955
- developer.apple.com
webcompat/web-bugs#4070
- gaana.com
webcompat/web-bugs#29886
- kitkat.com.au
webcompat/web-bugs#28992
- mail.google.com
webcompat/web-bugs#2983
- maps.google.com
webcompat/web-bugs#39281
- medium.com
webcompat/web-bugs#25844
- m.tailieu.vn
webcompat/web-bugs#39057
webcompat/web-bugs#21917
- pcloud.com
webcompat/web-bugs#40353
- salesforce communities
webcompat/web-bugs#48882
webcompat/web-bugs#48754
- sites using PDK 5 video
webcompat/web-bugs#25887
webcompat/web-bugs#35061
- cracked.com
webcompat/web-bugs#18218
- laposte.fr - FIXED, but still present in the about:compat list
webcompat/web-bugs#52274

**Desktop User Agent Overrides:**

- att.tv
https://github.com/webcompat/web-bugs/issues/3846 
- steamcommunity.com
https://github.com/webcompat/web-bugs/issues/34171 
- sling.com (Geo-location restriction)
https://github.com/webcompat/web-bugs/issues/17804 
- criticalcareontario.ca
https://github.com/webcompat/web-bugs/issues/40267 
- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608
- app.pixton.com
https://github.com/webcompat/web-bugs/issues/43438 

**Mobile User Agent Overrides:**

- app.pixton.com
https://github.com/webcompat/web-bugs/issues/43438 
- www.mobilesuica.com
https://github.com/webcompat/web-bugs/issues/4608
- answers.yahoo.com
https://github.com/webcompat/web-bugs/issues/5460 
Created Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1647193 Remove UA Override for answers.yahoo.com
- autotrader.ca
https://github.com/webcompat/web-bugs/issues/50961
- bracketchallenge.ncaa.com (Geo-location restriction)
https://github.com/webcompat/web-bugs/issues/49886 
- cc.com
https://github.com/webcompat/web-bugs/issues/329 
- ceskatelevize.cz
https://github.com/webcompat/web-bugs/issues/15467 
- cineflix.com.br
https://github.com/webcompat/web-bugs/issues/21553 
- dominos.ch
https://github.com/webcompat/web-bugs/issues/48273 
- enuri.com
https://github.com/webcompat/web-bugs/issues/37139 
- galaxy.store
https://bugzilla.mozilla.org/show_bug.cgi?id=1598198 
- homebook.pl
https://github.com/webcompat/web-bugs/issues/24044 
- lohaco.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298
- m2.bmo.com
https://github.com/webcompat/web-bugs/issues/45019 
- metfone.com.kh
https://github.com/webcompat/web-bugs/issues/16363 
- mobile.de
https://github.com/webcompat/web-bugs/issues/38446 
- nhk.or.jp (?)
https://bugzilla.mozilla.org/show_bug.cgi?id=1177298
- posts.google.com
https://github.com/webcompat/web-bugs/issues/17870 
- rakuten.co.jp
https://bugzilla.mozilla.org/show_bug.cgi?id=1385206
- tieda.baidu.com
https://github.com/webcompat/web-bugs/issues/18455 
https://github.com/webcompat/web-bugs/issues/3149 
- uniqlo.com
https://github.com/webcompat/web-bugs/issues/43334  
https://github.com/webcompat/web-bugs/issues/38825
- wp1-ext.usps.gov
https://github.com/webcompat/web-bugs/issues/29867 
- zmags.com
https://github.com/webcompat/web-bugs/issues/21576  
https://github.com/webcompat/web-bugs/issues/40471

**Comment by denschub** [comment]
Things got a bit delayed because of All Hands, but most interventions are landed on GitHub. [One is still pending review](https://github.com/mozilla/webcompat-addon/pull/141), and when that's done, I'll build a patch for central. Unless something explodes, this should land before the freeze.

**Comment by denschub** [comment]
v12 hit central this morning, and it didn't bounce in 1.5 hours, so I'm optimistic and mark this as done.
