### ISSUE TITLE
2020Q2 - 1.5 UA string investigation for Firefox for iOS

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#128]
We've had a number of reports in the past few months about Firefox for iOS UA string issues.

This KR tracks the work to investigate possible changes, and their implications for detection and possible breakage. The expected output is a report detailing any recommended changes.

**Comment by denschub** [comment]
I've made some progress here and have collected a total of 29 examples so far (thanks for the pings on related issues, btw!)

So far, all breakage looks similar, the resolution would be "make it look more like Safari". In my tests, we could preserve a unique identifier for Firefox on iOS, as long as it looks close enough to Safari. I built a little tool to test UA changes on most of the broken sites I know, so that running tests on when the UA detection breaks are easier.

**Comment by denschub** [comment]
Started writing out a report with my findings so far and collected two possible fixes to the iOS UA that would resolve those issues. Testing confirmed these work on all sites that I could automate, currently doing some manual tests as well.

**Comment by denschub** [comment]
No really significant change since last checkin.

**Comment by denschub** [comment]
In the process of finishing up my report, both as an internal Google Doc, and a slightly altered form as an article to be published on my blog. Work on this got delayed a bit by other stuff like diagnosis, but this will be done by the end of the week.

Unfortunately, my original idea of altering the UA to be closer to Safaris no longer holds. While it fixes some of the cases that we know about, I discovered during manual testing that this would break a lot of top 100 sites. There is one slight change we can make that fixes "is mobile?" detection on some libs, though.

I also built a tool to automatically check user agent detection across a range of C#, Go, JavaScript, PHP, Python, and Ruby libraries. This allows us to build a matrix similar to Mike's https://miketaylr.github.io/arewedetectableyet/, but built automatically and not only checking for mobile state, but also checking if the library correctly detected the browser vendor and version, as a lot of sites actually depend on that (💩). I'm not 100% confident that's releaseable on GitHub by the end of the week, as I have to fix some security issues first, but that'll be a nice addition.

I'll link both the blog post and the Google Doc here as soon as that's done!

**Comment by denschub** [comment]
Here is Version 1 of the report, as promised: https://docs.google.com/document/d/1DEwAhckLk9IdB_-aFYyHm6eJbplxWQA5WVLxtqAydUo/edit?usp=sharing

If you don't want to work through all 8 pages, here's the conclusion:

> Overall, it's easy to say that the initial feeling about receiving too many reports about breakage in Firefox for iOS were wrong. In fact, we receive a surprisingly small amount of reports compared to other products, so Firefox for iOS appears to be working very well. However, almost all reports about Firefox for iOS we receive are due to User Agent sniffing. In retrospect, this is not too surprising, as sites who detect Firefox for iOS correctly (or not at all) just deliver the default Safari for iOS experience, which generally works without issues.
>
> For UA sniffing related issues, there was an interesting shift of the type of issues over the years. Before mid-2019, most of the reports were caused by sites not recognizing Firefox for iOS at all, resulting in completely blocked out websites. More recently, we see less of those issues, and instead, most of the banners we see today claim the browser version is outdated.
> 
> Most cases where we were able to look at the sniffer implementation did correctly identify Firefox for iOS as a mobile Firefox browser, and the libraries usually also correctly detected the version. However, because our Firefox for Android and Firefox Desktop version numbers usually were in sync, application developers hard-coded the version limits to be something reasonably high. Firefox for iOS, however, is not following the regular release number, and instead is still at a low 26, which is below the limits for most sites.
> 
> Another common modern breakage we can observe is that sites look for identifiers indicating an iOS device, like Mobile+Safari, and if that's found, they look for a Version or CriOS identifier to detect the version used. This fails for Firefox for iOS, and the result is the library returning an outdated Safari version.
>
> However, with all that being said, the total number of reports and broken websites is really low. This is good news, and it's indicating that the UA string chosen works well in most environments.
> 
> **Possible UA string changes**
> 
> It's difficult to identify possible changes to the UA string to improve the detection, especially since it's generally working well already.
> 
> It might be a good idea to add a Version identifier to catch the cases where we correctly get identified as an iOS browser, and a library is looking for the browser version. Since Firefox for iOS' version number is ahead of Safari's, it should be safe to use the Firefox for iOS version here, Version/13.1.1, for example. I did some manual testing on top sites to check if there is obvious breakage, and did not find anything. However, more careful testing needs to be done here.
> 
> For sites that show an outdated version banner, or a general "unsupported" banner, changing the Firefox for iOS identifier to something with a higher version number, like FxiOS/77.0, is a good shot. If the site is correctly identifying Firefox, but is checking the version number against a Firefox for Android-based allowlist, this might resolve the issue without losing a Firefox identifier.

You'll notice that the section containing details about automated sniffing library testing is missing at the moment. That's correct, and that's because I'm reworking major parts in preparation to a lightning talk next week, and I didn't quite get done with that until today.

However, that's OKR DLC content anyway, and since the report is done, I'll consider this as done. I will update this issue and the Google Doc as soon as I am done with the refactorings, so nobody will miss it. :)

**Comment by denschub** [comment]
The code for automatic User Agent sniffing libraries testing is at https://github.com/denschub/agent-hypersniff - I'll do a short introduction later today for the team, and eventually write a blog post about that (once I have a proper human readable output, not just a JSON file)
