### ISSUE TITLE
2020Q3 - Reserve: webcompat-ml bot improvements

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#130]
* Get access to the entire stack (handover from OI)
* Modify the bot to only work on certain milestones (needstriage)
* Finish integration into moderation workflow

**Comment by miketaylr** [comment]
Let's schedule this one for Q3!

**Comment by ksy36** [comment]
This was done in https://github.com/mozilla/webcompat-team-okrs/issues/194
