### ISSUE TITLE
2020Q2 - 2.2 New form rewrite

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#131]
* Modularize form v2 code (using ES modules)
* Add unit tests for modules
* Add a transpile step for older browsers
* Integrate transpiled bundles into build + deploy workflow

https://github.com/webcompat/webcompat.com/projects/9

**Comment by miketaylr** [comment]
Update: Working on final submit step on the form. Need to work on build + babel next.

**Comment by miketaylr** [comment]
Update: no updates this time, still on track.

**Comment by ksy36** [comment]
Update: tested submitting a form and fixed a couple bugs, added some ui improvements for the progress bar. Found out that there is still some code for the GET params parsing needs to be moved, so finishing that up. Will be looking into transpiling the code for older browser with babel and including that to the grunt tasks next

**Comment by ksy36** [comment]
Update: added webpack bundling, refactored most of the code to not use global variables. Haven't moved backbone mousetrap yet (clicking g to go to github), so currently looking into that. Next I will need to move css to be part of webpack infrastructure. Still on track

**Comment by ksy36** [comment]
Moved css to webpack bundle, added separate bundle for modern browsers and modified deploy script to run webpack instead of grunt. Needs some additional testing before merging :)

**Comment by miketaylr** [comment]
Update: done!
