### ISSUE TITLE
2020Q2 - 3.1 WebExtension API development in GeckoView

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#133]
The bugs will be added here in the near future, Tom will be working on this 50% of his time this quarter.

**Comment by wisniewskit** [comment]
Not started yet, as I'm still waiting on the relevant teams to decide on priorities for the various APIs. I'll probably begin working on the most likely-to-be-chosen candidates regardless, to prevent falling too far behind.
