### ISSUE TITLE
2020Q2 - 3.2 Enhanced Tracking Protection diagnosis + interventions experiments

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#134]
In order to support the SecEng team, we'll diagnose the most important issues and recommend fixes.

@wisniewskit, can you add a link to the meta bugs you're focusing on?

**Comment by wisniewskit** [comment]
Sure, it's this meta-bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1101005

**Comment by wisniewskit** [comment]
I'm roughly 3/4 of the way through diagnosing all of the bugs, and have at least triaged and pre-screened almost all of them. At this point I feel confident that the bulk of the issues can be resolved with a combination of shim/surrogates scripts (similar to how the webcompat addon does things), and proxying or sandboxing yellow-listed resources.

**Comment by wisniewskit** [comment]
Phase one is done now, and we're just figuring out what to do for phase two. As per my previous comment, the summary of my findings is that we ought to be able to detect the loading of tricky resources and shim them with minimal versions to keep pages working, and/or ask the user to allow them (with placeholders and other UI) where necessary.

**Comment by wisniewskit** [comment]
Work has begun on experimenting with mitigating strict mode site breakage using the WebCompat system addon to "shim" certain blocked scripts. Primary focus is on getting login-with-Facebook functionality working. I have a patch again m-c which implements over a dozen shims into the WebCompat addon including an Facebook SDK one. I'm awaiting initial feedback while I work on Twitter and Instagram SDK shims.

**Comment by wisniewskit** [comment]
After some testing, it was found that I needed better Gecko support to make the addon reasonably solid. That work should be landing in [bug 1639718](https://bugzilla.mozilla.org/show_bug.cgi?id=1639718).

Once that lands, I should be ready to post my patches against the webcompat addon for review. My only real concern at this point is that the popup-blocker gets in the way of third-party Facebook popups with the addon, and my work-around is not ideal. We may need a further patch in Gecko to address this, if the work-around isn't deemed good enough for the MVP.

I will be working on adding tests to the patch in the meantime, if not more shims.

**Comment by wisniewskit** [comment]
The [blocking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1639718) has just landed in time for Firefox 78, and I have the patch for changes to the webcompat addon ready for testing (on desktop).

I will upload the webcompat addon patch ASAP to [bug 1637329](https://bugzilla.mozilla.org/show_bug.cgi?id=1637329) for further testing, once Dennis and I have decided on whether the mochitests ought to be stored on GitHub, or only on m-c.

There is still also a potential issue with the popup blocker, but it is unlikely to keep us from landing the patch, so I'll be focused on the Fenix port while testing begins and we decide which shims we want to ship with aside from the Facebook login feature.

**Comment by wisniewskit** [comment]
I've since figured out the remaining issues with the popup blocker, Fenix support, and basic mochitest coverage, so the bulk of the remaining work here is with addressing the review comments (which are substantial, as existing addon APIs aren't particularly well suited to shimming, but we've decided to use them as much as possible to avoid other complications they still work around). It's my hope to get the patch landed well before the month is up, but it's unclear if the All Hands will complicate that. I don't feel we're at risk here, though.

**Comment by wisniewskit** [comment]
There has been a ton of review-churn, but I'm still hopeful to get the last mochitests and nits addressed as early as I can this week to land before the code-freeze. Unfortunately it seems as though unexpected bugs will likely make us miss the window for Fenix in 79, though. Worst-case we'll miss 79 entirely, but I should have the patches landing by month's end.

**Comment by miketaylr** [comment]
Let's go ahead and close this in favor of #148.
