### ISSUE TITLE
2020Q2 - 3.3 Add support for Print reftests to WPT

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#135]
To support the Layout team.

**Comment by miketaylr** [comment]
Update: Making progress, we have a demo implementation that's working (had some issues with glyphs, but we've found a workaround).

**Comment by miketaylr** [comment]
Update: Working around the work around, and hoping to get support from PDFjs folks (or fixing the bug ourselves).

**Comment by jgraham** [comment]
Update: Print Reftest RFC merged. Implementation in Gecko fixed. Need to clean up the patches and get review.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/rfcs/pull/41 is the merged RFC

**Comment by jgraham** [comment]
Generic implementation (for Chrome and Firefox) [under review](https://github.com/web-platform-tests/wpt/pull/21901). Once that's landed I'll get the Gecko-specific implemenation inside marionette up fro review on Phabricator.

**Comment by jgraham** [comment]
Landed the code upstream and now on the third attempt at getting the sync containing the print reftest to stick (for reasons unrelated to print reftests). Currently rebasing marionette patches for review on top of that.

**Comment by miketaylr** [comment]
Update: on autoland, looking like it will merge to central today.
