### ISSUE TITLE
2020Q2 - 3.4 WebDriver Bi-Directional protocol spec work

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#136]
To support the DevTools and Performance testing teams.

(Feel free to add better links and a description, once we have them).

**Comment by jgraham** [comment]
This is now in progress. I filed some intitial spec issues: https://github.com/w3c/webdriver/labels/BiDi

**Comment by jgraham** [comment]
Added an initial proposal for the low-level serialization, but no feedback yet. Got a first WG meeting coming up, so hoping to see some interest in the open issues before that.

**Comment by jgraham** [comment]
First WG meetng tomorrow. Created an empty document for the core spec and sorting out the admin issues and CI setup. Some more activity on the open issues; there seems to be enough agreement to write down the transport layer of the protocol in a spec document, and probably some basic datatype stuff.

**Comment by jgraham** [comment]
Spec is in-progress https://w3c.github.io/webdriver-bidi/
