### ISSUE TITLE
2020Q3 - 2.1 End every week with 0 untriaged and unmoderated bugs

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#137]
As measured by the webcompat-metrics server: http://webcompat-dashboard.herokuapp.com/needstriage and https://github.com/webcompat/web-bugs-private/issues (since we don't have a moderation endpoint for the metrics server yet).

The goal here is to track that we're able to keep up with bug load with current resources, and if not, use that as a justification to request more resources.

Note: Comments about progress will be reported every **Friday at 5PM** (Romania time).

**Comment by softvision-oana-arbuzov** [comment]
Progress - 10.07.2020: 0 [untriaged](https://github.com/webcompat/web-bugs/issues?page=1&q=is%3Aissue+milestone%3Aneedstriage+is%3Aopen) / 0 [unmoderated](https://github.com/webcompat/web-bugs-private/issues?q=is%3Aissue+is%3Aopen+) / 10 backlog issues (needsinfo)

**Comment by softvision-oana-arbuzov** [comment]
Progress - 17.07.2020: 0 [untriaged](https://github.com/webcompat/web-bugs/issues?page=1&q=is%3Aissue+milestone%3Aneedstriage+is%3Aopen) / 0 [unmoderated](https://github.com/webcompat/web-bugs-private/issues?q=is%3Aissue+is%3Aopen+) / 12 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 24.07.2020: 0 [untriaged](https://github.com/webcompat/web-bugs/issues?page=1&q=is%3Aissue+milestone%3Aneedstriage+is%3Aopen)/ 0 [unmoderated](https://github.com/webcompat/web-bugs-private/issues?q=is%3Aissue+is%3Aopen+) / 23 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 31.07.2020: 0 untriaged / 0 unmoderated / 5 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 07.08.2020: 0 untriaged / 0 unmoderated / 7 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 14.08.2020: 0 untriaged / 0 unmoderated / 42 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 21.08.2020: 0 untriaged / 0 unmoderated / 5 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 28.08.2020: 0 untriaged / 0 unmoderated / 5 backlog issues (needsinfo)

**Comment by softvision-oana-arbuzov** [comment]
Progress - 04.09.2020: 0 untriaged / 0 unmoderated / 3 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 11.09.2020: 0 untriaged / 0 unmoderated / 33 backlog issues (needsinfo)

**Comment by cipriansv** [comment]
Progress - 18.09.2020: 0 untriaged / 0 unmoderated / 4 backlog issues (needsinfo)

**Comment by softvision-oana-arbuzov** [comment]
Progress - 25.09.2020: 0 [untriaged](https://github.com/webcompat/web-bugs/issues?page=1&q=is%3Aissue+milestone%3Aneedstriage+is%3Aopen)/ 0 [unmoderated](https://github.com/webcompat/web-bugs-private/issues?q=is%3Aissue+is%3Aopen+) / 6 backlog issues (needsinfo)
