### ISSUE TITLE
2020Q3 - 2.2 Manual testing of 5 open source editor libraries

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#138]
Libraries to be identified, but the idea is to test (on a hosted demo page, or one we create) and triage known issues identified for Firefox. 

Proposed Libraries:
1. https://github.com/microsoft/monaco-editor
2. https://draftjs.org/
3. https://quilljs.com/
4. https://trix-editor.org/
5. https://github.com/tinymce/tinymce

**Comment by magsout** [comment]
I could create a page to deploy these libraries.

**Comment by karlcow** [comment]
Maybe slightly related I wonder if an aggregator of github issues monitoring firefox keywords for known libraries, would help to raise flags. Just a thought.

**Comment by karlcow** [comment]
ahah. https://github.com/search?l=JavaScript&o=desc&q=firefox&s=created&type=Issues

**Comment by miketaylr** [comment]
> I could create a page to deploy these libraries.

@magsout that would be super helpful. Can you help out with this?

**Comment by magsout** [comment]
@miketaylr I opened this new repository https://github.com/webcompat/webcompat-editor-testing

Hosted page is available here https://webcompat.github.io/webcompat-editor-testing/

I hope is it what you want/need/ask

**Comment by miketaylr** [comment]
This is so great, thank you!

**Comment by softvision-oana-arbuzov** [comment]
Update: a bit of research and manual testing on the @magsout provided page.

**Comment by softvision-oana-arbuzov** [comment]
Update: Research on functionality for:
- https://draftjs.org/
- https://trix-editor.org/
- https://github.com/tinymce/tinymce

**Comment by miketaylr** [comment]
When we do file bugs, we should link them here: https://docs.google.com/document/d/12kA5Ng11keqFdfMngEqLmEqggmXSoxa6vSKbBpuYlkw/edit#

**Comment by softvision-oana-arbuzov** [comment]
We've performed exploratory testing on all platforms (Windows/Linux/Mac) on:
- https://draftjs.org/
- https://github.com/tinymce/tinymce

**Comment by softvision-oana-arbuzov** [comment]
Issues found:
58643 webcompat.github.io - Flags emoji are not displayed properly (Chrome)
58646 webcompat.github.io - Incorrect display of pasted icon (Chrome)
58695 webcompat.github.io - H1 text is enlarged when using "Bold" style (Firefox)
58740 quilljs.com - Incorrect highlight on text with background color (Firefox) 
58745 quilljs.com - Paragraphs get selected when double clicking at the end of them (Firefox) 
58752 webcompat.github.io - "Remove" button does not remain active after selecting the attached file (Firefox)
