### ISSUE TITLE
2020Q3 - 1.1 Remove form v1 legacy code

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#139]
I'm not sure if there is a corresponding issue for the webcompat.com repo yet, so we should file one if not. 

This issue is intended to cover the work removing the legacy form and related code that is unused. Possibly some refactoring since we don't need to support 2 types of forms as well.

**Comment by ksy36** [comment]
This should probably include removing/ refactoring css as well, since some of styles are no longer needed

**Comment by karlcow** [comment]
Created https://github.com/webcompat/webcompat.com/projects/12

**Comment by karlcow** [comment]
* [Removing python code](https://github.com/webcompat/webcompat.com/issues/3380)

**Comment by karlcow** [comment]
* [Removing HTML/CSS code](https://github.com/webcompat/webcompat.com/pull/3393)

**Comment by karlcow** [comment]
And we are done!
