### ISSUE TITLE
2020Q3 - Reserve: keyboard a11y testing of webcompat.com form 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#140]
It should be possible to file a bug with only the keyboard. If it's not, bugs should get filed. 🐛 ⌨️

**Comment by softvision-oana-arbuzov** [comment]
I've created a new label for Accessibility issues on webcompat.com
https://github.com/webcompat/webcompat.com/labels/a11y

**Comment by softvision-oana-arbuzov** [comment]
I did a bit of a11y testing, I just need to report the issues.

**Comment by softvision-oana-arbuzov** [comment]
Waiting for the batch of issues to be fixed/merged in order to perform confirmation testing on them.

**Comment by softvision-oana-arbuzov** [comment]
Update: 2 issues reaming. 
We will schedule a session this week to perform confirmation testing on the rest of the fixed issues.

**Comment by softvision-oana-arbuzov** [comment]
We've finished confirmation testing and below are the results:
- verified 10 issues: [9 fixed](https://github.com/webcompat/webcompat.com/issues?q=label%3Aa11y+is%3Aclosed) and [1 reopened](https://github.com/webcompat/webcompat.com/issues/3456) (partially fixed)
- [4 new issues](https://github.com/webcompat/webcompat.com/issues?q=is%3Aopen+label%3Aa11y+is%3Aissue+created%3A%3E%3D2020-09-15+) found

Testing was performed on all platforms (Windows, Mac, Linux) and on Firefox and Chrome browsers.
