### ISSUE TITLE
2020Q3 - 2.3 Regular System Addon Release Rotations

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#145]
https://wiki.mozilla.org/Compatibility/Interventions_Releases#Intervention_Release_Owner_Schedule

We should aim to manually test interventions after a new release, so we can file bugs for removing against tracking issues. 

Firefox 80 [v13](https://bugzilla.mozilla.org/show_bug.cgi?id=1647771): Karl, soft freeze deadline: **2020-07-23**
Firefox 81 [v14](https://bugzilla.mozilla.org/show_bug.cgi?id=1649243): Ksenia, soft freeze deadline: **2020-08-20**
Firefox 82 [v15](https://bugzilla.mozilla.org/show_bug.cgi?id=1649244):Tom, soft freeze deadline: **2020-09-17**

**Comment by softvision-oana-arbuzov** [comment]
[Done] QA verification progress will be visible here (1st run 10-13.07.2020): https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=955297959

**Comment by karlcow** [comment]
so far for v13

* 1649325/1
* 1651292/1
* 1651917/1
* 1651943/1
* 1651946/1
* 1652025/1

**Comment by karlcow** [comment]
v13.0.0 has been published.

**Comment by softvision-oana-arbuzov** [comment]
We'll perform a new QA verification run 6th of August.
On desktop `about:compat` is not available https://bugzilla.mozilla.org/show_bug.cgi?id=1656863 Uncaught (in promise) Error: not allowed` on about:compat

**Comment by denschub** [comment]
@softvision-oana-arbuzov There are two preferences in `about:config`: `extensions.webcompat.perform_injections` and `extensions.webcompat.perform_ua_overrides` you can toggle to `false` to disable interventions. Please note that those preferences reset to their defaults on browser restart.

**Comment by softvision-oana-arbuzov** [comment]
[Done] QA verification progress will be visible here (2nd run 06.08.2020): https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1162622086

**Comment by softvision-oana-arbuzov** [comment]
Next QA run will be performed on 3rd of September.

**Comment by ksy36** [comment]
v14.0.0 has made it to mozilla-central and android components

**Comment by softvision-oana-arbuzov** [comment]
[Done] QA verification progress will be visible here (3nd run 03.09.2020): https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=100736700

**Comment by wisniewskit** [comment]
Version 15.0.0 has just landed in m-c and a-c.

**Comment by softvision-oana-arbuzov** [comment]
We'll perform another QA verification on 1st of October.
