### ISSUE TITLE
2020Q3 - 1.2 Create externally callable method to return an issue as a static file

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#146]
Some details here: https://github.com/webcompat/webcompat.com/issues/3326

Some forward progress on https://github.com/webcompat/webcompat.com/projects/10

**Comment by karlcow** [comment]
Development has been started. 
Follow on this draft pull request https://github.com/webcompat/webcompat.com/pull/3406

**Comment by karlcow** [comment]
Progress is ongoing. We are on track with trying to keep everything tested at 100%.

**Comment by karlcow** [comment]
* [x] Issue data extraction and modelization
* [x] issue as_html
* [x] save
* [x] issue html template prototype
* [x] comments extraction and modelization
* [x] comment as_html
* [x] convert body from markdown to html
* [x] individual comment template
* [x] for-loop for comments

The basics functionality should be finished by next meeting in 2 weeks. 
The layout is probably the difficult choice

Then we need to decide how we plug this in the rest of the system (but not sure it's part of this okr).


<img width="866" alt="Capture d’écran 2020-08-18 à 08 27 46" src="https://user-images.githubusercontent.com/505230/90453919-cd748e80-e12c-11ea-9963-1d62f36e9343.png">

**Comment by karlcow** [comment]
We are basically done. 
The rest is the template details what we want to display, and where. 

We have a tool now, which allows us if needed to be called from an external script, from inside flask, whichever we think make sense. That will take an issue dictionary and creates an html page ready to save at the location of our choice.
