### ISSUE TITLE
2020Q3 - 4.1 Fix FastClick.js issues via intervention

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#147]
There's a few approaches we could take, but we have a lot of FastClick breakage. We should fix that. 

https://github.com/webcompat/web-bugs/labels/type-fastclick

**Comment by miketaylr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1448747

**Comment by karlcow** [comment]
I'm not sure we see that many fastclick issues anymore. I propose we close this.
