### ISSUE TITLE
2018-Q3 2.3 Enable Report Site Issue menu in Fennec Beta channel

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#15]
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1452783

**Comment by miketaylr** [comment]
Update: @denschub is going to tackle this one.

**Comment by denschub** [comment]
Patch waiting for review: https://bugzilla.mozilla.org/show_bug.cgi?id=1452783#c5

**Comment by miketaylr** [comment]
Update: Dennis is looking for a reviewer.

**Comment by denschub** [comment]
Landed! Let's wait with marking this as done until it's merged to central and didn't get backed out in a day, but let's bump the confidence. :)

**Comment by miketaylr** [comment]
https://hg.mozilla.org/mozilla-central/rev/7a7a689a669b

**Comment by miketaylr** [comment]
> and didn't get backed out in a day, but let's bump the confidence. :)

Oh haha, got too excited. If it gets backed out, I'll toggle it back... 🙈
