### ISSUE TITLE
Prototype intervention automated testing

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#152]
Can we write a simple test format that can be run via webdriver comparing a site's expected vs actual behavior before and after disabling the webcompat system addon?

**Comment by wisniewskit** [comment]
Project:

An automated test suite for the Firefox webcompat GoFaster feature which provides website interventions and SmartBlock shims.

Goals:
- reduce the related manual testing burden as much as feasible (to verify which interventions are still useful, and whether they have broken).
- operational as soon as possible during H2 2021, even if only partially.
- having tests for all UA overrides, interventions, and SmartBlock shims (as feasible).
- test them on the actual, live web pages they are intended for.
- the ability to test individual interventions, or all of them.
- support each official Firefox build which bundles the webcompat GoFaster addon (at least via emulator, if not live devices).
- include a capability to provide non-public login information for tested sites.
- is as decoupled from the Firefox build process as possible, to make it as easy to run tests as possible.
- is triggerable by QA or developers on an as-needed basis (typically once per release cycle, or as interventions are being developed).

Non-goals:
- tests requiring complicated setup (VPNs, 2FA, etc).
- running in CI.
- running on or for non-Gecko browsers.
- testing interventions not part of the webcompat GoFaster addon.

Current plan:
- de-couple the test driver from specific Mozilla repositories and infra (mozilla-central, TreeHerder).
- rely on GeckoDriver, and likely Selenium, to drive the tests (not Marionette).
- keep this driver code in a separate, standalone repository.
- keep the actual tests in the webcompat addon's repository.
- create a mach command to vendor and run the test driver on local builds, or trigger try runs.
- tests will be run with all interventions enabled, confirming whether they still function.
- variations on those tests will also be run with all interventions disabled, confirming whether they are still actually needed.

Pros:
- works well with our current deployment strategy to mozilla-central and Android Components.
- allows us to bundle just the tests with the webcompat addon (without the driver, Selenium, etc).
- allows us to run the tests against any binary of Firefox, including GeckoViewExample and Fenix, without having to build one (or at least, only requiring an artifact build for desktop).
- allows us to write vendoring scripts to simplify running tests locally.
- allows us to instead trigger test-runs on treeherder (in the near-to-mid future).
- avoids deprecated legacy test tech (Marionette).
- keeps the test driver a stand-alone project which may be used by other projects.
- makes it still feasible to port the driver to WebKit's WebDriver implementation, for future Firefox on iOS testing (or other WebDriver-capable browsers).

Cons:
- much more development effort and code compared to just relying on Marionette.
- tests themselves may be more convoluted than if using Marionette.
- unclear if we will be able to trigger try-runs without leaking non-public info like website logins.
- unclear whether GeckoDriver will require extra work to expose APIs for any complex tests.

**Comment by karlcow** [comment]
This has been done. The prototyping is done. Thanks @wisniewskit and @jgraham 

 @wisniewskit will document the status of the project in https://wiki.mozilla.org/Compatibility/Interventions_Test_Suite

For the next phase of the project, we probably need to create a new issue.
