### ISSUE TITLE
2020Q3 - 4.4 WebDriver BiDi spec work

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#154]
The goal this quarter is to get the BiDi spec into a state where there’s enough infrastructure to build out real features (script execution, logging, etc.) (perhaps in Q4).

We will link to specific GitHub issues once they exist.

Useful links: 
* https://w3c.github.io/webdriver-bidi/
* https://github.com/w3c/webdriver-bidi

**Comment by jgraham** [comment]
Made a PR for rearranging some of the schema bits https://github.com/w3c/webdriver-bidi/pull/50. Started working on the event infra.

**Comment by jgraham** [comment]
Also filed https://github.com/w3c/webdriver-bidi/pull/51 and started to look at object serilization.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/57 and https://github.com/w3c/webdriver-bidi/pull/56 also filed; these are mostly waiting on review from others. I think we made good progress here and should be in a good place to get to feature work next quarter.
