### ISSUE TITLE
2020Q3 - 3.2 wpt-sync Python 3 conversion

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#156]
[wpt-sync](https://github.com/mozilla/wpt-sync) is critical infrastructure to support bi-directional sync between Mozilla Central and the Web Platform Test project. This card tracks the work of getting the project working in Python 3 (since 2 is unsupported at this point).

We need to scope this more tightly, but here's a list of bugs:

https://github.com/mozilla/wpt-sync/labels/Python%203

Initial plan: James to get tests running in Python 3, then will identify issues to tackle after that.

**Comment by karlcow** [comment]
Probably a project in wpt-sync with a py3 - Phase 1 conversion collecting all the issues doable on Q3

**Comment by miketaylr** [comment]
Update: we have a Docker image that can use Python 3 (the tests fail). And some auto-generated annotations from MyPy. Next steps: fix the annotations, and use that to make progress.

**Comment by jgraham** [comment]
Ongoing slow progress updating the annotations. Fixed maybe 700 hundred initial failures, down to maybe 100.

**Comment by jgraham** [comment]
mypy now passes; working through Python 3 test failures; currently 30 known failures to go.

**Comment by jgraham** [comment]
Deployed Py3 version, found some issues in production, made some fixes. Basically things are looking good.
