### ISSUE TITLE
2020Q3 - 3.3 Improve wpt-sync sync landing sheriffing process

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#157]
The end result here should be some up to date documentation that sheriffs (and our team) can use to handle issues that come up from wpt-sync landings.

This is probably a good opportunity to get more than just James involved in the process (if we think that deserves its own card, we can do that too) of unsticking wpt-sync merges and updating metadata related to intermittents.

The goal is to have someone who understands the system. As artifacts, at least 2 documents:

1. documentation for sheriffing
2. documentation for handling all the problems

**Comment by jgraham** [comment]
Updated the documentation and started the process to get @denschub and @ksy36 access.

**Comment by jgraham** [comment]
Got access for denschub and ksy36. Had a meeting to demonstrate the basics of making the sync run, and set up a matrix channel for sync-sync. Need to continue to keep people involved with the process.
