### ISSUE TITLE
2020Q3 - 2.5 QA re-reverification of sitewait and needscontact issues

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#160]
Some of these issues may have been fixed, or no longer reproduce. We should check them in Q3.

**Comment by softvision-oana-arbuzov** [comment]
Progress is visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=618764285

**Comment by cipriansv** [comment]
**Needscontact** re-checked issues: 153/486. 
**Fixed** issues: 57

**Comment by cipriansv** [comment]
Updated status:

**Needscontact** re-checked issues: 270/486.
**Fixed issues**: 125

**Comment by cipriansv** [comment]
Updated status:

**Needscontact** re-checked issues: 486/486 
Fixed issues: 179
Invalid issues:14

**Sitewait** re-checked issues: 91/305
Fixed issues: 25
Invalid issues:4

**Comment by softvision-oana-arbuzov** [comment]
Final status:

Needscontact re-checked issues: 486/486
Fixed issues: 179
Invalid issues: 14

Sitewait re-checked issues: 305/305
Fixed issues: 59
Invalid issues: 11

Considering the above this task is Completed.
