### ISSUE TITLE
2020Q3 - Reserve: enable SpecialPowers for Web Platform Tests

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#161]
The idea captured in this card is one or more of the following:

1. understand which SpecialPowers APIs are used in mochitest, and break that down into:
a. things wpt can already do
b. things wpt can't do

2. Create a spec, adding the relevant APIs
3. Write some code exposing these APIs, behind a pref, or Nightly-only (or something)

**Comment by miketaylr** [comment]
@jgraham has started some of this here: https://jgraham.github.io/browser-test/

**Comment by jgraham** [comment]
I think the original request here was more literally making specialPowers itself work with gecko-only wpt. But I think both things are useful; this approach is more forward-looking but probably also longer-term. I don't think we need multiple issues yet; it's possible that doing stage 1 here will reveal that either a) there aren't many specialPowers things in use that can't be converted into cross-browser APIs so we should just do the more cross-browser thing or b) there are enough things that are really gecko only that get used that we really need to do both things.
