### ISSUE TITLE
2020Q3 - Reserve: Move webcompat production to dedicated server

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#162]
Right now we're running staging and prod on the same box, which is not ideal! So, let's split 'em up. I have the box set up (it's running the trexa API service), we just need to do the work.

It would also be interesting to perhaps keep production running on the staging box and set up load balancing via nginx.

**Comment by miketaylr** [comment]
Maybe a good collaborative project for @karlcow and @ksy36, taking the opportunity to set up Ksenia with all the accounts and special powers for deploys.

**Comment by karlcow** [comment]
This has been done.
