### ISSUE TITLE
2020Q4 - Manual testing on web learning platforms

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#168]
We could perform some testing on learning platforms since we do receive a lot of issues there 
For example we could check Udemy (Mozilla account), Codecademy, Coursera, freeCodeCamp, Google Classroom, edX etc.

**Comment by karlcow** [comment]
TODO: Karl to find a japanese online learning platform.

**Comment by karlcow** [comment]
Ah the one I was thinking about is https://www.internetacademy.jp/ but I'm not sure they have free online courses

**Comment by softvision-oana-arbuzov** [comment]
We started exploratory testing on:
- Codecademy
- Coursera
- freeCodeCamp
- Google Classroom

**Comment by softvision-oana-arbuzov** [comment]
Found issues:
- Codecademy (desktop&mobile):
https://github.com/webcompat/web-bugs/issues/62571
https://github.com/webcompat/web-bugs/issues/62580
https://github.com/webcompat/web-bugs/issues/63749
https://github.com/webcompat/web-bugs/issues/63750

- Coursera (desktop&mobile):
https://github.com/webcompat/web-bugs/issues/64220
https://github.com/webcompat/web-bugs/issues/63329

**Comment by karlcow** [comment]
This was done.
