### ISSUE TITLE
2020Q4 - ETP shim testing on 20 new sites from the optional list

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#169]
We can continue testing ETP shimming on the optional list of sites 
https://gist.github.com/englehardt/a698fa491d477cc03a67e383c8853ca0

**Comment by karlcow** [comment]
This should be discussed/coordinated with @wisniewskit

**Comment by cipriansv** [comment]
Progress visible here: 

- https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?ts=5ea7d1fa#gid=1987467379.

**Comment by softvision-oana-arbuzov** [comment]
We've finished testing all 20 sites on all platforms (Win/Mac/Linux/Android) and no issues were found.

We can mark this OKR completed.
