### ISSUE TITLE
2020Q4 - Webdriver-bidi - standardisation

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#172]
**Motivation**: Support standardisation of bidirectional communication protocol for automating browsers, in order to allow modern automation tooling (e.g. Puppeteer) to work across multiple browsers.

**Goal**: Continue driving spec work, getting it to the point where an end-user feature (e.g. logging or script execution) is specified.
**Size**: Large; maybe 1-1.5 months work in quarter

**Comment by karlcow** [comment]
James: In progress.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/62 is a new PR for working with browsing contexts, also lots of discussion at TPAC; see https://www.w3.org/wiki/WebDriver/2020-TPAC

**Comment by jgraham** [comment]
Added a PR for working with realms; realised the event subscription design can cause some race conditions so wrote up the concerns for feedback from others.

**Comment by karlcow** [comment]
https://w3c.github.io/webdriver-bidi/

**Comment by jgraham** [comment]
Responsing to feedback on open PRs which got rather delayed review.

**Comment by jgraham** [comment]
Also there's one more f2f meeting left this year and a design issue to discuss around event notifications.
