### ISSUE TITLE
2020Q4 - WPT - Enable specialPowers in gecko-only web-platform-tests

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#173]
**Goal**: Enable specialPowers in gecko-only web-platform-tests. This will reduce the number of cases where Gecko developers have to use mochitest, and in the long term allow us to move to all new tests being wpt.

**Size**: Medium. Probably a couple of weeks to a month of work

**Comment by jgraham** [comment]
This looks like it's easier than expected. I made a patch at https://phabricator.services.mozilla.com/D92035 which seems to enable SpecialPowers, although there may be some followup work to ensure that things work well for developers.

**Comment by jgraham** [comment]
That landed, just need to do an annoucement and wait for feedback.

**Comment by jgraham** [comment]
Done the announcement. No feedback so far, but also no complaints.
