### ISSUE TITLE
2020Q4 - WPT - Get testdriver APIs working correctly in cross-origin iframes/windows

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#175]
**Goal**: Get testdriver APIs working correctly in cross-origin iframes/windows where the test page has a handle to the window.

**Size**: Small. Probably a week of work

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/rfcs/pull/63

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/25833 this is as done as seems likely to happen this quater.
