### ISSUE TITLE
2020Q4 - WPTSync - Fix mach-wpt-update command to work with Python 3

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#176]
Goal: Fix mach-wpt-update command to work with Python 3. This is part of the general conversion of mach commands to Python 3 and is appropriate now because the rest of wpt is gaining Py3 compatibility and will likely switch over at the end of the year.

Size: Small? Will probably take a week or two.

Motivation: Ensure we have up-to-date web-platform-tests in m-c so that we are able to use them to test for compatibility and regressions.

**Comment by jgraham** [comment]
I tried this and it seemed to Just Work. I was surprised.

**Comment by karlcow** [comment]
The switch has not been flipped yet. 0 work to be done, just waiting for the right time.

**Comment by karlcow** [comment]
Android has crashes right now because of python 3. Why? What? Investigating. 
Stop supporting python 2 next year

**Comment by jgraham** [comment]
This is done.
