### ISSUE TITLE
 2020Q4 - Finish landing ETP shims

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-team-okrs#178]
There is one pending UX issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1661330
Work on that is in progress, and once it is complete we can finally try riding the trains.

**Comment by karlcow** [comment]
Last week, @wisniewskit figured out what needed to be done. Rescheduled for 84. Early in the next cycle.

**Comment by karlcow** [comment]
Still waiting for UX people.

**Comment by wisniewskit** [comment]
I've been on bereavement leave lately, so I haven't had a chance to complete this yet. As such we may miss another release window, but I do believe the necessary back-end work is done, and we just have to hook up the UI changes in [bz1661330](https://bugzilla.mozilla.org/show_bug.cgi?id=1661330). The UX team may not have any spare cycles to work on it, but I should be able to write that patch (and I'll post an update ASAP).

**Comment by wisniewskit** [comment]
Still no ETA. I need to chat with a UX team member who has been on PTO lately, but I'm aiming to at least have those discussions before the year's end. Since it seems likely that the required work will not land until next quarter, so this is challenged at best.

**Comment by wisniewskit** [comment]
I've met with the ETP team to confirm what needs to be done and everyone is now on the same page, but we won't be able to complete this until next quarter.

**Comment by wisniewskit** [comment]
There is good news here, but also a bit of bad news as well.

First the good: I've managed to get enough assistance to figure out the remaining issues, and there is now tangible progress on fixing them. There are two issues: one easy (a console-logging update on the addon-end), and one tricky (the main UX issue that has been blocking this project). But I have a rough idea on how to fix the UX issue, and some likely help to get it fixed, so things are looking up.

The bad news is that we won't make it for 86 at this rate, but 87 seems firmly realistic.

**Comment by wisniewskit** [comment]
I now have pbz helping me to get this effort across the finish line, helping with the ETP end of things. We're down to just the UX patch, which pbz feels he can complete (given my starter patch with the necessary changes we discussed to the webcompat addon). I feel we should have it done this cycle at this rate, but will alter my assessment as soon as pbz can give me an update.

**Comment by wisniewskit** [comment]
pbz and I have managed to get the shims code ready to land, but in the process we've uncovered some issues in the underlying front-end code which pbz feels we ought to resolve before doing so. Unfortunately that means landing in the next cycle for 88 :(

**Comment by karlcow** [comment]
Thanks for the update.

> pbz and I have managed to get the shims code ready to land, but in the process we've uncovered some issues in the underlying front-end code which pbz feels we ought to resolve before doing so. Unfortunately that means landing in the next cycle for 88 :(

Interesting! What kind of issues?

**Comment by wisniewskit** [comment]
@karlcow, I'm hoping to find out more details in tomorrow's anti-tracking team meeting. All I know for now is that there are structural issues with how the frontend code handles the state of blocked network requests across tracking categories. Also, GeckoView will also need an update, and we were concerned that we might break on Android if we deployed right now.

**Comment by karlcow** [comment]
This should be probably considered done.
