### ISSUE TITLE
2021Q1 - Site Interventions Release Calendar

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#181]
According to the [Site Interventions Release](https://wiki.mozilla.org/Compatibility/Interventions_Releases#Intervention_Release_Owner_Schedule)

* [x] [Firefox 87 (v19)](https://bugzilla.mozilla.org/show_bug.cgi?id=1686065) - @wisniewskit 2021-01-21 
* [x] [Firefox 88 (v20)](https://bugzilla.mozilla.org/show_bug.cgi?id=1688792) - @denschub 2021-02-18 
* [x] [Firefox 89 (v21)](https://bugzilla.mozilla.org/show_bug.cgi?id=1693824) - @karlcow 2021-03-18

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1097965007

UA Override to be removed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1685488 Remove UA Override for app.pixton.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1685489 Remove UA Override for criticalcareontario.ca
https://bugzilla.mozilla.org/show_bug.cgi?id=1685494 Remove UA Override for goal.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1685511 Remove UA Override for indiatimes.com

**Comment by softvision-oana-arbuzov** [comment]
New QA run - 2021-02-04

**Comment by wisniewskit** [comment]
FYI, v19 has just landed in the nightly builds on desktop and mobile.

**Comment by karlcow** [comment]
Cool! Next in line is @denschub I created the bugzilla issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1688792

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=772963905

UA Override & Interventions to be removed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1690779 Remove Intervention for gamearter.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1690792 Remove Intervention for dckids.com 
https://bugzilla.mozilla.org/show_bug.cgi?id=1690799 Remove Intervention for medium.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1690805 Remove UA Override for cc.com
https://bugzilla.mozilla.org/show_bug.cgi?id=1690816 Remove UA Override for dominos.ch

**Comment by karlcow** [comment]
@denschub Are you on track for it?

**Comment by denschub** [comment]
Yeah! Here's the PR: https://github.com/mozilla-extensions/webcompat-addon/pull/206

**Comment by denschub** [comment]
Version 20 is shipping in [mozilla-central](https://bugzilla.mozilla.org/show_bug.cgi?id=1688792) and [android-components](https://github.com/mozilla-mobile/android-components/pull/9710).

**Comment by ksy36** [comment]
Created a bugzilla issue for v21 https://bugzilla.mozilla.org/show_bug.cgi?id=1693824 
(just happened to see a candidate for an UA override)
@karlcow

**Comment by softvision-oana-arbuzov** [comment]
New QA run - 2021-03-04

**Comment by softvision-oana-arbuzov** [comment]
[Done] 3rd run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1055151762

Interventions to be removed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1696415 Remove Intervention for *.stemwijzer.nl
https://bugzilla.mozilla.org/show_bug.cgi?id=1696416 Remove Intervention for sports.ndtv.com

**Comment by karlcow** [comment]
PR done. Next step is review.
https://bugzilla.mozilla.org/show_bug.cgi?id=1693824

**Comment by karlcow** [comment]
#193 The issue for 2021Q2
