### ISSUE TITLE
 2021Q1 - [wpt] Improve debugging experience for web-platform-tests

### ISSUE THREAD

**Issue by jgraham** [mozilla/webcompat-team-okrs#188]
Difficulty figuring out which asserts ran and why tests failed is a common complaint about web-platform-tests. To improve this do some/all of the following items:
* Add testharness.js features to record when asserts run and provide the list of asserts as part of the output.
* Add opt-in console logging to track test execution
* Make it possible to run the tests under devtools
* Better integration for reftest analyzer

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/27224

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/27284

**Comment by jgraham** [comment]
I landed these; going to set this to done, although there might well be followup issues to add additional features.

**Comment by karlcow** [comment]
Congrats!
