### ISSUE TITLE
2021 Q1 - [wpt] Come up with some metrics on which test types we author

### ISSUE THREAD

**Issue by jgraham** [mozilla/webcompat-team-okrs#189]
In particular for web-platform-tests vs mochitest-plain and reftests. This should allow tracking over time so that we can see where further improvements to wpt are required.

**Comment by karlcow** [comment]
Status? Probably the report you have written, should be linked. Do we consider this ongoing or done.

**Comment by jgraham** [comment]
https://docs.google.com/document/d/149EccFbc_rWr1w5Q2bDn-98_mpfSeIInbVlkv12kf4A/edit# is the report, but it's moco only at the moment.

I think the metrics are done (we can rerun to do the ongoing part), but there should perhaps be a new issue for followup work.
