### ISSUE TITLE
2021Q2 - Site Interventions Release Calendar

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#193]
According to the [Site Interventions Release](https://wiki.mozilla.org/Compatibility/Interventions_Releases#Intervention_Release_Owner_Schedule)

* [x] [Firefox 89 (v22)](https://bugzilla.mozilla.org/show_bug.cgi?id=1702011) - @ksy36  2021-04-15 
* [x] [Firefox 90 (v23)](https://bugzilla.mozilla.org/show_bug.cgi?id=1707797) - @wisniewskit  2021-05-27 
* [x] [Firefox 91 (v24)](https://bugzilla.mozilla.org/show_bug.cgi?id=1714611) - @denschub  2021-07-08

**Comment by karlcow** [comment]
One candidate https://github.com/webcompat/web-bugs/issues/66888

**Comment by softvision-oana-arbuzov** [comment]
New QA run - 2021-04-01

**Comment by ksy36** [comment]
bug for v22 https://bugzilla.mozilla.org/show_bug.cgi?id=1702011

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1879808436

Interventions to be removed:
[1702441](https://bugzilla.mozilla.org/show_bug.cgi?id=1702441) Remove Intervention for binance.com

**Comment by ksy36** [comment]
I've have updated Firefox versioning to match the release schedule. 

Also instead of 90 I'm going to be releasing in 89 since we have skipped it (the changes that were supposed to land in 89 went to 88 instead).

**Comment by wisniewskit** [comment]
The v22 patches have indeed landed in time for 89 (desktop and Android).

**Comment by softvision-oana-arbuzov** [comment]
New QA run - 2021-05-13

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1678593143

Interventions to be removed:
[1710993](https://bugzilla.mozilla.org/show_bug.cgi?id=1710993) Remove Intervention for dev.to
[1710997](https://bugzilla.mozilla.org/show_bug.cgi?id=1710997) Remove Intervention for slack.com
[1711003](https://bugzilla.mozilla.org/show_bug.cgi?id=1711003) Remove Intervention for store.hp.com

**Comment by ksy36** [comment]
Candidate for v91 https://bugzilla.mozilla.org/show_bug.cgi?id=1712626

**Comment by softvision-oana-arbuzov** [comment]
New QA run - 2021-06-24

**Comment by softvision-oana-arbuzov** [comment]
[Done] 3rd run - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=178594192

UA Overrides to be removed: 
[1717998](https://bugzilla.mozilla.org/show_bug.cgi?id=1717998) Remove UA Override for www.homebook.pl
[1718009](https://bugzilla.mozilla.org/show_bug.cgi?id=1718009) Remove UA Override for www.vh1.com

**Comment by karlcow** [comment]
Not technically done. But next one will be @denschub in a couple of days.

**Comment by denschub** [comment]
v91 landed within the expected release train, so this is 100% done now. Closing. :)
