### ISSUE TITLE
2021Q3 - QA re-verification needscontact issues

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#198]
Some older issues may no longer be valid, let's check them.
@softvision-raul-bucata & @softvision-oana-arbuzov

**Comment by softvision-oana-arbuzov** [comment]
Progress will be available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=561554965

**Comment by softvision-oana-arbuzov** [comment]
Progress: 87 verified issues / 507 issues

**Comment by softvision-oana-arbuzov** [comment]
Progress: 126 verified issues / 507 issues

**Comment by softvision-raul-bucata** [comment]
Progress: 161 verified issues/ 507 issues

**Comment by softvision-oana-arbuzov** [comment]
Progress: 321 verified issues/ 507 issues

**Comment by softvision-raul-bucata** [comment]
Progress: 375 verified issues/ 507 issues

**Comment by softvision-oana-arbuzov** [comment]
We've finished verifying all the Needscontact issues and bellow are the results:
- **Fixed: 174 issues**
- Duplicate: 4 issues
- Invalid: 23 issues
- Incomplete: 2 issues
- Non-compat: 8 issues
- Won't fix: 2 issues
- Can't test: 6 issues
- **Reproducible: 281 issues**
