### ISSUE TITLE
2021Q3 - Needstriage on Webcompat Bugzilla

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#201]
The goal is to make sure these are all being triaged.
https://bugzilla.mozilla.org/buglist.cgi?bug_id=1183994%2C1331312%2C1461931%2C1482918%2C1503620%2C1510589%2C1531755%2C1546167%2C1549796%2C1568314%2C1576620%2C1582977%2C1602670%2C1603202%2C1604450%2C1614604%2C1635980%2C1637142%2C1642846%2C1654108%2C1660117%2C1665720%2C1670340%2C1670478%2C1671029%2C1671531%2C1672435%2C1673747%2C1673944%2C1674042%2C1674509%2C1674724%2C1678370%2C1678393%2C1679318%2C1681222%2C1685629%2C1688324%2C1689860%2C1690206%2C1690210%2C1691754%2C1691809%2C1693132%2C1694385%2C1695010%2C1697332%2C1698021%2C1698022%2C1698243%2C1698417%2C1699113%2C1699136%2C1699390%2C1699799%2C1700310%2C1701032%2C1701410%2C1702429%2C1702713%2C1703217%2C1703550%2C1706905%2C1707023%2C1707915%2C1708611%2C1708964%2C1710017%2C1711596%2C1711623%2C1711825%2C1712637%2C1712759%2C1713576%2C1714911%2C1715516%2C1716220%2C1717114%2C1717372%2C1717890%2C1718667%2C1718669&list_id=15766011

@softvision-oana-arbuzov & @softvision-raul-bucata

**Comment by softvision-oana-arbuzov** [comment]
Progress is available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=451245690

**Comment by softvision-oana-arbuzov** [comment]
Progress: 44 triaged issues / 82 issues

**Comment by softvision-oana-arbuzov** [comment]
Progress: 71 triaged issues / 82 issues

**Comment by softvision-raul-bucata** [comment]
Progress: 78 triaged issues/ 82 issues

**Comment by softvision-oana-arbuzov** [comment]
We've finished triaging the issues and bellow is the result:
- 1 issue **Fixed**
- 30 issues **Worksforme**
- 15 issues Needinfo user
- 3 issue Invalid
- 1 issue Incomplete
- 6 issues No account
- 2 issues Can't test
- 1 issue Won't fix
- 1 issue **Reopened**
- 22 issues **Reproducible**

This talks is completed. I will close it.
