### ISSUE TITLE
Ensure the Webcompat addon is also shipped on Focus for Android

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#204]
https://github.com/mozilla-mobile/focus-android/issues/4525

**Comment by wisniewskit** [comment]
This appears to have landed as part of this commit: https://github.com/mozilla-mobile/focus-android/commit/95b49cc5b264295db9a81998536a86c3556953a7

I'm not sure if SmartBlock is working 100%, but that can be fixed in a follow-up outside of this OKR.

**Comment by wisniewskit** [comment]
This is indeed done, with the caveat that SmartBlock opt-in logins (for "log in with Facebook" oauth buttons) are intentionally not enabled until UX can be considered which is in-line with Focus' desires.
