### ISSUE TITLE
2022Q1 - Test Top 50 Alexa site with Firefox v.100

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#218]
Test top 50 Alexa sites to make sure they work with Firefox version.100.
https://www.alexa.com/topsites

**Comment by karlcow** [comment]
Let's wait first for the results of The Firefox 100 experiment going.

**Comment by softvision-oana-arbuzov** [comment]
Experiment is completed, thus we can test ourselves. 

Progress will be available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1466880256

**Comment by softvision-oana-arbuzov** [comment]
Progress 04.02.2022:
- [Google.com](https://www.google.com)
- [Youtube.com](http://youtube.com/)

**Comment by softvision-raul-bucata** [comment]
Progress 11.02.2022:
- [Tmall.com](https://www.tmall.com)
- [Baidu.com](https://www.baidu.com/)
- [Facebook.com](https://www.facebook.com/)
- [Taobao.com](http://taobao.com/)
- [QQ.com](http://qq.com/)
- [Sohu.com](http://sohu.com/)
- [360.cn](https://www.360.cn/)
- [Jd.com](http://jd.com/)

**Comment by softvision-oana-arbuzov** [comment]
Progress 18.02.2022:
- [Amazon.com](https://www.amazon.com/)
- [Wikipedia.org](https://www.wikipedia.org/)
- [Sina.com.cn](https://sina.com.cn/)
- [Yahoo.com](http://yahoo.com/)

**Comment by softvision-raul-bucata** [comment]
Progress 25.02.2022:
- [Weibo.com](http://weibo.com/)
- [Xinhuanet.com](http://xinhuanet.com/)
- [Live.com](http://live.com/)
- [Microsoft.com](http://microsoft.com/)
- [Zoom.us](http://zoom.us/)
- [Netflix.com](http://netflix.com/)
- [Reddit.com](http://reddit.com/)
- [Office.com](http://office.com/)

**Comment by softvision-oana-arbuzov** [comment]
Progress 04.03.2022:

- [Zhanqi.tv](https://zhanqi.tv/)
- [Alipay.com](https://alipay.com/)
- [Csdn.net](https://csdn.net/)
- [Vk.com](https://vk.com/)
- [Bongacams.com](https://bongacams.com/)
- [Twitter.com](https://twitter.com/)
- [Amazon.in](https://amazon.in/)
- [Okezone.com](https://okezone.com/)
- [Panda.tv](http://panda.tv/)
- [Google.com.hk](http://google.com.hk/)
- [Bing.com](http://bing.com/)
- [Myshopify.com](http://myshopify.com/)
- [Microsoftonline.com](http://microsoftonline.com/)
- [Yahoo.co.jp](http://yahoo.co.jp/)
- [Naver.com](http://naver.com/)
- [Twitch.tv](http://twitch.tv/)
- [Ebay.com](http://ebay.com/)

**Comment by softvision-oana-arbuzov** [comment]
We've finished checking all top Alexa 50 sites, both on desktop and mobile with Firefox Nightly v.100. 

Based on the results and issues found sites that are considered "**Fail**"
- desktop [Yahoo.com](http://yahoo.com/)

Sites no longer available (N/A) or app required:
- [Panda.tv](http://panda.tv/)
- [Microsoftonline.com](http://microsoftonline.com/)
- mobile - [Alipay.com](https://alipay.com/)

**Found issues:**
- [99635](https://github.com/webcompat/web-bugs/issues/99635) www.yahoo.com - Extra "meatball" menu is present in top menu bar
- [99636](https://github.com/webcompat/web-bugs/issues/99636) www.yahoo.com - Icon is missing from the "Mail" button
- [99638](https://github.com/webcompat/web-bugs/issues/99638) www.yahoo.com - Page has squeezed content due to padding values
- [99639](https://github.com/webcompat/web-bugs/issues/99639) www.yahoo.com - Suggestion pop-up is not present
- [100733](https://github.com/webcompat/web-bugs/issues/100733) www.adobe.com - Incorrect slideshow animation
