### ISSUE TITLE
2022Q2 - QA re-verification of Sitewait issues

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#223]
Some older issues may no longer be valid, let's check them.
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+milestone%3Asitewait

**Comment by softvision-oana-arbuzov** [comment]
Progress - 15.04.2022 : 47/372

**Comment by softvision-raul-bucata** [comment]
Progress - 21.04.2022 : 139/372

**Comment by softvision-raul-bucata** [comment]
Progress - 29.04.2022 : 151/372

**Comment by softvision-oana-arbuzov** [comment]
Progress - 06.05.2022 : 228/372

**Comment by softvision-oana-arbuzov** [comment]
Progress - 13.05.2022 : 245/372

**Comment by softvision-raul-bucata** [comment]
Progress - 20.05.2022 : 372/372

**Comment by softvision-oana-arbuzov** [comment]
We've finished re-verification of Sitewait issues and below are the results:
![image](https://user-images.githubusercontent.com/12184325/170948146-f798bde3-928a-4f69-b904-cf7677547ae1.png)
