### ISSUE TITLE
2022Q1 - QA re-verification of Contactready issues

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#224]
Some older issues may no longer be valid, let's check them.
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+milestone%3Acontactready

**Comment by softvision-oana-arbuzov** [comment]
Progress will be visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1042435056

**Comment by softvision-raul-bucata** [comment]
Progress 7/01/2022: 40/103

**Comment by softvision-raul-bucata** [comment]
Progress 7/01/2022: 41/103

**Comment by softvision-oana-arbuzov** [comment]
We've finished this task and bellow is the progress:
- Fixed issues: **28**
- Non-compat: 3
- Invalid: 8
- Needinfo: 2
- Reproducible: **62**
