### ISSUE TITLE
2022Q1 - needstriage on Webcompat Bugzilla

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#225]
We currently have 70 issues without a webcompat keywords, so supposedly being in need of needs-diagnosis or another status.

The goal is to make sure these are all being triaged.
https://bugzilla.mozilla.org/buglist.cgi?cmdtype=dorem&remaction=run&namedcmd=needs-triage&sharer_id=473918

**Comment by karlcow** [comment]
Yes!

**Comment by karlcow** [comment]
And could you in your routine when moved to needsdiagnosis to just assign someone to them. one of the 4 by rotation.

**Comment by softvision-oana-arbuzov** [comment]
Progress will be visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1662301213

**Comment by softvision-raul-bucata** [comment]
Progress 7/01/2022: 11/70

**Comment by softvision-oana-arbuzov** [comment]
Progress 14/01/2022: 32/70

**Comment by softvision-oana-arbuzov** [comment]
Progress 21/01/2022: 36/70

**Comment by softvision-raul-bucata** [comment]
Progress 28/01/2022: 38/70

**Comment by softvision-oana-arbuzov** [comment]
Progress 04/02/2022: 65/70

**Comment by softvision-oana-arbuzov** [comment]
Progress 11/02/2022: 68/70

**Comment by softvision-oana-arbuzov** [comment]
We've finished checking the Bugzilla issue and below is the result:
- Fixed : **9**
- Worksforme: **14**
- Meta Bug: 4
- Wontfix : 1
- Incomplete: 1
- NeedInfo User: **23**
- Reproducible: **18**
