### ISSUE TITLE
2022 - Bugzilla Webcompat clean-up

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#227]
Investigate old Bugzilla issues.
https://bugzilla.mozilla.org/describecomponents.cgi?product=Web%20Compatibility

**Comment by denschub** [comment]
I went through all the issues in the "Interventions" component, so that's done. :)

**Comment by karlcow** [comment]
@softvision-oana-arbuzov did you mean the compat bugs to triage and diagnosis? or something else.]
@denschub "just" did for Interventions. (Thanks)

**Comment by softvision-oana-arbuzov** [comment]
@karlcow yes we'll check the compat bugs on Bugzilla (Desktop & Mobile).

**Comment by softvision-oana-arbuzov** [comment]
Mobile Webcompat list: https://bugzilla.mozilla.org/buglist.cgi?product=Web%20Compatibility&component=Mobile&resolution

Progress will be visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=700729771

**Comment by softvision-oana-arbuzov** [comment]
[Mobile Webcompat] Progress - 18.03.2022 : 8/50

**Comment by softvision-oana-arbuzov** [comment]
We've finished checking Bugzilla issues (Mobile) and below are the results:

![image](https://user-images.githubusercontent.com/12184325/159970089-4db8c0ef-b701-41e4-a577-66173a1378b3.png)

**Comment by softvision-oana-arbuzov** [comment]
Desktop Webcompat list: https://bugzilla.mozilla.org/buglist.cgi?product=Web%20Compatibility&component=Desktop&resolution=---&list_id=16032293

Progress will be visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=2089421580

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 25.03.2022 : 1/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 01.04.2022 : 19/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 08.04.2022 : 43/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 15.04.2022 : 64/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 21.04.2022 : 74/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 29.04.2022 : 79/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 06.05.2022 : 87/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 13.05.2022 : 89/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 20.05.2022 : 120/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 27.05.2022 : 140/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 03.06.2022 : 153/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 10.06.2022 : 173/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 17.06.2022 : 187/300

**Comment by softvision-oana-arbuzov** [comment]
[Desktop Webcompat] Progress - 24.06.2022 : 232/300

**Comment by softvision-raul-bucata** [comment]
[Desktop Webcompat] Progress - 1.07.2022 : 300/300

**Comment by softvision-raul-bucata** [comment]
We've finished checking Bugzilla issues (Desktop) and below are the results:

![Screenshot_4](https://user-images.githubusercontent.com/75027050/176849241-f037803d-9398-42ab-8911-d98090e71d68.jpg)

**Comment by denschub** [comment]
Amazing work! :)

**Comment by karlcow** [comment]
Congratulations!
