### ISSUE TITLE
2018-Q3 3.3 Finish weekly reporting dashboard powered by new metrics server / client

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#23]

**Comment by miketaylr** [comment]
Update: getting all the server / db stuff set up. Working on tests + refactoring. 

> It'll get there

**Comment by miketaylr** [comment]
Update: the backend has landed. Kate is working on ideas around how to present thing via the frontend.

**Comment by miketaylr** [comment]
> Anyone who wants to weigh in on data to be included or presentation style can add comments here: https://github.com/webcompat/webcompat-metrics-client/issues/95

**Comment by miketaylr** [comment]
Update: working on getting more test data in, looking to prototype needsdiagnosis stuff in the coming weeks.

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat-metrics-server/pull/61/files has landed. 🎉

**Comment by miketaylr** [comment]
I'm gonna put this at 50% done -- @laghee has built a backend and remote service to power this. Next up: front-end bits. (it could be less than 50%, just being conservative here)

**Comment by karlcow** [comment]
laghee's PR has been merged on the server side part,
