### ISSUE TITLE
List ETP-related interventions on about:compat

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-team-okrs#232]
SmartBlock/ETP shims are not presently listed on about:compat. Work for adding them is progressing in [bz1723776](https://bugzilla.mozilla.org/show_bug.cgi?id=1723776).

There will almost certainly be some related follow-up work, such as [bz1728110](https://bugzilla.mozilla.org/show_bug.cgi?id=1728110)

Rough time estimate: about one week of engineering.

**Comment by karlcow** [comment]
While this shares the same spot for webcompat site interventions. I believe this is work we should be tracked by the privacy team.

**Comment by wisniewskit** [comment]
This is now done, and about:compat on desktop, Fenix, and Focus on Android shows the ETP-related shims under "SmartBlock Fixes".
