### ISSUE TITLE
Make a concrete plan for iOS interventions/SmartBlock

### ISSUE THREAD

**Issue by wisniewskit** [mozilla/webcompat-team-okrs#236]
Having a document outlining our proposals, intents, and how our code aims to work would be beneficial for others to know which code we're adding and why.

Rough time estimate: 2+ days of effort to compile our thoughts and create a document, after having spent some time to figure out our thoughts in the first place.

**Comment by karlcow** [comment]
This seems to be for the Privacy team.

**Comment by wisniewskit** [comment]
Actually, I intended it to be for our port of the webcompat addon's capabilities to iOS, including UA overrides and JS/CSS interventions (the SmartBlock/ETP-specific parts can be treated separately, though they are likely to be very similar overall).

**Comment by wisniewskit** [comment]
This is effectively a dupe of #205, as the investigations for both the webcompat and SmartBlock parts of the addon are happening in parallel.
