### ISSUE TITLE
2018-Q3 1.5 Support "Dark Funnel" tiger team reporting needs

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#25]
The dark funnel tiger team is trying to understand which non-mozilla.org sites are offering Firefox downloads. They approached us to see what we can do.

**Comment by miketaylr** [comment]
Update: A mostly done version exists, just waiting on some questions around required forms.

English, Spanish, and Basaha localization also done.

They also need a script to dump report values to CSV, tbd if I'm doing that too.

**Comment by miketaylr** [comment]
Update: 99% done. In testing right now, a few requests to change things.

**Comment by CajuM** [comment]
Will the public at large get that report and csv?
