### ISSUE TITLE
Write an explainer about site interventions

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#252]
Goal: offer a document which can be used as a reference and/or blog post explaining site interventions.

* What does it solve?
* What is the architecture on the Gecko side? (Probably a couple of graphs)
* Rough explanation of the release cycle
* How to create site interventions (with code examples)?
   * JavaScript
   * CSS

**Comment by denschub** [comment]
This seems like something I would enjoy, so I'm preemptively assigning myself. But if someone else wants to work on this, please, feel free to take this!

**Comment by denschub** [comment]
We have the following wiki pages:

- https://wiki.mozilla.org/Compatibility/System_Addon
- https://wiki.mozilla.org/Compatibility/System_Addon/Override_Policies_and_Workflows
- https://wiki.mozilla.org/Compatibility/System_Addon/Release_Process (probably the most relevant!)
