### ISSUE TITLE
[H1] Testing of top 20 Leading Online Marketplaces Worldwide sites

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#257]
Exploratory testing on top 20 Leading Online Marketplaces Worldwide.

1.  Amazon | Global - [830](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Amazon) webcompat issues
2.  eBay | Global - [406](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+eBay+) webcompat issues
3.  Mercado Libre | Latin America - [18](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+MercadoLibre+) webcompat issues
4.  Rakuten | Japan - [33](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Rakuten+) webcompat issues
5. AliExpress | Global - [122](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+AliExpress) webcompat issues
6. Shopee | Southeast Asia - [14](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Shopee) webcompat issues
7. Walmart.com | USA - [10 ](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Walmart.com) webcompat issues
8. Etsy | Global - [23](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Etsy) webcompat issues
9. Taobao | China - [30](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Taobao+) webcompat issues
10. Pinduoduo | China - [0](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Pinduoduo) webcompat issues
11. Trendyol | Turkey - [3](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Trendyol) webcompat issues
12. Allegro | Poland - [14](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Allegro) webcompat issues
13. Target.com | USA - [4](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Target.com) webcompat issues
14. Wayfair | North America, Europe - [9](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Wayfair+) webcompat issues
15. JD.com | China - [4](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+JD.com) webcompat issues
16. Flipkart | India - [97](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Flipkart) webcompat issues
17. Wildberries | Russia - [3](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Wildberries+) webcompat issues
18. Tokopedia | Indonesia - [12](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Tokopedia) webcompat issues
19. Lazada | Southeast Asia - [27](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Lazada) webcompat issues
20. Zalando | Europe - [15](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Zalando) webcompat issues

This top is according to https://www.webretailer.com/b/online-marketplaces/#/

Progress will be visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1340023429

**Comment by softvision-oana-arbuzov** [comment]
Progress 20.05.2022 sites:
- Amazon

**Comment by softvision-raul-bucata** [comment]
Progress 27.05.2022:
 - Amazon
 - Ebay

**Comment by softvision-oana-arbuzov** [comment]
Progress 03.06.2022:
- Amazon
- Ebay
- Zalando

**Comment by softvision-oana-arbuzov** [comment]
Progress 10.06.2022:

- Amazon
- Ebay
- Zalando
- Lazada

**Comment by softvision-raul-bucata** [comment]
Progress 17.06.2022:

- Amazon
- Ebay
- Zalando
- Lazada (.com, .co.in)

**Comment by softvision-oana-arbuzov** [comment]
Progress 24.06.2022:
- Lazada (.co.in)
- Rakuten
- Shopee
- Wayfair

**Comment by softvision-raul-bucata** [comment]
Progress 1.07.2022:

- Lazada
- Shopee -desktop
- Wayfair -mobile
- Wildberries.ru
- Wildberries.eu

**Comment by softvision-oana-arbuzov** [comment]
This task is done for H1.
