### ISSUE TITLE
2022Q3 - QA re-verification of Needscontact issues

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#260]
Some older issues may no longer be valid, let's check them.
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+milestone%3Aneedscontact

**Comment by softvision-oana-arbuzov** [comment]
Progress will be available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=792912894

**Comment by softvision-oana-arbuzov** [comment]
Progress - 29.07.2022: 12/499

**Comment by softvision-oana-arbuzov** [comment]
Progress - 05.08.2022: 48/499

**Comment by softvision-oana-arbuzov** [comment]
Progress - 12.08.2022: 112/499

**Comment by softvision-oana-arbuzov** [comment]
Progress - 19.08.2022: 165/499

**Comment by softvision-oana-arbuzov** [comment]
Progress - 26.08.2022: 245/499

**Comment by softvision-raul-bucata** [comment]
Progress - 02.09.2022 332/499

**Comment by softvision-raul-bucata** [comment]
Progress - 09.09.2022 401/499

**Comment by sv-calin** [comment]
Progress - 16.09.2022 483/499

**Comment by softvision-oana-arbuzov** [comment]
Progress - 23.09.2022 498/499

**Comment by softvision-raul-bucata** [comment]
Progress - 30.09.2022 499/499

**Comment by softvision-raul-bucata** [comment]
We've finished the re-verification of Needscontact issues and below are the results:

![Screenshot_11](https://user-images.githubusercontent.com/75027050/193596781-5ff4a8d2-e73d-4e1a-8d5c-8f67d3363536.jpg)
