### ISSUE TITLE
[H2] Testing of top 20 Leading Online Marketplaces Worldwide sites

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#261]
Exploratory testing on top 20 Leading Online Marketplaces Worldwide.

1.  Amazon | Global - [830](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Amazon) webcompat issues
2.  eBay | Global - [406](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+eBay+) webcompat issues
3.  Mercado Libre | Latin America - [18](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+MercadoLibre+) webcompat issues
4.  Rakuten | Japan - [33](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Rakuten+) webcompat issues
5. AliExpress | Global - [122](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+AliExpress) webcompat issues
6. Shopee | Southeast Asia - [14](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Shopee) webcompat issues
7. Walmart.com | USA - [10 ](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Walmart.com) webcompat issues
8. Etsy | Global - [23](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Etsy) webcompat issues
9. Taobao | China - [30](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Taobao+) webcompat issues
10. Pinduoduo | China - [0](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Pinduoduo) webcompat issues
11. Trendyol | Turkey - [3](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Trendyol) webcompat issues
12. Allegro | Poland - [14](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Allegro) webcompat issues
13. Target.com | USA - [4](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Target.com) webcompat issues
14. Wayfair | North America, Europe - [9](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Wayfair+) webcompat issues
15. JD.com | China - [4](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+JD.com) webcompat issues
16. Flipkart | India - [97](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Flipkart) webcompat issues
17. Wildberries | Russia - [3](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Wildberries+) webcompat issues
18. Tokopedia | Indonesia - [12](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Tokopedia) webcompat issues
19. Lazada | Southeast Asia - [27](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Lazada) webcompat issues
20. Zalando | Europe - [15](https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+Zalando) webcompat issues

This top is according to https://www.webretailer.com/b/online-marketplaces/#/

Note: This continues the task from [H1] https://github.com/mozilla/webcompat-team-okrs/issues/257

Progress will be visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1340023429

**Comment by softvision-oana-arbuzov** [comment]
Progress 8.07.2022:
- Shopee - mobile
- Etsy - desktop
- Wildberries.ru - desktop & mobile

**Comment by softvision-raul-bucata** [comment]
Progress 15.07.2022:
- Aliexpress.com -desktop
- Etsy - desktop and mobile
- MercadoLibre.com.co desktop

**Comment by softvision-raul-bucata** [comment]
Progress 22.07.2022:
- wallmart.com - mobile and desktop

**Comment by softvision-oana-arbuzov** [comment]
Progress 29.07.2022:
- Flipkart - mobile & desktop

**Comment by softvision-oana-arbuzov** [comment]
Progress 05.08.2022:
- Target.com - mobile

**Comment by softvision-oana-arbuzov** [comment]
Progress 12.08.2022:

- Target.com - desktop
- Tokopedia.com - desktop & mobile
- Pinduoduo.com - desktop

**Comment by softvision-oana-arbuzov** [comment]
Progress 19.08.2022:
- Pinduoduo.com - mobile
- Trendyol - mobile & desktop

**Comment by softvision-oana-arbuzov** [comment]
Progress 26.08.2022:

- Allegro - mobile & desktop

**Comment by softvision-raul-bucata** [comment]
Progress 02.09.2022:

- MercadoLibre.com.co - mobile & desktop

**Comment by softvision-raul-bucata** [comment]
Progress 09.09.2022:

- Taobao.com -mobile & desktop

**Comment by softvision-oana-arbuzov** [comment]
We've finished testing the top 20 Leading Online Marketplaces Worldwide sites.

**Issues found:**
- https://github.com/webcompat/web-bugs/issues/110031
- https://github.com/webcompat/web-bugs/issues/107804
- https://github.com/webcompat/web-bugs/issues/107749
- https://github.com/webcompat/web-bugs/issues/110802 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1790622
- https://bugzilla.mozilla.org/show_bug.cgi?id=1789377
- https://github.com/mozilla-mobile/fenix/issues/26835
- https://bugzilla.mozilla.org/show_bug.cgi?id=1782968
- https://bugzilla.mozilla.org/show_bug.cgi?id=1782925
- https://bugzilla.mozilla.org/show_bug.cgi?id=1782956
- https://github.com/webcompat/web-bugs/issues/107933
- https://github.com/webcompat/web-bugs/issues/107945
- https://github.com/webcompat/web-bugs/issues/107942
- https://github.com/webcompat/web-bugs/issues/107988
- https://github.com/webcompat/web-bugs/issues/105596
- https://github.com/webcompat/web-bugs/issues/106229
- https://github.com/webcompat/web-bugs/issues/109007
- https://github.com/webcompat/web-bugs/issues/109215
- https://github.com/webcompat/web-bugs/issues/109740
- https://bugzilla.mozilla.org/show_bug.cgi?id=1776427
- https://github.com/webcompat/web-bugs/issues/106713
- https://github.com/webcompat/web-bugs/issues/108051
- https://github.com/webcompat/web-bugs/issues/108327
- https://github.com/webcompat/web-bugs/issues/108746 
- https://github.com/webcompat/web-bugs/issues/108745 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1783807
- https://bugzilla.mozilla.org/show_bug.cgi?id=1784042
- https://github.com/webcompat/web-bugs/issues/108887
- https://github.com/webcompat/web-bugs/issues/105333
