### ISSUE TITLE
2022Q4 - QA re-verification of Contact Ready issues

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#263]
Some older issues may no longer be valid, let's check them.
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+milestone%3Acontactready

**Comment by softvision-oana-arbuzov** [comment]
Progress will be available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=992180638

**Comment by softvision-raul-bucata** [comment]
Progress 07.10.2022: 30/63

**Comment by softvision-raul-bucata** [comment]
We've finished the re-verification of Contact Ready issues and below are the results:



![Screenshot_3](https://user-images.githubusercontent.com/75027050/195618199-832e5bb8-b7a1-49a0-8629-e97865251a18.jpg)
