### ISSUE TITLE
2022Q4 - Exploratory testing for Top 10 Sites for:  Streaming

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#264]
Exploratory testing on Top 10 Leading Worldwide Streaming Sites:

1. [YouTube](https://www.youtube.com/live) - 2,549 issues
2. [Facebook](https://www.facebook.com/watch) - 2,183 issues
3. [Twitch](https://www.twitch.tv/) - issues: 271
4. [VK](https://vk.com/video) - issues: 176
5. [TikTok](https://www.tiktok.com/) - issues: 53
6. [Voot](https://www.voot.com/) - issues: 11
7. [Vlive](https://www.vlive.tv/) - issues: 5
8. [Dlive](https://dlive.tv/) - issues: 4
9. [Nimo](https://www.nimo.tv/) - issues: 2
10. [Openrec](https://www.openrec.tv/) - issues: 0

Items to be tested with the main focus on **Streaming (media play)**, both mobile and desktop:

- Page Layout
- Home Page
- Browse menu
- Navigation (3lvls deep) / Categories/Sub-categories / Links
- Search/Add Search Engine
- Filter / Sort / Drop-down menus / Date Picker
- Pagination
- Overlays/Pop-ups
- Page Elements Alignment /Lists / Bullets
- Forms (typing information) / Text Fields / Radio Buttons / Check Boxes
- Text / Padding / Font Size / Font Color / Font Style
- Background
- Video Media Player - play/pause, fast forward, back/next video, volume, settings... (on both uploaded/live videos)
- Portrait / Landscape Mode
- Full Screen Mode
- Picture in Picture
- Captions / Subtitles
- Video quality
- Video performance (load time/lag)
- Follow/Subscribe to channels/users
- Comment / Reply / React
- Private Chat (send/receive messages)
- Live chat (comment/react)
- Attach/Upload media (in chat and account)
- Make playlists - Add/remove/organize videos
- Add/Remove videos from favorites / Edit favorites
- Upload videos
- Live Stream (if possible without external software)
- Share media (Google, FB, Twitter etc.)
- Notifications
- Download app link(if available)
- Ads display (not to hinder site navigationm dismissive)
- Create account / Email confirmation link / Sign in /Sign out / User account details / Editing / Profile Page / Error handling
- Help / Contact / Subscribe / Customer feedback / About / Terms of Usage / Privacy
- Toggle Mobile/Desktop
- Differences in the UI with respect to look and feel

Document source: [Top Live Streaming & Movie Stream Websites Worldwide](https://docs.google.com/document/d/1mfazfJ03Zmf4zrFVQ7vrMFuk8HoRYLRK-6sJ0tziLSQ/edit?pli=1&skip_itp2_check=true)

**Comment by softvision-raul-bucata** [comment]
Progress 14.10.2022:
- Openrec.tv -desktop
- Vk.com -mobile and desktop
- Vlive.tv -desktop
- Nimo.tv -desktop

**Comment by softvision-raul-bucata** [comment]
Progress 21.10.2022:
- Openrec.tv -desktop and mobile
- Dlive.tv -desktop and mobile

**Comment by softvision-raul-bucata** [comment]
Progress 28.10.2022:
* Openrec.tv - mobile

**Comment by softvision-raul-bucata** [comment]
Progress 04.11.2022:
* Tiktok.com - mobile
* Voot.com -desktop

**Comment by sv-calin** [comment]
Progress 11.11.2022:
* tiktok.com - desktop
* voot.com - mobile

**Comment by softvision-raul-bucata** [comment]
Progress 18.11.2022:

* Twitch.tv - desktop
* Voot.com - mobile
* Tiktok.com - desktop

**Comment by sv-calin** [comment]
Progress 25.11.2022:
* Twitch.tv - desktop
* Voot.com - mobile

**Comment by sv-calin** [comment]
Progress 02.12.2022:
* None this week

Note:
- National holidays in Romania (30 nov - 1 dec)
- Raul PTO (25th of November - 2nd of December)

**Comment by softvision-raul-bucata** [comment]
Progress 09.12.2022:
* Twitch.com - mobile and desktop
* Youtube.com - desktop

Note:
- Calin PTO (8th of December)

**Comment by softvision-raul-bucata** [comment]
Progress 16.12.2022:
* Twitch.tv - mobile 
* Facebook - desktop
* Youtube.com - desktop

**Comment by softvision-raul-bucata** [comment]
Progress 23.12.2022:
* Facebook - desktop
* Youtube.com - desktop and mobile

**Comment by softvision-raul-bucata** [comment]
Progress 30.12.2022:
* Facebook - mobile

**Comment by softvision-raul-bucata** [comment]
We have completed the exploratory testing for the Top 10 Streaming sites worldwide. Issues found:

* https://github.com/webcompat/web-bugs/issues/115838
* https://github.com/webcompat/web-bugs/issues/115837
* https://github.com/webcompat/web-bugs/issues/115445
* https://github.com/webcompat/web-bugs/issues/115239
* https://github.com/webcompat/web-bugs/issues/114054
* https://github.com/webcompat/web-bugs/issues/112502
* https://github.com/webcompat/web-bugs/issues/112326
* https://github.com/webcompat/web-bugs/issues/112272
* https://github.com/webcompat/web-bugs/issues/113388
* https://github.com/webcompat/web-bugs/issues/113383
* https://github.com/webcompat/web-bugs/issues/112617
