### ISSUE TITLE
2022 - Q4 re-verification of NeedsDiagnosis issues

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#265]
Some older issues may no longer reproduce, let's check them:
https://github.com/webcompat/web-bugs/issues?q=milestone%3Aneedsdiagnosis+sort%3Aupdated-desc+-label%3Adiagnosis-priority-p1+-label%3Adiagnosis-priority-p2+-label%3Adiagnosis-priority-p3+-label%3Astatus-needsinfo-denschub+-label%3Astatus-needsinfo-wisniewskit+-label%3Astatus-needsinfo-ksy36+label%3Aengine-gecko+

**Comment by softvision-raul-bucata** [comment]
We will start with issues submitted by users. Progress will be available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1634164584

**Comment by softvision-raul-bucata** [comment]
Progress - 04.11.2022: 41/75 (user issues)
Total 41/172

**Comment by sv-calin** [comment]
Progress - 11.11.2022: 75/75 (user issues)
Total 75/172

**Comment by softvision-raul-bucata** [comment]
Progress - 18.11.2022: 92/172

**Comment by sv-calin** [comment]
Progress - 25.11.2022: 158/172

**Comment by sv-calin** [comment]
Progress - 02.12.2022: 158/172

**Comment by softvision-raul-bucata** [comment]
Progress - 09.12.2022: 172/172

**Comment by softvision-raul-bucata** [comment]
We've finished the re-verification of Needs Diagnosis issues and below are the results:

![Screenshot_10](https://user-images.githubusercontent.com/75027050/206737200-d6d7ef1a-97a6-445a-bd24-6fab69a1c18d.jpg)
