### ISSUE TITLE
2023Q1 - Bugzilla Webcompat clean-up

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#269]
Investigate old Bugzilla issues, both mobile and desktop
https://bugzilla.mozilla.org/describecomponents.cgi?product=Web%20Compatibility

**Comment by softvision-raul-bucata** [comment]
We will start with the desktop issues, based on this query, from old to new (chronological order): https://bugzilla.mozilla.org/buglist.cgi?product=Web%20Compatibility&component=Desktop&resolution=---&list_id=16360449. Progress will be available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1434610859

**Comment by sv-calin** [comment]
Progress - 13.01.2023: 41/205

**Comment by softvision-raul-bucata** [comment]
Progress 20.01.2023: 115/205

**Comment by softvision-raul-bucata** [comment]
Progress 27.01.2023: 132/205

**Comment by softvision-raul-bucata** [comment]
Progress 03.02.2023: 205/205

**Comment by sv-calin** [comment]
We have started checking the old bugzilla mobile issues: https://docs.google.com/spreadsheets/d/1b1K-Zk35uLCk_6n2I-aON-4yc0bkZWQQPme1Em59QOQ/edit#gid=937071978

Progress 10.02.2023: 26/30

**Comment by softvision-raul-bucata** [comment]
[done] Progress 17/02/2023 30/30 mobile 205/205 desktop 235/235 total
