### ISSUE TITLE
2023Q1 - Exploratory testing for Top 10 Sites for: Social Media

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#270]
Exploratory testing on Top 10 Leading Worldwide Social Media Sites:

1. [Facebook](http://facebook.com/) - 2244 issues
2. [Instagram](instagram.com)  -367 issues
3. [Twitter](twitter.com) - 769 issues
4. [Reddit](reddit.com) - 559 issues
5. [Tiktok](tiktok.com) - 57 issues
6. [Whatsapp](whatsapp.com) - 45 issues
7. [Wechat](wechat.com) - 0 issues
8. [Telegram](telegram.org) - 6 issues
9. [Snapchat](snapchat.com) - 6 issues
10. [Linkedin](linkedin.com) - 189 issues

Items to be tested with the main focus on **Social Media**, both mobile and desktop:

- Page Layout
- Home Page
- Browse menu
- Navigation (3lvls deep) / Categories/Sub-categories / Links
- Search/Add Search Engine
- Post status(text, media)
- Overlays/Pop-ups
- Page Elements Alignment /Lists / Bullets
- Forms (typing information) / Text Fields / Radio Buttons / Check Boxes
Text / Padding / Font Size / Font Color / Font Style
- Background
- Media/content quality
- Follow/Subscribe to channels/users
- Comment / Reply / React
- Private Chat (send/receive messages)
- Attach/Upload media (profile, comments)
- Share media/ articles/ content
- Notifications
- Download app link(if available) 
- Ads display (not to hinder site navigationm dismissive)
- Create account / Email confirmation link / Sign in /Sign out / User account details / Editing / Profile Page / Error handling
- Help / Contact / Subscribe / Customer feedback / About / Terms of Usage / Privacy
- Overall experience in regards to UI

Document source: [Beaucoup list](https://docs.google.com/spreadsheets/d/128x7npL8THeiGbXsYoiSRN3W19Ha7VrGN3zBUH5w3ik/edit#gid=0)

**Comment by softvision-raul-bucata** [comment]
Progress 03.02.2023:
* slack.com -desktop
* instagram.com - desktop

**Comment by sv-calin** [comment]
Progress 10.02.2023:
* facebook.com - desktop
* instagram.com - mobile

Note: we are unable to test on:
* wechat.com - unable to create account (at least not with romanian number)
* snapchat.com - not supported

**Comment by softvision-raul-bucata** [comment]
Progress 17.02.2023:
* facebook.com - desktop
* reddit.com - desktop

**Comment by sv-calin** [comment]
Progress 24.02.2023:
* facebook.com - mobile
* reddit.com - desktop

**Comment by softvision-raul-bucata** [comment]
Progress 03.03.2023:
* facebook.com - mobile
* whatsapp.com - desktop
* reddit.com - mobile

**Comment by sv-calin** [comment]
Progress 10.03.2023:
* twitter.com - mobile & desktop
* whatsapp.com - desktop
* pinterest.com - desktop

**Comment by softvision-raul-bucata** [comment]
Progress 17.03.2023:
* twitter.com - mobile 
* pinterest.com - desktop & mobile

**Comment by sv-calin** [comment]
Progress 24.03.2023:
* pinterest.com - mobile
* quora.com - desktop
* linkedin.com - mobile & desktop

**Comment by softvision-raul-bucata** [comment]
Completed 31.03.2023. 

* quora.com - mobile and desktop
* tiktok.com - mobile and desktop

Total issues found in the process: 19
