### ISSUE TITLE
2018-Q4 1.2 - Extend operational metrics work

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#28]
Add sections for needscontact, sitewait. Finish weekly stats re-write.

* [ ] Create DBs
* [ ] Add sitewait dashboard
* [ ] add needscontact dashboard
* [x] build front-end for weekly reports

**Comment by miketaylr** [comment]
cc @laghee @magsout

**Comment by miketaylr** [comment]
I believe https://github.com/webcompat/webcompat-metrics-client/issues/30 covers the "sitewait / needscontact" part.

https://github.com/webcompat/webcompat-metrics-client/issues/107 covers the weekly reports (at least the first parts of it).

**Comment by magsout** [comment]
@laghee we can think about a new dep.

**Comment by karlcow** [comment]
no progress on my side for this. I know @laghee is a bit busy too. :)

**Comment by laghee** [comment]
Thanks @magsout! I appreciate that. Since, in theory, the dashboards are going to be powered by the database rather than these temporary endpoints in a few months (or at least that's been my understanding), I'm trying to avoid adding extra packages we won't need for long.

I'll try to bend the current json to my will (or possibly alter my endpoint to return the data an easier way) before messing around with more libraries. I have some time this afternoon and tomorrow to see what I can figure out.

**Comment by karlcow** [comment]
We need to move to a DB. so we can remove our dependency from @laghee and @karlcow servers 
https://github.com/webcompat/webcompat-metrics-server/issues/4#issuecomment-434925670

**Comment by karlcow** [comment]
Added more context on DB choices to move forward on this OKR. 
https://github.com/webcompat/webcompat-metrics-server/issues/4#issuecomment-434942350

**Comment by laghee** [comment]
Very basic front end for weekly reports is hacked up and awaiting review [PR#11 on metrics-client](https://github.com/webcompat/webcompat-metrics-client/pull/111) while failing 7% of tests! 🎉 

![weekly-reports-tab](https://user-images.githubusercontent.com/20972610/48078866-854fda80-e1ea-11e8-9a5c-ac257c193ffc.png)

**Comment by karlcow** [comment]
awesome!

**Comment by laghee** [comment]
Looks like fixing the tests for the weekly issues dashboard won't be too complicated, then I can concentrate on making it look better and adding any extra features, as well as pulling in the outreach dashboard as well. I should be able to do the test fixes by the end of this week.

**Comment by laghee** [comment]
Update: Tests fixed! Adding a date filter back in this week.

**Comment by miketaylr** [comment]
Let's call this DONE. We will pick up the rest in Q1, probably.
