### ISSUE TITLE
2024H1 Bugzilla backlog triage

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#282]
This is the OKR for the Bugzilla triage task

Progress will be available [here](https://docs.google.com/spreadsheets/d/1Vun7EDha-R6p7t_rgOTPu70K1FLCMTrukmHvHZr3vOQ/edit#gid=663205964)

**Comment by softvision-raul-bucata** [comment]
`Week 22-26th of January:`

Total investigated issues: 20

**Comment by sv-calin** [comment]
`Week 29th of Jan - 2nd of Feb:`

Total investigated issues: 103

**Comment by sv-calin** [comment]
`Week 5th of Feb - 9th of Feb:`

Total investigated issues: 107

**Comment by softvision-raul-bucata** [comment]
`Week 12th of Feb - 16th of Feb:`

Total investigated issues: 204

**Comment by sv-calin** [comment]
`Week 19th of Feb - 23rd of Feb:`

Total investigated issues: 320

**Comment by softvision-raul-bucata** [comment]
`Week 25th of Feb - 1st of Mar :`

COMPLETED

Total investigated issues: 340
