### ISSUE TITLE
2024H1 - QA Support for Bugzilla Meta Bugs - 1778322 and 939897

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#283]
This OKR is set to track our work following the requested QA support for [1778322](https://bugzilla.mozilla.org/show_bug.cgi?id=1778322) and [939897](https://bugzilla.mozilla.org/show_bug.cgi?id=939897)

On the mentioned META bugs, the following will be conducted:

* Go over all linked bugs and test
* Leave one comment in each meta summarizing the status of the dependencies (both `Blocked`, `See also` and `Depends`, prioritizing the Open linked bugs vs Closed linked bugs)

**Comment by softvision-raul-bucata** [comment]
Investigated the following `opened` bugs for META [939897](https://bugzilla.mozilla.org/show_bug.cgi?id=939897):

* [1663079](https://bugzilla.mozilla.org/show_bug.cgi?id=1663079) based on [test case](https://bug1663079.bmoattachments.org/attachment.cgi?id=9187807) still **reproduces**
* [1806717](https://bugzilla.mozilla.org/show_bug.cgi?id=1806717) has **2 corresponding** meta bugs: 
-> [_939897_](https://bugzilla.mozilla.org/show_bug.cgi?id=939897) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9258107) **reproduces** 
-> [_1743890_](https://bugzilla.mozilla.org/show_bug.cgi?id=1743890)  is **fixed** provided in all test cases( 1 through 6)
* [1858571](https://bugzilla.mozilla.org/show_bug.cgi?id=1858571) still **reproduces** for all the test cases provide
* [1635225](https://bugzilla.mozilla.org/show_bug.cgi?id=1635225) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9145604) still **reproduces** following the steps to reproduce
* [521204](https://bugzilla.mozilla.org/show_bug.cgi?id=521204) **reproduces** for some [opened bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1513949)

These are opened corresponding bugs in the meta bug.

**Comment by sv-calin** [comment]
Investigated the following `opened bugs` for META [1778322](https://bugzilla.mozilla.org/show_bug.cgi?id=1778322):
* Reproducible: [1749294](https://bugzilla.mozilla.org/show_bug.cgi?id=1749294), [1753090](https://bugzilla.mozilla.org/show_bug.cgi?id=1753090)
* Not reproducible: [1772140](https://bugzilla.mozilla.org/show_bug.cgi?id=1772140)
* Couldn't test the following: [1778620](https://bugzilla.mozilla.org/show_bug.cgi?id=1778620) (asus router needed), [1806442](https://bugzilla.mozilla.org/show_bug.cgi?id=1806442) (requires third-party apps and certain technical skills), [1817853](https://bugzilla.mozilla.org/show_bug.cgi?id=1817853) (qa-not-actionable)

**Comment by softvision-raul-bucata** [comment]
Investigated the following `opened` bugs for META [939897](https://bugzilla.mozilla.org/show_bug.cgi?id=939897):

* [1233125](https://bugzilla.mozilla.org/show_bug.cgi?id=1233125) need info to test
* [1885849](https://bugzilla.mozilla.org/show_bug.cgi?id=1885849) need info to test

* [1601429](https://bugzilla.mozilla.org/show_bug.cgi?id=1601429) still **reproduces** for [521204](https://bugzilla.mozilla.org/show_bug.cgi?id=521204) and [180422](https://bugzilla.mozilla.org/show_bug.cgi?id=1804229)

These are opened corresponding bugs in the meta bug. All the opened corresponding bugs have been investigated.

**Comment by softvision-raul-bucata** [comment]
Update on the `needsinfo` items:
* [1233125](https://bugzilla.mozilla.org/show_bug.cgi?id=1233125) fixed based on the test cases provided in [1622935](https://bugzilla.mozilla.org/show_bug.cgi?id=1622935)
* [1885849](https://bugzilla.mozilla.org/show_bug.cgi?id=1885849) seems fixed based on the test cases provided in [1622935](https://bugzilla.mozilla.org/show_bug.cgi?id=1622935)

**Comment by sv-calin** [comment]
Investigated the following `opened bugs` for META [1778322](https://bugzilla.mozilla.org/show_bug.cgi?id=1778322):

* Not reproducible: [1789321](https://bugzilla.mozilla.org/show_bug.cgi?id=1789321) ([file tested](https://filesamples.com/formats/m4a)), [1805365](https://bugzilla.mozilla.org/show_bug.cgi?id=1805365) ([file tested](https://filesamples.com/formats/mp2?utm_content=cmp-true#google_vignette))

**Comment by sv-calin** [comment]
Investigated the following `closed bugs` for META [1778322](https://bugzilla.mozilla.org/show_bug.cgi?id=1778322):

* Not reproducible: [1133166](https://bugzilla.mozilla.org/show_bug.cgi?id=1133166),  [1772758](https://bugzilla.mozilla.org/show_bug.cgi?id=1772758), [1772988](https://bugzilla.mozilla.org/show_bug.cgi?id=1772988), [1772989](https://bugzilla.mozilla.org/show_bug.cgi?id=1772989), [1773907](https://bugzilla.mozilla.org/show_bug.cgi?id=1773907), [1777207](https://bugzilla.mozilla.org/show_bug.cgi?id=1777207), [1777470](https://bugzilla.mozilla.org/show_bug.cgi?id=1777470), [1777893](https://bugzilla.mozilla.org/show_bug.cgi?id=1777893), [1778160](https://bugzilla.mozilla.org/show_bug.cgi?id=1778160), [1778167](https://bugzilla.mozilla.org/show_bug.cgi?id=1778167)
* Duplicates: [1778498](https://bugzilla.mozilla.org/show_bug.cgi?id=1778498)
* Can’t test/fixed based on the comments: [1778572](https://bugzilla.mozilla.org/show_bug.cgi?id=1778572)
* Somewhat reproducible: [1778597](https://bugzilla.mozilla.org/show_bug.cgi?id=1778597) (fails the download if not changing the file type)

**Comment by softvision-raul-bucata** [comment]
Investigated the following `closed` bugs for META [939897](https://bugzilla.mozilla.org/show_bug.cgi?id=939897):

`reproducible:`
* [811024](https://bugzilla.mozilla.org/show_bug.cgi?id=811024) based on [test case](https://bug811024.bmoattachments.org/attachment.cgi?id=827787) shows broken icons  in Chrome, but not in Firefox
* [1843228](https://bugzilla.mozilla.org/show_bug.cgi?id=1843228) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9343642) reproduces, as the layout is not the same (no overlapping elements though)
* [1089549](https://bugzilla.mozilla.org/show_bug.cgi?id=1089549) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=8511950) reproduces
* [1807406]( https://bugzilla.mozilla.org/show_bug.cgi?id=1807406)based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9309765) seems somehow reproducible
* [1315994](https://bugzilla.mozilla.org/show_bug.cgi?id=1315994) based [test case](https://bug1315994.bmoattachments.org/attachment.cgi?id=8808665) reproduces (missing elements in print-preview)

`can't test`:
* [969147](https://bugzilla.mozilla.org/show_bug.cgi?id=969147) no test cases, links available for QA testing
* [983427 ](https://bugzilla.mozilla.org/show_bug.cgi?id=983427) no test cases, links available for QA testing
* [1620490](https://bugzilla.mozilla.org/show_bug.cgi?id=1620490) no test cases, links available for QA testing
* [1633028](https://bugzilla.mozilla.org/show_bug.cgi?id=1633028) no test cases, links available for QA testing
* [1633031]( https://bugzilla.mozilla.org/show_bug.cgi?id=1633031) no test cases, links available for QA testing

`fixed`:
* [1622935](https://bugzilla.mozilla.org/show_bug.cgi?id=1622935) based on[test case]( https://bugzilla.mozilla.org/attachment.cgi?id=9146697) is fixed
* [1674774](https://bugzilla.mozilla.org/show_bug.cgi?id=1674774) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9185178) and test cases provided in [1673499](https://bugzilla.mozilla.org/show_bug.cgi?id=1673499 is fixed
* [1677339](https://bugzilla.mozilla.org/show_bug.cgi?id=1677339) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id)=9187875) is fixed
* [1695475](https://bugzilla.mozilla.org/show_bug.cgi?id=1695475) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9205926) is fixed
* [1739561](https://bugzilla.mozilla.org/show_bug.cgi?id=1739561) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9249372) and  [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9249497) is fixed
* [1744363](https://bugzilla.mozilla.org/show_bug.cgi?id=1744363) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=9260845) is fixed
* [1799530](https://bugzilla.mozilla.org/show_bug.cgi?id=1799530) is fixed based on all 4 test cases provided
* [1288734](https://bugzilla.mozilla.org/show_bug.cgi?id=1288734) based on the steps to reproduce is fixed
* [1303221](https://bugzilla.mozilla.org/show_bug.cgi?id=1303221) based on the steps to reproduce is fixed
* [1559961](https://bugzilla.mozilla.org/show_bug.cgi?id=1559961) based on the steps to reproduce is fixed
* [1565186](https://bugzilla.mozilla.org/show_bug.cgi?id=1565186) based on the steps to reproduc is fixed
* [1742024](https://bugzilla.mozilla.org/show_bug.cgi?id=1742024) based on the steps to reproduce is fixed
* [1814057](https://bugzilla.mozilla.org/show_bug.cgi?id=1814057) based on the steps to reproduce is fixed
* [856235](https://bugzilla.mozilla.org/show_bug.cgi?id=856235) based on [test case](https://bugzilla.mozilla.org/attachment.cgi?id=731384) is fixed (no crash observed)
* [1233125](https://bugzilla.mozilla.org/show_bug.cgi?id=1233125) is fixed based on comments
* [1569396](https://bugzilla.mozilla.org/show_bug.cgi?id=1569396) based on the steps to reproduce is fixed

`invalid:`
* [1344992](https://bugzilla.mozilla.org/show_bug.cgi?id=1344992) invalid
* [1885849](https://bugzilla.mozilla.org/show_bug.cgi?id=1885849) based on comments has been closed
* [1615274](https://bugzilla.mozilla.org/show_bug.cgi?id=1615274) can test: link no longer valid

**Comment by sv-calin** [comment]
Investigated the following `closed bugs` for META [1778322](https://bugzilla.mozilla.org/show_bug.cgi?id=1778322):

* Not reproducible: [1779128](https://bugzilla.mozilla.org/show_bug.cgi?id=1779128), [1855103](https://bugzilla.mozilla.org/show_bug.cgi?id=1855103) 
* Duplicates: [1779135](https://bugzilla.mozilla.org/show_bug.cgi?id=1779135), [1782366](https://bugzilla.mozilla.org/show_bug.cgi?id=1782366), [1778071](https://bugzilla.mozilla.org/show_bug.cgi?id=1778071) 
* Can’t test/fixed based on the comments: [1780451](https://bugzilla.mozilla.org/show_bug.cgi?id=1780451), [1810197](https://bugzilla.mozilla.org/show_bug.cgi?id=1810197) (download link no longer available)
* Incomplete: [1778925](https://bugzilla.mozilla.org/show_bug.cgi?id=1778925), [1779965](https://bugzilla.mozilla.org/show_bug.cgi?id=1779965), [1815089](https://bugzilla.mozilla.org/show_bug.cgi?id=1815089)

**Comment by softvision-raul-bucata** [comment]
All the testing has been done. Closing this as completed.
