### ISSUE TITLE
2024H1 - Start every week triaging UNCONFIRMED Bugzilla reports

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla/webcompat-team-okrs#285]
We will start every Monday by triaging no later than 4:30 PM Unconfirmed Bugzilla issues in our Webcompat component based on [link](https://bugzilla.mozilla.org/buglist.cgi?resolution=---&component=Site%20Reports&bug_status=UNCONFIRMED&query_format=advanced&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&product=Web%20Compatibility&list_id=17052029)

All the UNCONFIRMED issues will be triaged as follows (Release vs Nightly):

* **Reproducible issues**: change status to NEW and leave a relevant comment
* **Can't test** (lack of credentials, set-up, geolocation restrictions, etc): do not change status but leave a relevant comment on why testing can not be performed and ask for more info (if that is the case) + re-verify after details are received. Eventually we close it if we are not able to reproduce it and the user stops replying
* **Not reproducible issues**: change status to WORKSFORME or FIXED  and leave a relevant comment

  - if it's a relatively new report, ask the reporter for more info/new test case and leave it as UNCONFIRMED until relevant confirmation is received.

**Comment by softvision-raul-bucata** [comment]
**Week 23:**

* Issues triaged: 14

**Comment by sv-calin** [comment]
**Week 24:**

* Issues triaged: N/A

**Comment by sv-calin** [comment]
**Week 25:**

* Issues triaged: 2
