### ISSUE TITLE
2018-Q2 1.3 Reduce needsdiagnosis backlog to 0 issues (for non-anonymous issues)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#3]
Currently at 316: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3Aneedsdiagnosis+-author%3Awebcompat-bot+sort%3Acreated-desc+created%3A%3C%3D2018-04-01

**Comment by karlcow** [comment]
Currently as of today 283 non-anonymous issues in needsdiagnosis.

**Comment by karlcow** [comment]
These includes 99 issues opened by @softvision-sergiulogigan and @softvision-oana-arbuzov

**Comment by miketaylr** [comment]
253 open today.

**Comment by miketaylr** [comment]
191 / 316, but we need more participation from @wisniewskit and @denschub.

**Comment by karlcow** [comment]
Dedicating my time on needsdiagnosis 3 days a week (putting aside #1 with only 1 day a week). Given the current circumstances and San Francisco coming, we will probably not meet the target.

**Comment by miketaylr** [comment]
155 / 316

**Comment by miketaylr** [comment]
Changing to 70% confidence to reflect being ~72% done as of right now.

**Comment by miketaylr** [comment]
81 / 316

**Comment by miketaylr** [comment]
79 / 316

**Comment by miketaylr** [comment]
Currently at 76. Let's close with the quarter done. Thanks for the efforts everyone.

**Comment by miketaylr** [comment]
Score: 0.7

Of 316 issues, 76 were not diagnosed, meaning we got to ~78% of issues this quarter. This is really good, but we could have gotten to 100% by prioritizing this work a bit higher, even with the other demands (especially when blocked).
