### ISSUE TITLE
2018-Q4 2.2 - Instrument Report Site Issue telemetry / webcompat.com analytics

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#32]
Gather user insights & experimentation with better tracking.

* [x] fix google analytics
* [x] https://bugzilla.mozilla.org/show_bug.cgi?id=1514861
* [x] https://github.com/webcompat/webcompat-reporter-extensions/issues/140
* [x] https://github.com/webcompat/webcompat.com/issues/2748

**Comment by laghee** [comment]
Found a few FOSS alternatives that could be worth investigating:  [Open Web Analytics] (http://www.openwebanalytics.com/), [Matomo](https://matomo.org/) (formerly PIWIK), [Countly](https://count.ly/web-analytics), and the kinda ugly (or, more kindly, fashionably retro) [AWStats](http://www.awstats.org/).

**Comment by miketaylr** [comment]
No update here yet. Thanks @laghee!

**Comment by miketaylr** [comment]
Update: figured out this is not broken. :)

**Comment by miketaylr** [comment]
Update: not much to report yet.

**Comment by miketaylr** [comment]
> Update: not much to report yet.

Same.

**Comment by miketaylr** [comment]
Nothing different to report yet.

**Comment by miketaylr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1514861

**Comment by miketaylr** [comment]
Patch submitted: https://phabricator.services.mozilla.com/D14899

**Comment by miketaylr** [comment]
Status: done! Landed all the relevant patches, but we'll need a re-deploy on webcompat.com, which will happen in the new year.
