### ISSUE TITLE
2018-Q4 2.3 - Experiment with opt-in mechanism to get in touch with anonymous reporters

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#33]
Make anonymous reports more actionable by allow users to opt into feedback channels (possibly web push).

**Comment by miketaylr** [comment]
Update: in discussions with @karlcow about how to do this.

**Comment by karlcow** [comment]
no progress on this. on my side. busy with webcompat.com diagnosis. That said I want to try a simpler solution than web push.

**Comment by karlcow** [comment]
## 2018-10-31
Added context and questions for the project in 
https://github.com/webcompat/webcompat.com/issues/1822#issuecomment-434577219

After reading all the bricks involved in doing that, I don't think the project is doable in one quarter. 
We should have probably separated the pieces in a more nuclear form.  Basically there is design, server and client components.

**Comment by karlcow** [comment]
## 2018-11-15

Created a prototype for a low key form. Asked review by @miketaylr 
https://github.com/webcompat/webcompat.com/pull/2713
it needs tests and a bit or reorg.

* example of a bug report https://github.com/webcompat/webcompat-tests/issues/1720
* example of a possible abuse https://github.com/webcompat/webcompat-tests/issues/1721

**Comment by miketaylr** [comment]
Status: @karlcow has a goal to get this done before EOY.

**Comment by karlcow** [comment]
## 2018-12-18
 Basically done. A just rogue pull request where one test is failing in Chrome. I'm not sure why. 
I will create a new branch and recreate a PR to clean up the cache of circleci
