### ISSUE TITLE
2018-Q4 2.4 - Update webcompat reporter addons to send POST data

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#34]
Follow up maintenance work on server rewrite.

**Comment by wisniewskit** [comment]
Related: the in-tree reporter addon now sends reports as POST data as of [bz1451485](https://bugzilla.mozilla.org/show_bug.cgi?id=1451485). It required using an [experimental API](https://searchfox.org/mozilla-central/source/browser/extensions/webcompat-reporter/experimentalAPIs/tabExtras.js#96) to efficiently POST to the server as part of loading a tab.

But I'm not sure how easy it will be to do the same in the pure webextensions. I'm guessing that we will need to change [this code](https://github.com/webcompat/webcompat-reporter-extensions/blob/master/shared/base.js#L32) to load a webextension page which just waits for the background script to pass it data, and then writes out a form and submits it with method=POST. But there may be security restrictions which prevent this from working, so it might require some experimentation.

**Comment by miketaylr** [comment]
@miketaylr needs to file some bugs.

**Comment by laghee** [comment]
Discussed possibilities with @miketaylr, including suggestion above by @wisniewskit. Will take some research to get to the experimentation point and time is a little short this month, but I'll try to have a better idea on how to proceed toward the mid/end of November (or, worst case, will bring ideas to AllHands in December).

**Comment by laghee** [comment]
Haven't had time to look at this so far, but will be prepared to brainstorm in Orlando...
