### ISSUE TITLE
2018-Q4 2.6 - Land Web Extension Report Site Issue in Fennec

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#36]
Consistent extension code base.

Depends on landing web extension re-write.

https://bugzilla.mozilla.org/show_bug.cgi?id=1503402

**Comment by miketaylr** [comment]
@wisniewskit has been poking at this, and has a mostly working version with a few items to sort out. adding him as a co-owner.

**Comment by wisniewskit** [comment]
Still waiting on review. Will ping this week to try to get it across the finish line.

**Comment by wisniewskit** [comment]
This just landed.
