### ISSUE TITLE
2018-Q4 3.1 - Finish Enterprise site testing

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#37]
Finish QA on Enterprise top sites and services.

https://wiki.mozilla.org/Compatibility/Enterprise_Testing_Surveys

**Comment by adamopenweb** [comment]
Requires accounts. Sending follow ups this week to our contacts. Have a meeting internally for Workday.

**Comment by softvision-sergiulogigan** [comment]
16 October 2018

Office 365 - DONE
GSuite - DONE
Box - DONE
Sharepoint - In progress
Slack - In progress

Workday - Not started
ServiceNow - Not started
Salesforce - Not started
Concur - Not started
SuccessFactors - Not started
Jive - Not started
WebEx - Not started
ZScaler - Not started
Confluence - Not started
Cornerstone OnDemand - Not started

**Comment by softvision-sergiulogigan** [comment]
30 October 2018

Office 365 - DONE
GSuite - DONE
Box - DONE
Sharepoint - DONE
Slack - DONE
ServiceNow - DONE
Confluence - DONE

Workday - No access
Salesforce - No access
Concur - Not started
SuccessFactors - No account
Jive - No account
WebEx - No account
ZScaler - Not started
Cornerstone OnDemand - No account

**Comment by miketaylr** [comment]
Update re: accounts:

WebEx going to set up a test account for us, in the next few days.
Workday: blocked, but asking stpeter for more help.
Jive: asking stpeter for help.

Some of the others have turned out to be dead ends.

**Comment by softvision-oana-arbuzov** [comment]
WebEx (Modern/Clasic view) - In progress
Salesforce - In progress

**Comment by softvision-sergiulogigan** [comment]
27 November 2018

WebEx (Modern/Classic view) - In progress (80%)
Salesforce - In progress (50%)

**Comment by softvision-sergiulogigan** [comment]
29 November 2018

Salesforce - DONE

**Comment by softvision-oana-arbuzov** [comment]
4 December 2018

WebEx - DONE

**Comment by miketaylr** [comment]
Orlando update: we met with the Enterprise folks and they were very pleased with the results so far.
