### ISSUE TITLE
2018-Q4 3.2 - Diagnose Enterprise QA issues

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#38]
Follow up on [Enterprise QA with diagnosis](https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+milestone%3Aneedsdiagnosis+label%3Atype-enterprise-survey) and [outreach](https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+label%3Atype-enterprise-survey+milestone%3Acontactready).

**Comment by karlcow** [comment]
# 2018-11-16
So a status about this
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=+is%3Aissue+label%3Atype-enterprise-survey+

There are [64 issues](https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=+is%3Aissue+label%3Atype-enterprise-survey+)

On these 64 issues
* 41 open
* 23 closed

in the 41 open ones, 23 remained to be diagnosed. The rest has been already dealt with.

So 64% has already been done. Pushing the label.

**Comment by karlcow** [comment]
## 2018-11-16

well… now 17 remained to be diagnosed and I'm pretty sure 5 of them are either wontfix or invalid.

17 -> 73%

**Comment by karlcow** [comment]
## 2018-11-19
We are almost done.

I asked for help to @wisniewskit on two issues
* https://github.com/webcompat/web-bugs/issues/19240
* https://github.com/webcompat/web-bugs/issues/18621

One issue is blocked because I need to coordinate with oana and sergiu.

I also realized that 4 of these issues are… chrome only. So should not be counted part of the OKR.

2 issues on 60 firefox issues We are at 96% done.

**Comment by karlcow** [comment]
2018-11-27 There is a moving dependency around this.
It depends on https://github.com/mozilla/webcompat-team-okrs/issues/37#issuecomment-441616997
So each time, @softvision-oana-arbuzov @softvision-sergiulogigan add to the pile. The percentage is changing ;)

**Comment by karlcow** [comment]
## 2018-12-11
I plan to work on diagnosis in the next couple of days.

**Comment by karlcow** [comment]
## 2018-12-12
This morning
* [6 open issues](https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+label%3Atype-enterprise-survey+milestone%3Aneedsdiagnosis) on a total of 68 issues. 91% done. Working on this today.

Later
* https://github.com/webcompat/web-bugs/issues/19167 should be ignored. It seems to be a Chrome issue. 
* https://github.com/webcompat/web-bugs/issues/19089 should be ignored. it seems to be a Chrome issue.

So let's revise the numbers: 68 - 2 chrome issues 66. And one issue left where I pinged @wisniewskit to help. 

1/66 ~ 99% done. Yoohoo!

**Comment by karlcow** [comment]
## 2018-12-18
Probably done. Only one remaining bug to diagnose by @wisniewskit

**Comment by karlcow** [comment]
[Remaining issue](https://github.com/webcompat/web-bugs/issues/19240)

**Comment by miketaylr** [comment]
And we're done now. 🎉
