### ISSUE TITLE
2018-Q2 1.4 Re-triage all existing non-anonymous needsdiagnosis issues.

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#4]
Currently at 316: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3Aneedsdiagnosis+-author%3Awebcompat-bot+sort%3Acreated-desc+

**Comment by miketaylr** [comment]
(sergiu and oana to own)

**Comment by miketaylr** [comment]
Going to create a label to track the work, in progress.

Decided that we won't comment on issues with a comment in the 30 days (presumably they're still active).

We already re-triaged our own issues.

**Comment by softvision-sergiulogigan** [comment]
Probably a good idea to write down progress.
April 30 - 56 remaining issues to re-triage.

**Comment by softvision-sergiulogigan** [comment]
May 9 - 0 issues remining.

![image](https://user-images.githubusercontent.com/16573771/39802121-e43c8ed4-5375-11e8-830c-aed960913615.png)

**Comment by miketaylr** [comment]
Let's close this out, thanks sergiu and oana!

**Comment by miketaylr** [comment]
Score 1.0

Great work as always by Sergiu and Oana.
