### ISSUE TITLE
2018-Q4 4.1 - Establish regular site patch deploy process

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#40]
Establish a process with release management for off-train intervention deployment (GoFaster)

**Comment by adamopenweb** [comment]
Waiting for the web-extension to land before bugging Dennis too much.

**Comment by adamopenweb** [comment]
Webextension work is done. Started talking with Dennis about requirements, process and potential issues.

**Comment by adamopenweb** [comment]
Met with the QA team, received good feedback. Next step is to book kickoff meeting for single site patch. Also need to draft project plan.

**Comment by denschub** [comment]
Cross-referencing [bug 1515005](https://bugzilla.mozilla.org/show_bug.cgi?id=1515005), which I filed to track the completion of this work on Bugzilla, so people who want to get rid of the old update mechanism have a bug to depend on. :)
