### ISSUE TITLE
2018-Q4 4.2 - Fix 25 site issues using webcompat system addon

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#41]
Use the new super power to make a better web for Firefox. And get it in front of our release users.

**Comment by denschub** [comment]
17 site patches are built and merged into the GitHub repo. [This internal spreadsheet](https://docs.google.com/spreadsheets/d/1U17PnlB0lN6dtmuz2HpUI8ANUYMh-aaeyz22qGu5faY/edit?usp=sharing) keeps track of both potential candidates and patches already built. We need more candidates (and someone looking for them).

As for getting them released, @adamopenweb is still working on it, but we've had some trouble getting meetings scheduled.

**Comment by karlcow** [comment]
* https://bugzilla.mozilla.org/show_bug.cgi?id=1508516

**Comment by karlcow** [comment]
* https://bugzilla.mozilla.org/show_bug.cgi?id=1508564

**Comment by denschub** [comment]
With https://github.com/mozilla/webcompat-addon/pull/39 merged, we are now at *23* overrides in the repo.

**Comment by miketaylr** [comment]
Update: we made it to 24, and @denschub pinged people for review.

**Comment by denschub** [comment]
All interventions landed in [bug 1512907](https://bugzilla.mozilla.org/show_bug.cgi?id=1512907) and didn't get backed out, so this is looking good. As we defined the rollout-to-release process as a separate step, this is done. 🎉
