### ISSUE TITLE
2018-Q4 4.3 - Land Nightly-only about:compat page to list current site patches / UA overrides

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#42]
Inform users on active webcompat system patches.

**Comment by miketaylr** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1488845.

**Comment by wisniewskit** [comment]
No progress yet.

**Comment by wisniewskit** [comment]
Still no progress. Will chat with Mike about this ASAP to see if we have any concrete ideas yet, or should at least do some research.

**Comment by miketaylr** [comment]
Hoping to have conversations in Orlando around this feature with Product, and the team.

**Comment by miketaylr** [comment]
We're tackling this in Q12019.
