### ISSUE TITLE
2018-Q4 4.4 - Convert system addon into a webextension

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#43]
Maintenance on system addon to keep the extension alive.

**Comment by denschub** [comment]
Desktop: Still fighting against leakcheck tests, pinging people to get help.

Mobile: Mochitests still failing, nobody understands why, yet.

**Comment by denschub** [comment]
This is... **done**.

The update for desktop was done in [bug 1498278](https://bugzilla.mozilla.org/show_bug.cgi?id=1498278), the Fennec part landed in [bug 1451484](https://bugzilla.mozilla.org/show_bug.cgi?id=1451484).
