### ISSUE TITLE
2018-Q4 5.1 - Tinker Tester for Chrome

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#44]
Make tinker tester compatible with Chrome

**Comment by wisniewskit** [comment]
Some feasibility investigations were done over the past couple of weeks, but I haven't had time to actually code anything.

**Comment by wisniewskit** [comment]
I did some work converting over to Chrome, but the results aren't conclusive yet. It seems likely that a Chrome-specific version won't be able to load before all scripts on a page as early as the Firefox version, which could cause hiccups on sites using inline script tags.

**Comment by wisniewskit** [comment]
Progress is good, and I now have a version of the addon about half done which supports both Chrome and Firefox with essentially the same codebase (just different methods for gluing things together).

I also have a pending webextension API proposal for these kinds of addons, which I will discuss at the upcoming All-Hands, and should help even more.

**Comment by wisniewskit** [comment]
Progress is unfortunately about where it was last time, as I explored making an experimental API (so we had a more solid proposal ready for the Mozilla All-Hands) but it hasn't become solid enough yet for my liking. I'm going to refocus on just getting the Chrome port done now instead.

**Comment by wisniewskit** [comment]
Other priorities kept this from being completed in the last sprint, so it's still unclear if I can finish the port this quarter (but it's close!)

**Comment by wisniewskit** [comment]
Due to a sneak-attack bug with the webcompat reporter, I've been delayed and doubt I'll finish this before the quarter is done.
