### ISSUE TITLE
2018-Q4 5.2 - Draft a more polished Tinker Tester UI/UX concept

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#45]
Make it more useful for other people, and easier to use.

**Comment by miketaylr** [comment]
@denschub I think we're defining the scope of this as a proposal, is that correct? So the deliverable will likely be some form of document.

**Comment by denschub** [comment]
I finished everything I wanted to, and will export them as a usable file format (from Sketch to .. PDF or so) and put them in a slide deck on the plane to Orlando, so I have something to do, and we have something to look at. :)
