### ISSUE TITLE
2018-Q4 5.4 - Modularize tinker tester code for external users

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#47]
Make the extension useful for other teams.

**Comment by wisniewskit** [comment]
No chance to get to this yet, but note that it will probably overlap with OKR 5.1.

**Comment by wisniewskit** [comment]
Still no progress, but other OKRs are now winding down so the priority here may be bumped up.

**Comment by wisniewskit** [comment]
Quick update: there is still little progress here, but now I finally have a solid idea of how to port this over to Chrome, so I'm able to finally start consdering how to cleanly modularize the code.

**Comment by wisniewskit** [comment]
As hoped, I'm now modularizing the addon as I rewrite it for Chrome and Firefox (in #44). Hopefully the most useful parts for other team can be factored out this quarter, but I'm still not 100% sure yet.

**Comment by wisniewskit** [comment]
It's unclear how much of this will actually be done as I make the Chrome port, so I'm pretty sure that it won't be done this quarter.

**Comment by miketaylr** [comment]
(Going to score this as 0.3, because some work did happen.)
