### ISSUE TITLE
2019-Q1 1.3 - Ship a prototype dashboard showing user-facing webcompat metric for Top 200 Mobile and Desktop Sites 

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#49]
See [draft proposal](https://docs.google.com/document/d/1cRgFNqmTpv3Ce0Dv9Z8oPy5fmiqnJhxMOiTOTPyWkmU/edit). 

It's possible this results in an effective dupe of https://github.com/mozilla/webcompat-team-okrs/issues/67, but that's OK.

**Comment by magsout** [comment]
I can help if needed to display the data

**Comment by miketaylr** [comment]
Experimenting with ideas this week.

**Comment by miketaylr** [comment]
Draft write-up with links here: https://docs.google.com/document/d/1U88cs6pVU08Heunx4_6SjHEkIAvMuGYC2tegG6Tm0v0/edit#heading=h.km363ecwck1s

I think we can call this one done 🎉
