### ISSUE TITLE
2018-Q2 1.5 Add contextual metadata to new in-product webcompat.com bug reports

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#5]
- [ ] Console Errors: [Bug 1453493](https://bugzilla.mozilla.org/show_bug.cgi?id=1453493)
- [x]  Tracking protection status: [Bug 1399987](https://bugzilla.mozilla.org/show_bug.cgi?id=1399987)
- - [x] add label for tracking protection list type https://github.com/webcompat/webcompat.com/issues/2434
- [x]  Include `navigator.buildID` and update channel: 
- - [x] https://github.com/webcompat/webcompat.com/issues/2047 
- - [x] [Bug 1399985](https://bugzilla.mozilla.org/show_bug.cgi?id=1399985)
- [x]  Put `details` content in hidden input: https://github.com/webcompat/webcompat.com/issues/2042

**Comment by miketaylr** [comment]
> Put details content in hidden input: webcompat/webcompat.com#2042

PR @ https://github.com/webcompat/webcompat.com/pull/2395

**Comment by miketaylr** [comment]
@wisniewskit to investigate console errors. Unknown how difficult it will be. Details and buildID/update channel stuff in progress.

**Comment by miketaylr** [comment]
TP stuff in review, @wisniewskit has some WIP code for console logging (with an open question about inner window IDs). Looking good.

**Comment by wisniewskit** [comment]
Unfortunately I haven't had time to investigate the aformentioned window ID issues for the console error portion of this OKR during this sprint, so I can't provide any meaningful update on that.

**Comment by miketaylr** [comment]
Going to leave at 80% confidence, will be on the backburner for a ~2 weeks.

**Comment by wisniewskit** [comment]
Update on the console messages: I took another look at it, only to end up blocked on a needinfo. I'm not at all sure why the inner window IDs that I need aren't working, but once I have a clue on that I may be able to finish it.

**Comment by miketaylr** [comment]
Thanks for the update @wisniewskit, I'm going to lower confidence a little bit -- it seems like we might end up in "things not working as we expect them" territory.

**Comment by wisniewskit** [comment]
I managed to figure out the issue, and have submitted a patch to the addon for review.

**Comment by denschub** [comment]
Finished everything, except console errors. Got a review on our approach, but have to finish that. Also some issues with the labeling, but doable.

**Comment by miketaylr** [comment]
Let's go ahead and close -- there will be some follow up work in Q3 to ensure the console errors get sent to the form, but it depends on some infrastructure work on the webcompat.com backend.

**Comment by miketaylr** [comment]
Score: 0.85

We landed 6 out of 7 bugs listed in the OKR. The 7th received r+ but we realized it needs some backend changes on webcompat.com to support it. We’ll continue to prioritize the last one in Q3.
