### ISSUE TITLE
2019-Q1 3.3 - Implement and ship 4 UI improvement issues for Tinker Tester diagnosis addon

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#52]
Implement and ship the following issues: https://github.com/webcompat/tinker-tester-developer-spy/labels/q1-2019

**Comment by denschub** [comment]
Updated: I started digging into the current implementation, build some prototypes for architectural changes and started doing some planning. There will be some shareable progress at the next OKR checkup!
