### ISSUE TITLE
2019-Q1 2.2 - Land an `about:compat` page to display active sitepatches, and allow site authors to disable them.

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#53]
This should land in Nightly and ride to DevEdition. 

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1488845.

Amazing mockup:
<img width="924" alt="screen shot 2018-12-21 at 12 42 08 pm" src="https://user-images.githubusercontent.com/67283/50358105-d9eeb100-051d-11e9-85d3-6c4e132e873a.png">

We could probably do something similar to what is in `about:policies` for UI.

```
Needs a time estimate. 
```

### Requirements

* Desktop and Mobile users on Nightly (and then DevEdition) should be able to navigate to `about:compat` to see which UA overrides and interventions are enabled 
* Users should be able to disable them via `about:compat` (either globally, or individually)
* Ideally the content on this page is populated by the webcompat system addon 

### Next Steps

* [x] Experiment with implementation approach, and come up with a plan: can we register `about:` pages via a(n experimental) WebExtensions API? Do we hard-code a redirect to an add-on page from an about page? Can we inject a content script into an about page from an experimental API from a WebExtension?
* [ ] Once we have a plan, send an intent to implement to dev-platform
* [x] Write code, tests, land in Nightly
* [x] Send PI request
* [ ] Do everything else not listed here yet.

67 seems like a good target for this to land in Nightly.

**Comment by miketaylr** [comment]
Status update: we met, and discussed the goals of the thing.

**Comment by wisniewskit** [comment]
Status update: I have a working prototype pretty much ready, and now I'm figuring out the last bits of integrating it with our existing addon.

**Comment by wisniewskit** [comment]
Status update: I have a patch waiting for review/discussion in the bug. I suspect we will need changes to at least the copy and layout of the desktop page, along with any changes related to review feedback.

**Comment by wisniewskit** [comment]
Status update: I think I'm done with the first round of reviews. The l10n bits seem close, the rest I'm not as sure about but I'm not seeing any blockers other than reviews.

**Comment by wisniewskit** [comment]
Status update: about:compat just landed, so hopefully it sticks and we're done here.

**Comment by miketaylr** [comment]
Note: submitted a PI request for this to ride the trains in 68.

**Comment by miketaylr** [comment]
> This should land in Nightly and ride to DevEdition.

edit: This should land in Nightly in this quarter. We would like it to ride to release.
