### ISSUE TITLE
2019-Q1 3.1 - Identify and log presence of Fastclick library (and version) at report-time for Mobile bug reports

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#58]
* time estimate: 2 months

**Comment by karlcow** [comment]
No progress since last time, but likely to work on it this week or next week.

**Comment by karlcow** [comment]
no progress there yet.

**Comment by karlcow** [comment]
Working on this tomorrow. I need to discuss with @wisniewskit on how to detect something on the reporter side.

**Comment by karlcow** [comment]
@wisniewskit ok thomas, this seems to work on site I have tried. tell me if it makes sense and if it can be easily incorporated to the Report Site Issue button feature.
https://gist.github.com/karlcow/90cae56b651e0561b1a038262c01b95b

the goal is to add a keyword in the form, that we can parse on webcompat.com side and do whatever we want with it. (extra_labels)

It also shows in the console with 
<img width="392" alt="Capture d’écran 2019-03-13 à 15 58 07" src="https://user-images.githubusercontent.com/505230/54259415-f111cd80-4565-11e9-84d9-098bad5b7316.png">

**Comment by karlcow** [comment]
I also realized something about fastClick. They do have a notNeeded function
https://github.com/ftlabs/fastclick/blob/7e400d112947c7edfcc377d9ef6b0057a7f20bd4/lib/fastclick.js#L796-L806

which is testing user agents, there is a case for Firefox.

**Comment by karlcow** [comment]
```js
		// Firefox version - zero for other browsers
		firefoxVersion = +(/Firefox\/([0-9]+)/.exec(navigator.userAgent) || [,0])[1];

		if (firefoxVersion >= 27) {
			// Firefox 27+ does not have tap delay if the content is not zoomable - https://bugzilla.mozilla.org/show_bug.cgi?id=922896

			metaViewport = document.querySelector('meta[name=viewport]');
			if (metaViewport && (metaViewport.content.indexOf('user-scalable=no') !== -1 || document.documentElement.scrollWidth <= window.outerWidth)) {
				return true;
			}
}
```

**Comment by wisniewskit** [comment]
Yes, I think we can add that to the reporter's `browser.tabExtras.getWebcompatInfo` [experimental API](https://searchfox.org/mozilla-central/source/browser/extensions/webcompat-reporter/experimentalAPIs/tabExtras.js#11),  as part of its `getInfoFrameScript` function. The code probably would not need to change too much, in fact.

**Comment by miketaylr** [comment]
> They do have a notNeeded function

Good find.

`FastClick.notNeeded`, if it's accessible via the global, we could write interventions to disable it for sites that were important enough.

**Comment by karlcow** [comment]
@wisniewskit deployed The FastClick detection script into the "Report Site Issue" https://bugzilla.mozilla.org/show_bug.cgi?id=1535479
This should be available soon in Firefox Nightly.

I opened for the server side. 
https://github.com/webcompat/webcompat.com/issues/2823

We are almost done.

**Comment by karlcow** [comment]
Once this is reviewed. We are done.
https://github.com/webcompat/webcompat.com/pull/2824
