### ISSUE TITLE
2018-Q2 1.6 "Pre-triage with the crowd" experiment

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#6]
We believe there might be an opportunity for us to increase contributions from non-technical (or /rather, non-expert) volunteers in a way that is rewarding for them, and helps us to handle a greater number of issues. It's our hope that by doing this, our triagers can more readily make decisions about bug cycle states and our diagnosers can spend less time on non-expert activities.

Some documents:

* [Pre-triage Guidelines](https://docs.google.com/document/d/1nTfBYxX7-_OQ4uOcfb_Rcb2Mhww8MJuwwtgWpcd0l70/edit)
* [Issue quality score](https://docs.google.com/document/d/17An0NXkiYUV3Dl1iHq0n0duHdRKJwCW0l2txSH0kRN8/edit)
* [Pre-triage Experiment progress document](https://docs.google.com/spreadsheets/d/1p6lIt74SFqSkf8UmRfQLYlDLwHk_MCABOsY7INDR7W0/edit?usp=sharing)

- [x] Write document explaining experiment and goals
- [x] Develop "issue quality" metric
- [x] Run experiment rounds with volunteers
- [x] Hold team discussion in San Francisco All Hands
- [x] Write up findings and recommendations
- [x] File bugs for follow up work (if any)

cc @rosanardila

**Comment by miketaylr** [comment]
(sergiu and oana)

**Comment by softvision-oana-arbuzov** [comment]
Pre-triage Experiment progress document [link](https://docs.google.com/spreadsheets/d/1p6lIt74SFqSkf8UmRfQLYlDLwHk_MCABOsY7INDR7W0/edit?usp=sharing)

**Comment by miketaylr** [comment]
Round results.

Round 1: 26.49%
Round 2: 21.09%
Round 3: 15.65%
Round 4: 8.07%

**Comment by miketaylr** [comment]
Latest update:

> I am sending this later this week! 

So, it seems like we can probably run this after all hands.

**Comment by softvision-oana-arbuzov** [comment]
This part is done and the Experiment was a success. We can move forward with it and involve more contributors. 
There are no issues to be logged.

Recommendations: The next step will be to run the Experiment with more people from the community (Christos Bacharakis is working on gathering a list of people to participate).

**Comment by softvision-oana-arbuzov** [comment]
@miketaylr could you add check-marks for:
- [ ] - Write up findings and recommendations
- [ ] - File bugs for follow up work (if any)

**Comment by miketaylr** [comment]
@softvision-oana-arbuzov done!

(I also re-pinged about getting you and sergiu added to the @mozilla github org today)

**Comment by softvision-oana-arbuzov** [comment]
@miketaylr thanks.

**Comment by denschub** [comment]
From the OKR checkin: Still waiting for feedback, so no update. Did a brainstorming session with Rosana, but also waiting for more material.

**Comment by miketaylr** [comment]
Let's go ahead and close. We'll continue work on this in Q3.

**Comment by miketaylr** [comment]
Score: 0.7

We were blocked on a final exercise with more volunteers, but everything else points to this being a useful thing to follow up with in Q3.
