### ISSUE TITLE
2019-Q1 2.1 - Diagnose 10 Marfeel framework bugs and produce report with findings.

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#63]
* [ ] [type-marfeel](https://github.com/webcompat/web-bugs/labels/type-marfeel-analysis)
* [ ] [Bug 1147352](https://bugzilla.mozilla.org/show_bug.cgi?id=1147352)

```
* time estimate: 2 months
```

**Comment by miketaylr** [comment]
Update: 9 / 10 bugs to go.

**Comment by wisniewskit** [comment]
Update: still 9 / 10 to go.

**Comment by miketaylr** [comment]
@karlcow closed some of the bugs recently because the issue as reported does not exist on the sites anymore. But the issues still exist in Marfeel.

**Comment by wisniewskit** [comment]
Status update: no new progress.

**Comment by wisniewskit** [comment]
Status update: no updates yet, but now that about:compat has landed, the hope is that I'll be free to focus on this.

**Comment by wisniewskit** [comment]
Status update: was stuck on diagnosis duty, didn't find the time to dig into these yet.

**Comment by wisniewskit** [comment]
Still no real progress, was stuck on other things.
