### ISSUE TITLE
2019-Q1 1.2 - Ship a prototype dashboard showing Platform Gap metric for CSS and DOM

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#66]
* time estimate: 2 months

Things we want to do:
* WPT: “for the intersection of enabled tests, show which tests pass in Chrome or Safari but not Firefox” 

Things we need to do:
* Find the intersection of Blink IDL methods that have use counter data, and Firefox IDL methods, compute a gap score from that.
    * Figure out how to normalize the differences in Confluence data between Firefox and Blink
* Find the intersection of CSS properties between Blink and Gecko, where counter data exists, come up with a score
* See if we can come up with something interesting for CSS values from the Bing data, and if that’s worth pursuing.
* Investigate the “dark gap” areas and decide if it’s worth the effort there to come up with something.

**Comment by jgraham** [comment]
The "want" item here at least somewhat overlaps something I'm working on. My goal is to get information about interop problems in front of engineers so they are able to triage problems efficiently. The primary way of doing that is to develop a UI which shows cases where we don't match Chrome / Safari and which allows annotating results with bugs (and filtering by annotation). So the work in progress I have looks like this (link will expire at some point, but basically it's a per-bug-component list of Firefox-specific test failures):

<img src="https://screenshotscdn.firefoxusercontent.com/images/24423139-69cc-4ad5-b2a6-60538a5151b4.png">

**Comment by miketaylr** [comment]
Update: still in progress. Working on cleaning up some CSS data now.

**Comment by miketaylr** [comment]
https://docs.google.com/spreadsheets/d/1z7vwzL4fmvSd8pvFpwf-o5_s1HaRN0ci5UFatnW9CaE/edit#gid=1980197261

**Comment by miketaylr** [comment]
Update: still working on the CSS side of things. Tim Smith is working on getting some historical values.

**Comment by miketaylr** [comment]
Working on a summary here: https://docs.google.com/document/d/1NUT7payR3FTN3xykVjH0w9KqeeCsRhZ-u6ZjWH23wTs/edit#
