### ISSUE TITLE
2019-Q1 1.1 - Evaluate compatibility for Top 200(ish) sites in "Tier 1 Report Card" report twice in Q1

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#67]
<s>We're experimenting with this Tier 1 Report Card idea over at: https://docs.google.com/spreadsheets/d/148lJgt2qMUDk5LN3PcNMhaEEMS-2KQtwydZw3VuD51Q/edit#gid=0. </s>

Current Top Sites Report Card Prototype: [google doc link (ping mike if you want access)](https://docs.google.com/spreadsheets/d/1lSbM-gPtyyuUf_gO3GGrZKfZ_FP50XZ6N9xmNlouqpU/edit#gid=63787018)

* [x] Capture measurements once
* [x] Capture measurements again (at least a month later) to understand change over time

### Things we need to accomplish:

* [x] Write a script to generate stable (predictable) URIs for Top 200 sites: [Bug 1520538](https://bugzilla.mozilla.org/show_bug.cgi?id=1520538): https://github.com/mozilla/webcompat-bugcount-report-generator
* [x] For each site, evaluate if it receives the same desktop and mobile experience as Chrome Mobile: 1 if yes, 0 if no.
* [x] If obvious, note "Features missing in Firefox"

We can ignore duplicate bugs for now.

We need to do this work for all the sites where we have data, from the list. When this is done, we can consider and plan exploratory testing of top sites with zero bug reports. If we encounter obvious new bugs, we should file them!

And then we're going to do it again before the end of the quarter.

Top 200 sites (actually ~244): [spreadsheet here](https://docs.google.com/spreadsheets/d/1lSbM-gPtyyuUf_gO3GGrZKfZ_FP50XZ6N9xmNlouqpU/edit#gid=63787018). It's possible we remove some of these sites from the list after we do this once.

**Comment by softvision-sergiulogigan** [comment]
January 29 update:

55/230 websites tested
25 new issues found

**Comment by softvision-sergiulogigan** [comment]
February 12 update:

186/230 websites found
62 issues found

**Comment by softvision-sergiulogigan** [comment]
February 15 update:

230/230 websites tested
75 total issues found

1st pass-through is completed. It took 19 working days.
We will start the next pass-through on the 4th of March.

**Comment by softvision-sergiulogigan** [comment]
March 12 update:

2nd run
105/230 websites tested
22 issues found

**Comment by softvision-sergiulogigan** [comment]
March 25 update:

2nd run
230/230 websites tested
38 total issues found

2nd pass-through is completed. It took 16 working days, approximately 4 man hours per day.
