### ISSUE TITLE
2019-Q1 2.3 - Ship interventions (site patches) to entire Firefox population (Release, Beta, Nightly) via gofaster

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#69]
Follow up work from https://github.com/mozilla/webcompat-team-okrs/issues/41.

We have 24 in Nightly already.

**Comment by adamopenweb** [comment]
Documented a plan for this. Reaching out to RyanVM to kick off the process.
https://docs.google.com/document/d/1PIRGJrqrQ9ngsLrSdf6Qz9PU4IBkMgW8jV7xuqkHRb8/edit?usp=sharing

**Comment by adamopenweb** [comment]
Haven't heard back from Ryan as of yet, sent a follow up message.

**Comment by adamopenweb** [comment]
Held kick off meeting on 2/8/2019.

- Adjusted plan slightly to only ship urgent patches through GoFaster mechanism, lower priority patches can ride the trains
- Release and QA are on-board with our plan
- Dennis[ added two patches](https://github.com/mozilla/webcompat-addon/pull/44) for an initial test
- Meeting scheduled for 2/12/2019 to discuss complications of add-on versions

**Comment by miketaylr** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1527352 for our test interventions that will be shipped to release.

**Comment by adamopenweb** [comment]
Update:
- Patches were approved by QA
- Held a meeting with Ritu and mythmon to discuss shipping to release options
- Received approval to ship our test patches to 100% release population
- Sent Intent to Ship email, waiting for approval

**Comment by denschub** [comment]
Rollout happened in [bug 1527352](https://bugzilla.mozilla.org/show_bug.cgi?id=1527352), landing the patches in tree happened in [bug 1532346](https://bugzilla.mozilla.org/show_bug.cgi?id=1532346), sooo this is done! 🎉

**Comment by miketaylr** [comment]
Note: I want to investigate if Balrog -> Fennec actually works. It got QA signoff, but I never saw the update.
