### ISSUE TITLE
2019-Q1 2.4 Ship 1 site patch to fix a -webkit-scrollbar site bug, shimmed on top of CSS Scrollbars.

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#70]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1432935#c6 and https://github.com/mozilla/webcompat-addon/pull/33

This should also help us hit our goal in https://github.com/mozilla/webcompat-team-okrs/issues/69.

**Comment by denschub** [comment]
Update: The Code by Xidorn *is* already for the WebExtension, so my mind played me a trick here. It seems to be working for the case mentioned in the bug (#12356), but not for others, so we'd have to define what exactly we want to achieve (what sites to target and/or what kind of errors to address).

**Comment by denschub** [comment]
Update: No new progress in the last 2 weeks, because of other GoFaster-related work, and diagnosis.

**Comment by denschub** [comment]
Update: Rebased and slighly modified the code and added some generic documentation in https://github.com/mozilla/webcompat-addon/pull/45.

**Comment by denschub** [comment]
To avoid having unnecessary trouble with merge conflicts, let's pause working on this until both our prototype-rollout-to-release is done, and the work on `about:compat` has been merged.

**Comment by miketaylr** [comment]
Not currently blocked anymore.

**Comment by denschub** [comment]
PR with two interventions landed in our repo: https://github.com/mozilla/webcompat-addon/pull/48, central landing will be attempted next week (it's code freeze time right now).

**Comment by denschub** [comment]
Done. Landed to the tree in [bug 1536767](https://bugzilla.mozilla.org/show_bug.cgi?id=1536767).

**Comment by miketaylr** [comment]
Scoring at 0.3 because this turned out to be a lot simpler than we anticipated. :)

(that's a good thing)

**Comment by miketaylr** [comment]
> Scoring at 0.3 because this turned out to be a lot simpler than we anticipated. :)

actually no, let's score this as 0.7. 🎉
