### ISSUE TITLE
2019Q2 - 1.3 Create a regular process to verify sitewait bugs

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#76]
<s>We'll continue measuring site compat index (#49) into Q2, for Desktop and Mobile, by gathering known bug data monthly in Q2 (only once for Tier 1 status, at the end of the quarter).

Note, for the Tier 1 stuff, we want a lightweight process here. It should not take longer than a week (ideally).

This depends on #75.</s>

**Update!**
We want to verify sitewait bugs on a regular basis, and determine which ones we can close. Often sites will fix bugs after we contact them without any follow-up. Or sometimes sites are redesigned and the bug becomes invalid and can be closed.

I'd like us to start with severity-critical bugs[1], then move to severity-important[2]. This is roughly 200 bugs. If we can get to these by the end of the quarter, great! If not, let's focus on the critical bugs first.

[3] https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3Asitewait+label%3Aseverity-critical
[4] https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3Asitewait+label%3Aseverity-important

**Comment by softvision-sergiulogigan** [comment]
CC @cipriansv

**Comment by miketaylr** [comment]
TODO, for scraper:

* [ ] Stable links to duplicates on Bugzilla
* [ ] Tracking numbers weekly
* [ ] Split out desktop and mobile bugs
* [ ] Come up with a convention for excluding irrelevant bugs from the Fresh bugs list
* [ ] Come up with a convention to include bugs older than 1 year in the Fresh bugs list
* [ ] Consider how to represent valid webcompat issues from the “rest of web”
* [ ] Open webcompat bugs that may have been fixed but not verified yet
* [ ] Ensure we’re only capturing Firefox bugs from webcompat.com
* [ ] Include site rank into weighting

**Comment by miketaylr** [comment]
> Consider how to represent valid webcompat issues from the “rest of web”

@adamopenweb do you remember what we meant here? I may have forgotten. >_>

**Comment by adamopenweb** [comment]
The site compat index focuses on top sites. We weren't sure how this would be valuable but to include the other billion web bugs we get from non-top sites.

**Comment by miketaylr** [comment]
Please see the email to the compatibility mailing list to understand the edits here. Thanks!

**Comment by softvision-sergiulogigan** [comment]
June 11 update:
Sitewait - Critical
55/75 issues verified.
25 issues closed as Fixed.

**Comment by cipriansv** [comment]
June 25 update:

Sitewait - Critical
75/75 issues verified
28 issues closed as fixed

Sitewait - Important
124/124 issues verified
54 issues closed as fixed

Sitewait - Minor
42/67 issues verified - Will be done by the end of the week
23 issues closed as fixed so far

Sitewait - None (no severity label)
0/379 issues verified

**Comment by miketaylr** [comment]
I'm gonna move this to done, since we got to the importants.
