### ISSUE TITLE
2019Q2 - 2.1 Google Images Tier 1 QA

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#77]
* Perform Exploratory Mobile QA for Google images results while spoofing as Chrome Mobile
* Write up a report with list of bugs and possible next steps

Note: we'd like to time-box this to 3 days.

**Comment by softvision-sergiulogigan** [comment]
CC @cipriansv

**Comment by miketaylr** [comment]
TODO: Mike, can we get manual QA steps from Google for this property?

**Comment by miketaylr** [comment]
Probably related, https://github.com/webcompat/web-bugs/issues/29676

**Comment by softvision-sergiulogigan** [comment]
50% done.
Much results, many success.
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=sv%3B+gi

**Comment by softvision-sergiulogigan** [comment]
> TODO: Mike, can we get manual QA steps from Google for this property?

reping @miketaylr

**Comment by miketaylr** [comment]
> reping @miketaylr

@softvision-sergiulogigan the contact I had no longer works at Google (who gave us the earlier stuff), so I recommend we proceed without manual QA steps.

**Comment by softvision-oana-arbuzov** [comment]
100% done.

Results: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=sv%3B+gi

**Comment by miketaylr** [comment]
Thank you!
