### ISSUE TITLE
2019Q2 - 2.2 Bing QA

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#78]
Let's do some QA for bing.com, on GeckoView-powered mobile devices or tablets.

Similar to #77, this should also be time-boxed to <s>something like 1 week.</s> 1.5 days.

**Comment by softvision-sergiulogigan** [comment]
CC @cipriansv

**Comment by miketaylr** [comment]
Working on a test document, hoping to have it ready by tomorrow EOD so we could start on this at some point next week.

**Comment by miketaylr** [comment]
> Working on a test document, hoping to have it ready by tomorrow EOD so we could start on this at some point next week.

Update: we've requested devices be shipped to SoftVision, it turns out you can't just send stuff from amazon.com to Romania  -- I think they've already been ordered to the Berlin office, then will head over to Florin.

**Comment by miketaylr** [comment]
Update: Devices received and test plan sent to SoftVision crew.

**Comment by softvision-sergiulogigan** [comment]
Achievement unlocked!

We allocated half a day each for this activity, and came up with 21 issues logged, in total.

You can find them here: https://github.com/webcompat/web-bugs/labels/type-bing-interop

We also updated the document with our findings and tested areas: https://docs.google.com/document/d/1WZDtmmqq-XMMDHVnh50h_XJ38SAJxYJdFPgoClXWppA/edit#.

**Comment by softvision-sergiulogigan** [comment]
Also, here is @ksy36's comment on the differences of layouts:

`I believe the root cause of the issue is that the site is displaying a mobile version for Firefox on Android and a desktop version for Chrome for the same device. `

https://github.com/webcompat/web-bugs/issues/31619#issuecomment-494965485

**Comment by softvision-sergiulogigan** [comment]
The testing session is not valid, due to https://github.com/mozilla-mobile/fenix/issues/1848
We should retest this after the mentioned issue is fixed.

**Comment by miketaylr** [comment]
> The testing session is not valid, due to [mozilla-mobile/fenix#1848](https://github.com/mozilla-mobile/fenix/issues/1848)

I don't think I agree with that entirely! Y'all identified that an important site depends on that bug, which we really didn't know before. We can re-test at a later date though, agreed.
