### ISSUE TITLE
2019Q2 - 2.3 Mobile framework detection & tagging

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#79]
Just like #64, this KR covers figuring out detection of Mobify and Marfeel so we can understand how prevalent these sites are for our users.

**Comment by karlcow** [comment]
I can probably help  and work with @wisniewskit on this.

**Comment by karlcow** [comment]
## Marfeel 

This is mostly easy to detect. 

* Client side: https://bugzilla.mozilla.org/show_bug.cgi?id=1544358
* Server side: https://github.com/webcompat/webcompat.com/issues/2844

## Mobify

* Client side: https://bugzilla.mozilla.org/show_bug.cgi?id=1544359
* Server side: https://github.com/webcompat/webcompat.com/issues/2845

**Comment by karlcow** [comment]
Some preliminary thoughts on https://bugzilla.mozilla.org/show_bug.cgi?id=1544358#c1

**Comment by karlcow** [comment]
btw we could start tracking AMP

```
window.AMP
window.AMP_MODE
```

**Comment by karlcow** [comment]
## 2019-05-19
No specific progress here, but I think we have all the gears in place for activating this.

**Comment by wisniewskit** [comment]
@karlcow, are you sure that those are the variables we would use to track AMP? I'm seeing no such variables on AMP pages, though there is apparently [something related](https://www.oreilly.com/library/view/amp-building-accelerated/9781786467317/545cea4c-dc83-4855-91ae-fdfabd4bd70b.xhtml) called "Shadow AMP" that uses them?

**Comment by karlcow** [comment]
`AMP` not being part of the original issue. If there is doubt we can wait a bit we have a better assessment.

**Comment by karlcow** [comment]
I meant, we move forward without AMP. 😄

**Comment by wisniewskit** [comment]
That makes sense to me, but just to be precise: if we're happy only detecting "Shadow AMP", Ksenia and I can add that while we're writing a patch. I just wanted to be sure it was worth bothering, since I don't personally know of any live sites using `window.AMP`/`window.AMP_MODE`.

**Comment by karlcow** [comment]
>  I don't personally know of any live sites using `window.AMP`/`window.AMP_MODE`.

Many sites, I don't know if it's all sites. They usually do two things. 
They sport a variation of 

`Powered by AMP ⚡ HTML – Version 1905140117570`
and have `window.AMP`
Examples from 2019-05-23 to 2019-05-28: 
* https://www.wfsb.com/news/uconn-student-killed-in-mansfield-crash/article_914a5802-7dc0-11e9-a904-c73ee9014186.amp.html
* https://www.foxnews.com/entertainment/michael-d-cohen-transition-female-to-male.amp
* https://www.cbsnews.com/amp/news/trump-calls-tillerson-dumb-as-a-rock-over-claims-about-putin-meeting/

and so on. 
https://cdn.ampproject.org/v0.js

**Comment by miketaylr** [comment]
@ksy36  @wisniewskit did we end up tracking window.AMP here? or just mobify and marfeel

**Comment by karlcow** [comment]
just mobify and marfeel.

**Comment by miketaylr** [comment]
cool, thanks
