### ISSUE TITLE
2019Q2 - 3.1 Fix remaining -webkit-scrollbar issues via sitepatching

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#80]
Follow up to #70.

**Comment by denschub** [comment]
Worked on some patches last week, but got stopped by PTO. :)

**Comment by denschub** [comment]
New patches are basically ready to land, except for the Discord bug, which needs some more fine-tuning to fix a white line that appears...

**Comment by denschub** [comment]
Patches are done and working, waiting for Tom to merge the new changes to our repo.

**Comment by wisniewskit** [comment]
Sorry for the delay! I've just merged a roll-up patch in https://github.com/mozilla/webcompat-addon/pull/52, so the code matches what's currently in mozilla-central.

**Comment by denschub** [comment]
PR at https://github.com/mozilla/webcompat-addon/pull/53

**Comment by miketaylr** [comment]
landed on github, going to try to land this in m-c.
