### ISSUE TITLE
2019Q2 - 3.2 Explore integration of intervention capabilities in Fenix

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#81]
Note: There's a dependency on GeckoView web extensions capabilities here.

However, the point of this is to investigate what we need to ship this and write up a spec. Do we have all the WebExtension APIs we need? Do we need Balrog compatibility? Do we need something else?

**Comment by miketaylr** [comment]
Should have an update for the next meeting.

**Comment by denschub** [comment]
Snorp is investigating, I have an experimental Fenix build that can do UA overrides via our extension, but not much else. We will continue investigating that.

**Comment by denschub** [comment]
We have an idea, we have lots of APIs that should work, *and* we have a hack-session with some Fenix/Android Components folks scheduled for Whistler. :) Also, Tom did a lot of code investigation.

**Comment by denschub** [comment]
There isn't much to say here. The general feedback of everyone is "just do it". I've noted down a couple of things [here](https://docs.google.com/document/d/1pZiICD87B2MYAbY5vZNjAF-FyUcgPMs-cnLAGOKYxmo/edit?usp=sharing), and I assume this document will get updated in the future, but we have a very good idea of how to progress here. :)
