### ISSUE TITLE
2019Q2 - 3.3 Ship site patch to fix PDK5 library-powered video playback on mobile

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#82]
See https://github.com/mozilla/webcompat-addon/issues/43

**Comment by wisniewskit** [comment]
I have an in-progress patch for the reporter addon which seems to work fine, so I should be starting the review cycle on it soon.

**Comment by miketaylr** [comment]
This just landed, thanks @wisniewskit!
