### ISSUE TITLE
2019Q2 - 4.1 Python 3 compatibility

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#83]
webcompat.com master should be able to run by `python3`.

**Comment by karlcow** [comment]
The core of the work is currently done in 
* Pull Request https://github.com/webcompat/webcompat.com/pull/2825
* Issue https://github.com/webcompat/webcompat.com/issues/2348

Some peripheral issues have been fixed on the current master to prepare for this such as:

* https://github.com/webcompat/webcompat.com/issues/2828

This is also part of https://github.com/webcompat/webcompat.com/projects/4

**Comment by karlcow** [comment]
## 2019-05-14
The current python 3 branch is passing all the tests and I keep it in sync with master as much as possible.  We need to install Python 3 on staging. Waiting for a snapshot from Mike as a backup, before breaking everything. So we may expect turbulences on staging.

**Comment by miketaylr** [comment]
> Waiting for a snapshot from Mike as a backup

This is done.

**Comment by karlcow** [comment]
## 2019-06-10

Status:
* Python 3.7.1 is installed on staging
* nginx and uwsgi can work with python 3 (configuration files checked)
* source code is able to run on python 3 without issues.

I ran an instance of staging.webcompat.com with Python 3 code. 

So everything is able to run. 

I need to square the deployment file to see if we can basically deploy everything (2348/1 branch aka python3 /future master) from a local dev machine without failing anything.

The plan to switch the prod needs to be decided and coordinated later. 

Probably staging will become prod. 
prod will become the new staging and we can upgrade the systems. So we have a new shiny instance.

But as for this OKR:
> webcompat.com master should be able to run by python3.

we are almost done.

Need to coordinate with @miketaylr for the rest.

**Comment by miketaylr** [comment]
Really great work by @karlcow here. ❤️
