### ISSUE TITLE
2019Q3 - 1.3 Identify and associate Web Platform Tests for top 10 Webcompat tracked core Bugzilla bugs

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#87]
(Try to) Establish link between most common web compat issues and failing WPTs.

Let's keep track of how long it takes us, and if we find WPT tests, drop a link to them in a comment in the bug.

**Comment by miketaylr** [comment]
We can start with these bugs:

Webcompat P1: https://bugzilla.mozilla.org/buglist.cgi?list_id=14793970&o1=equals&v1=P1&f1=cf_webcompat_priority&resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced

Webcompat P2: https://bugzilla.mozilla.org/buglist.cgi?f1=cf_webcompat_priority&list_id=14793972&o1=equals&resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced&v1=P2

**Comment by miketaylr** [comment]
If there's no wpt, a whiteboard item of `[needs-wpt-?]` can be added.

**Comment by wisniewskit** [comment]
Quick status update: I've gone through the P1 and P2 webcompat bugs, and almost all of them lack what I would classify to be "good" WPT coverage. On the plus side, most of them do seem to have available test-cases in WebKit or Blink which should be portable:

| Priority | Bug | Summary | WPTs? | WebKit/Blink tests? | Notes |
| - | - | - | - | - | - |
| P1 | [1123938](https://bugzilla.mozilla.org/show_bug.cgi?id=1123938) | Viewport handling | no | yes | Mobile WPTs need to work first. |
| P1 | [981248](https://bugzilla.mozilla.org/show_bug.cgi?id=981248) | Broken input after type switch during focus+blur | no | no | I added a WPT patch to the bug. |
| P1 | [1248897](https://bugzilla.mozilla.org/show_bug.cgi?id=1248897) | SpeechRecognition | yes | yes | Test coverage seems limited in general. |
| P1 | [1498729](https://bugzilla.mozilla.org/show_bug.cgi?id=1498729) | meta-viewport changes ignored | no | no | | Mobile WPTs need to work first. |
| P1 | [1540158](https://bugzilla.mozilla.org/show_bug.cgi?id=1540158) | DOM level 3 KeyEvent.DOM_VK_* constants | no | no | |
| P1 | [1381071](https://bugzilla.mozilla.org/show_bug.cgi?id=1381071) | CSS Perf issue | N/A | | |
| P2 | [390936](https://bugzilla.mozilla.org/show_bug.cgi?id=390936) | CSS Zoom | no | yes | |
| P2 | [1403410](https://bugzilla.mozilla.org/show_bug.cgi?id=1403410) | Checkbox state bug | no | no? | Mobile WPTs need to work first. |
| P2 | [1455894](https://bugzilla.mozilla.org/show_bug.cgi?id=1455894) | Shadow DOM selections | no | yes? | |
| P2 | [970802](https://bugzilla.mozilla.org/show_bug.cgi?id=970802) | beforeinput event | yes | yes | existing WPT coverage may be limited. |
| P2 | [1470025](https://bugzilla.mozilla.org/show_bug.cgi?id=1470025) | default opacity on placeholder text | no | no? | |

I'll do another round on our P3 bugs next.

**Comment by wisniewskit** [comment]
No updates this cycle, but we're still on track.

**Comment by wisniewskit** [comment]
No updates this cycle either; still on track.

**Comment by wisniewskit** [comment]
No updates this cycle either; still on track.

**Comment by wisniewskit** [comment]
Still no updates; still as on track as before.
