### ISSUE TITLE
2019Q3 - 2.1 Bundle WebCompat System Addon (Web Extension) in Fenix

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#88]
Enable website interventions, resolving mobile compatibility issues, in Fenix.

**Comment by miketaylr** [comment]
Update: Dennis is going to take a first stab at this and see what sticks. 

@denschub can you write down a rough TODO list here?

**Comment by denschub** [comment]
Some progress: Got the addon sources included into an Android-Component and the build still works. Needs more work on getting the component included into Fenix.

**Comment by denschub** [comment]
It works! The Android-Component is practically done, integration in the Reference Browser is done, Fenix integration has some issues left to be worked out, but I expect a PR either at the end of this week, or next week.

<img width="500" alt="Screenshot 2019-08-13 at 15 52 44" src="https://user-images.githubusercontent.com/344777/63350387-9e7edd80-c35d-11e9-962f-84ee824e29cb.png">

**Comment by denschub** [comment]
Wrote some tests for our stuff, broke some tests while integrating our stuff as well. :) Fixed the A-C tests, now working on Fenix tests. "Final touches"

**Comment by denschub** [comment]
PR at https://github.com/mozilla-mobile/android-components/pull/4409, received some review feedback, which is already addressed.

**Comment by denschub** [comment]
aaaaaaand it's merged. Will follow-up with the Fenix PR tomorrow.

**Comment by denschub** [comment]
That's the PR for adding the feature into Fenix: https://github.com/mozilla-mobile/fenix/pull/5432

**Comment by pocmo** [comment]
@denschub Do we want to add this to Reference Browser too? :)

**Comment by denschub** [comment]
@pocmo I dunno, really. :) I added a note to the a-c PR:

> I used samples-browser as a test vehicle, but did not include that change in this PR. I don't know if you actually want this inside the sample browser, given the addon can and will change websites in a way that's maybe unexpected by developers. However, we as the webcompat team, would really like an easy test method for development and manual tests, so the sample browser would be somewhat convenient. What do you suggest here, should I add it to the sample-browser, keep testing with my local patch, or spin another sample that just loads the WebCompat feature?

We probably need it somewhere for easy testing, and I'd actually prefer having it in the android-components sample browser, just because it would simplify the testing process significantly, as you only have to checkout and build one repo. But the reference browser would be an option as well.

**Comment by pocmo** [comment]
Oh, yeah, definitely have it in the sample browser! What I like about having it in RB: It's in an app that updates over Google Play and it gets out to actual users (+ is always using the latest bleeding edge AC).

**Comment by denschub** [comment]
The Fenix PR is merged!

I'll follow-up with PRs that add the feature tot he sample browser and RB as well. Thanks for that, @pocmo! :)

**Comment by denschub** [comment]
I submitted PRs to add the component into

* the sample browsers: https://github.com/mozilla-mobile/android-components/pull/4513
* the reference browser: https://github.com/mozilla-mobile/reference-browser/pull/909
