### ISSUE TITLE
2018-Q2 2.2 Prototype an addon for diagnosing compat issues

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#9]
For this addon, the target audience is the current Mozilla webcompat team and community. Future releases may target more use cases that would be interesting for Mozilla or developers, depending on the success of this prototype.

https://github.com/wisniewskit/webCompatSiteDiagnosisHelper is the starting point for this (to be moved to webcompat org).

* [x] Gather and document difficult diagnosis use cases from webcompat team
* [x] Ship a functional prototype on AMO, based on Tom's addon
* [x] Write blog post and documentation
* [x] Giving lighting talk at SF 2018 All Hands (to team, or to larger audience)

**Comment by wisniewskit** [comment]
No updates during this past OKR sprint, though I should be working on it now, especially during the All-Hands.

**Comment by wisniewskit** [comment]
I'm currently soliciting feedback and discussing the add-on at the All-Hands (and gave the lightning talk). I'm aiming to come up with a roadmap and file issues next week. I'm still confident that I can complete the basic documentation and ship a minimally-usable version on AMO by the end of the quarter.

**Comment by denschub** [comment]
All left to be done is writing a blog post. @miketaylr Tom suggested to mark this as closed, because it's basically done, what do you think?

**Comment by wisniewskit** [comment]
Actually we'll mark it done once I've written a post and shipped on AMO, which should still be done by end-of-quarter if nothing comes up.

**Comment by wisniewskit** [comment]
This is essentially done now. The add-on is now [listed on AMO](https://addons.mozilla.org/en-US/firefox/addon/tinker-tester-developer-spy/) as an experimental one, and [the documentation](https://cdn.rawgit.com/webcompat/tinker-tester-developer-spy/master/docs/index.html) has gone live.

**Comment by miketaylr** [comment]
Score: 0.9

Tom got the addon shipped on AMO, gave a lightning talk, and documented everything. We decided to punt on a blog post for now.

https://addons.mozilla.org/en-US/firefox/addon/tinker-tester-developer-spy/
https://cdn.rawgit.com/webcompat/tinker-tester-developer-spy/master/docs/index.html
