### ISSUE TITLE
2019Q3 - 5.1 Explore private issue reporting for webcompat.com

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#93]
Determine requirements and constraints to allow for private bug reports and an option for users to provide their contact information in a secure and privacy preserving manner.

**Comment by miketaylr** [comment]
Status update: we plan on brainstorming this in Tokyo in September, and writing up our findings.

**Comment by karlcow** [comment]
@adamopenweb @miketaylr I have a couple of questions with regards to this.  Please respond in the comments here. So we can easily track it.

## FEATURE: allow for private bug reports

1. What is *private bug reports* and its goals?
2. What will *private bug reports* solve?
3. Who is the stakeholder of for the feature *private bug reports*?
4. In case *private bug reports* is deployed, what are the KPIs to verify with achieved the goals?

This should help with defining the perimeters of what we want to achieve. Constraints and Requirements should contain 

* Social impact 
* Timeline
* Development needs
* Resources needs
* Deployment plans in case we would want to move forward.
* Exit strategy in case of non-success if deployed.

The context here is to really understand to know if we could/should do it or not.

**Comment by karlcow** [comment]
# OKRs check / 2019-08-06

Here I need the feedback from @adamopenweb 
https://github.com/mozilla/webcompat-team-okrs/issues/93#issuecomment-516692574
@miketaylr was on PTO this week.

**Comment by miketaylr** [comment]
The plan was to explore the technical details in Tokyo, I think as long as we get answers by then (mid-September), we should be OK to come up with something here.

**Comment by karlcow** [comment]
# OKRs check / 2019-08-20

status quo. Need to re-ping @adamopenweb

**Comment by karlcow** [comment]
# OKRs check / 2019-09-01

@adamopenweb was not available lately. So this is at risk. We might be able to push this into 2019Q4 if we think it's necessary.

**Comment by adamopenweb** [comment]
@karlcow Truly sorry for the delay.

>    What is private bug reports and its goals?

We would like to understand the technical requirements (and challenges) to:
- Provide users a method of reporting non-public bugs to us through Webcompat.com
- Provide users a method of supplying an email address to be contacted about a bug without requiring a Github account

>What will private bug reports solve?

Non-public reports allows people or companies to submit reports with information they may deem too sensitive to have publicly available, but are comfortable sharing with Mozilla employees. This could be used to support other initiatives within Mozilla.

Accepting email addresses would allow a method of contact to websites that we can either not reproduce or that are not publicly available. 

>Who is the stakeholder of for the feature private bug reports?

Me and potentially other groups within Mozilla in the future tbd.

>In case private bug reports is deployed, what are the KPIs to verify with achieved the goals?

I'm reading this question as "what level of usage justifies that we invest our engineering time on these problems?" 

I don't have a sense of that as of yet. But the scope of this is determining what is required to support it, not the justification of doing so.

**Comment by karlcow** [comment]
Thanks a lot @adamopenweb for the context. 
The more I read it, the more it looks like it's a UI on top of bugzilla.mozilla.org, more than a private instance of github through webcompat.com.

The privacy of bugs is already possible on bugzilla, it looks like a lower hanging fruit. Maybe. 
Let's discuss with @miketaylr and @wisniewskit this week. Stay tuned! 📻

**Comment by miketaylr** [comment]
@miketaylr needs to write up our findings here.

**Comment by miketaylr** [comment]
Here are the minutes from our discussion (sorry, it's kinda confusing in parts).

High level overview: we see 2 paths forward, each with problems. Without a clear PRD, we can't go too deep on how to solve them. A rough estimate in terms of effort is 2 quarters (just engineering).

* For non-public bugs, it means re-architecture to support a private repo. But at the same time, Bugzilla already has a private system. If we were to do that, it feels like a better fit to be in Bugzilla since they're probably not compat bugs, but bugs for Mozilla (possibly, thinking of Enterprise support cases. But there could be some compat bugs with private details). There could be a UI, then instead of POST to GitHub, we POST to Bugzilla. It would take some time, but maybe less time than figuring out how to do private repos. 
* **Question**: do we need to require users to have a Bugzilla account? Bugzilla now allows GitHub oauth login. To investigate if that could be re-used (though it's not clear how the scopes map to bug filing privs).
* **Question**: Is this a bug reporting for a priviledged user (Enterprise customers?) - or intended to be for everyone?
* **Question**: why do we want this on webcompat.com? Are we ready to handle the consequences? Will we end up with alot of private issues reported that shouldn't be private (not a technical concern)? 
    - API to bugzilla.
        - A user can see his own private bugs, which seems like a MUST to be able to do this thing. (assuming we can make the github bugzilla auth thing work, that is, it's possible to login to bugzilla via github auth. can we get the right scope to file an issue on their behalf?)
    - web-bugs private. (requires another set of OAUTH keys)
* **Question** How would we implement this via a private GitHub repo?
        - If we just file issues into a private repo, this prevents users to be able to see anything, which kind of defeat the purpose of private bug reporting. The poster would not be able to see the bug. Technically difficult to find a workaround. We would have to require the user to input alternate contact info, but they could never see their own report.
        - One workaround would be to add each individual to the private repo, which would allow them to see all bugs (oops). And cost a billion dollars (something like 9USD per month, per person). not to mention legal fees for all the lawsuits. maybe 2 billion.
- **Conclusion**: there are challenges for either approach, but probably not impossible challenges. We would like a PRD to be able to further comment, as right now we're just guessing what would be required and how to workaround any limitations. Hard to guess how long either approach would take. If we had to, probably 2 quarters worth of work (throwing a coin into the air), once the problem and requirements are clearly defined.
