### ISSUE TITLE
2019Q3 - 5.2 Ship Python 3 migration to Production environment

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#94]
Future proof Webcompat.com code through shipping Python 3 updates.

**Comment by karlcow** [comment]
The plan is to 


# option A

* [ ] change the deployment script
* [ ] add configuration for  py3-prod on the current staging
* [ ] make sure staging / prod can run on parallel on the same instance
* [ ] merge the py3 branch into master
* [ ] deploy master on current staging in parallel to staging
* [ ] point the DNS to the new prod
* [ ] wait a bit and burn incense
* [ ] reconfigure the older instance (ex-prod) to make it modern.
* [ ] (option: switch back or DNS staging to it?)

# option B
* [ ] change the deployment script
* [ ] add configuration for  py27-prod on the current staging
* [ ] move py2.7-prod on the current instance of staging 
* [ ] point the prod DNS to staging
* [ ] wait a bit and burn incense
* [ ] reconfigure the older instance (ex-prod) to make it modern.
* [ ] deploy py3-prod on the modernized server
* [ ] point the prod DNS to new prod
* [ ] wait a bit and burn incense

**Comment by miketaylr** [comment]
after chatting with @karlcow, option 🅰️ seems pretty good!

**Comment by karlcow** [comment]
# OKRs check / 2019-08-06
I spent a chunk of my time related to this last week,  learning everything about Docker and associated issues. The idea was to see if it would make it easier to deploy python3 environment (and have preset dev environment for the project).

I gather plenty of notes that I will publish this week as a blog post.

If it was fruitful, it would be a C option. :)

staging is down. It's known. I'm in the process of configuring things a bit. :) Sorry about that.

**Comment by karlcow** [comment]
# OKRs check / 2019-08-20

* staging-server is all configured and the current staging.webcompat.com is running with python3
* the production configuration files are all set on staging-server
* The images of webcompat.com have been sync once on staging-server.
* Master branch is now python 3.

Next steps: switch off the current prod, and redirect to staging-server.

Then our hands will be free to upgrade the current prod-server.

**Comment by karlcow** [comment]
# OKRs check / 2019-09-01

* slightly late. had roadblocks with the fabfile for deployment.
* will make progress this week.

**Comment by karlcow** [comment]
## OKRs check / 2019-09-15

* This is done. 🎉 🎈 😂 
* To remember that the initial study for this was started on September 28, 2016.
* Thanks to @miketaylr for pairing on the latest development.
