### ISSUE TITLE
2019Q3 - 3.3 Verify sitewait bugs monthly

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#96]
Let's try to verify sitewait bugs 3 times this quarter, once a month and see how it goes in terms of cadence.

**Comment by softvision-sergiulogigan** [comment]
We are now continuing to verify the Sitewait issues that have no severity label applied.
We're at 82 out of 379.
http://tinyw.in/XJlR

**Comment by softvision-sergiulogigan** [comment]
295/379 - 84 more to go, from the first (partial) run.

We think we can run again the whole sitewait list, until the end of the quarter.

**Comment by miketaylr** [comment]
note: Monthly is probably not a realistic target (maybe, we'll know at the end). Probably once a quarter would be OK.

**Comment by softvision-oana-arbuzov** [comment]
We finished verifying the Sitewait issues with no severity label applied and bellow is the result:
- Fixed: 170 / 379 ~ 44.85%
- Invalid: 77 / 379 ~ 20.31%
- Reproducible: 132 / 379 ~ 34.82%

We will start another run as soon as Adam provides us with the new list of Site wait issues.

**Comment by softvision-sergiulogigan** [comment]
We began a new round of Sitewait issues verification.

Sitewait - Critical - **DONE**

Fixed: 9/76
Invalid: 2/76
Reproducible: 65/76

Sitewait - Important - **DONE**

Fixed: 7/107
Invalid: 7/107
Reproducible: 93/107

Sitewait - Minor - **DONE**

Fixed: 8/46
Invalid: 1/46
Reproducible: 37/46

Sitewait - no_label - **DONE**

Fixed: 7/42
Invalid: 1/42
Reproducible: 34/42

**Comment by miketaylr** [comment]
We did 1/3 of what we wanted to do here. Too ambitious. :)

Probably worth attempting again in 3 months.
