### ISSUE TITLE
2019Q3 - 3.4 Verify Top 10 TSCI bugs weekly

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#97]
Each week, by the end of the week, we should ensure all reports from the top 10 domains are triaged. For triaged bugs, we should ensure the bugs still reproduce. If they don’t, we can close them. If they do, we don’t need to add a comment (which will get noisy over time). 

For bugs that are in the sitewait milestone, we should re-test them and close if they are fixed.

(If this can be done in a single day, it’s probably best to wait until Friday -- the bugs are counted on the weekend, and this will ensure the data that’s recorded is “freshest”.)

The TSCI can be found at https://docs.google.com/spreadsheets/d/1rmH1EhTVZBtTIXXwqSHcaQXhmv7xJh2Y2LuNiySPURQ/edit?ts=5cf460c1#gid=1309019086, the Top 10 may change over time so it's best to consult the latest data we have, rather than list them here.

**Comment by miketaylr** [comment]
TSCI driven dev https://docs.google.com/document/d/1R4xzyCqedPrC_kxPMiFkG-Pn4LpKykjwXs8fJWd_yHo/edit#

**Comment by softvision-sergiulogigan** [comment]
Progress document: http://tinyw.in/Jypb

**Comment by miketaylr** [comment]
Update: on track, continuing weekly.
