### ISSUE TITLE
2019Q4 - 1.1 Revisit Sitewait Issues Once

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#98]
By the end of the quarter, we should re-triage/verify each of the issues in the sitewait milestone.

**Comment by softvision-oana-arbuzov** [comment]
Progress can be found here: https://docs.google.com/spreadsheets/d/1jpdTFvBF1_SMHbaCtWwuG6aAVCV35dTBS8l9rI4plQc/edit?ts=58df1d37&pli=1#gid=1975566373

**Comment by miketaylr** [comment]
Update: 123 to go. Looks good finish on time.

**Comment by softvision-oana-arbuzov** [comment]
We finished verifying all SiteWait issues: 
- Still reproducible: 256/279
- We closed 8.3% issues as fixed or invalid.
