### ISSUE TITLE
2019Q4 - 1.2 TSCI testing

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#99]
Dedicated testing sessions of the top 10 domains

**Comment by softvision-oana-arbuzov** [comment]
Current progress:
[Done] linkedin.com - mobile & desktop
[Done] baidu.com - mobile & desktop
[Done] wikipedia.org - mobile & desktop
[Done] amazon.com - mobile & desktop
[Done] microsoft.com - mobile & desktop
[In progress] twitter.com, youtube.com, netflix.com - desktop

More info here: https://docs.google.com/spreadsheets/d/1jpdTFvBF1_SMHbaCtWwuG6aAVCV35dTBS8l9rI4plQc/edit?ts=58df1d37&pli=1#gid=1364523700

**Comment by cipriansv** [comment]
Testing the top 10 domains from the TSCI list is done.

The covered areas and the results can be found here:
https://docs.google.com/spreadsheets/d/1jpdTFvBF1_SMHbaCtWwuG6aAVCV35dTBS8l9rI4plQc/edit#gid=1364523700

**Comment by softvision-sergiulogigan** [comment]
Issues found: 
#46670
#46671
#46675
#46050
#46053
#45929
#45919
#45921
#45555
#45613
#45553
#45619
#45615
